### ISSUE TITLE
Signature does not match

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#1001]
This error seems to be raised by several nodes these days. However, if we copy the DB to another computer, then the issue cannot be reproduced. We can eventually reproduce the issue even when restarting the node, but the priviledged method to debug this issue is to debug with node-inspector + signal SIGUSR1.

**Comment by RavanH** [comment]
Bonjour Cédric, j'ai eu ce problème avec mon compte il y a trois jours mais le lendemain c'était résolu tout seul si ce n'a rien a voir avec changer le nœud dans Cesium plusieurs fois... je sais il y a des autres qui ont toujours ce problème (malgré changer de nœud) et donc peuvent toujours pas faire leur demande de certification. Tous ont créé leur idenité sur https://g1.duniter.fr donc Cesium 0.12.7 ... ça vient de là peut-être?

**Comment by c-geek** [comment]
Donc finalement l'erreur provient du build 1.2.6 de Duniter, qui contient des modules en mauvaise version.

Je ne vais pas faire de release corrective, la 1.3.x arrivant très bientôt, et par ailleurs j'ai corrigé le problème sur le serveur g1.duniter.org en recompilant manuellement le nœud.

Donc il suffit d'utiliser un Cesium normalement, connecté au nœud g1.duniter.org. Par contre, peut-être que la propagation aux autres nœuds ne se fera qu'après avoir reçu au moins une certification.

**Comment by c-geek** [comment]
Version 1.3 disponible : https://duniter.org/fr/duniter-version-1.3

**Comment by RavanH** [comment]
Pas de version Mac ?

**Comment by c-geek** [comment]
Non, mais la version .tar.gz fonctionne peut-être ? Sinon il suffit de builder les sources : 

    git clone https://github.com/duniter/duniter.git
    cd duniter
    npm install

Puis [les commandes Duniter](https://duniter.org/fr/wiki/duniter/commandes/) devraient fonctionner.

**Comment by c-geek** [comment]
Exemple : 

    ./bin/duniter --version
