### ISSUE TITLE
Strange reboot !?

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#1033]
Je viens de redémarrer la machine, relancé duniter, au lieu d'avoir 196 blocs calculés il m'en a affiché 84, comme il y a x jours quand j'ai démarré le noeud. Là il synchronise au bloc #15500...

Donc après arrêt du noeud, reboot machine, duniter webstart, il fait comme s'il reprenait tout depuis le jour où j'ai lancé cette machine à plein temps dessus...

**Comment by c-geek** [comment]
Ça ressemble à une installation avec 2 BDD. L'un des process ne serait-il pas lancé en `root` tandis que l'autre le serait avec l'utilisateur local ?

**Comment by c-geek** [comment]
Duniter prend par défaut le dossier `$HOME`. Donc ce dossier dépend de l'utilisateur avec lequel est lancé Duniter. Faire un `sudo` modifie la valeur du `$HOME`.

**Comment by galuel** [comment]
Oui j'ai lancé alternativement sudo duniter start, et duniter start seulement, je ne sais pas dans quel ordre.

Si je lance duniter webstart, j'obtiens ça : 

~$ sudo duniter stop
duniter_default daemon is not running
~$ duniter webstart
Starting duniter_default daemon...
duniter_default daemon failed to start:  Failed to write pidfile (EACCES)
~$ duniter webstart
Starting duniter_default daemon...
duniter_default daemon failed to start:  Failed to write pidfile (EACCES)
~$ sudo duniter webstart
Starting duniter_default daemon...
duniter_default daemon started. PID: 4640
~$ duniter logs
2017-07-12T09:28:46+02:00 - warn: Waiting for the end of pulling...
2017-07-12T09:28:50+02:00 - info: Block #15744 added to the blockchain in 3297 ms

**Comment by galuel** [comment]
Ah oui je sais ! Je l'ai lancé auparavant sur un autre utilisateur... oublié...

**Comment by galuel** [comment]
Résolu, faut lancer avec le bon utilisateur... bref :)
