### ISSUE TITLE
Node do not run on ts branch

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#1040]
On `ts` branch, I restarted my node, and the daemon says duniter is not running.

I tried a global resync, and still same issue.

I tried on `dev` branch and did not encounter this problem.

It is not linked to https://github.com/duniter/duniter/issues/1039 as I was on a previous commit where this those errors was not present.

**Comment by M5oul** [comment]
I encounter some network issues.
I can not contact my node.
And the node can't contact other nodes, which make it compute already found blocks.

**Comment by c-geek** [comment]
Seems to work now. Also not that `ts` branch has been merged to `dev` branch.

**Comment by M5oul** [comment]
In fact, it is fixed!
