### ISSUE TITLE
 Duniter et le choix du contenu des blocs

### ISSUE THREAD

**Issue by gerard94** [duniter/duniter#1053]
Reference : [forum.duniter.org](https://forum.duniter.org/t/duniter-et-le-choix-du-contenu-des-blocs/2968)
As the peer to peer network brings already a bit of randomness in the choice of blocks contents, It could be easier and more uniform to go on this way and randomize the whole contents as soon as concurrency is concerned.

**Comment by c-geek** [comment]
I will simply apply an array shuffle before trying to add the newcomers in the block.

http://underscorejs.org/#shuffle
