### ISSUE TITLE
Add a new P2P network protocol

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#1056]
For calculators only.

**Comment by c-geek** [comment]
Here is the plan: we *won't* build another network interface, the new P2P protocol will rely on the existing BMA. It will be added a WebSocket URL like `/ws/p2p`.

This is URL will allow WebSocket connection, and will be *exclusively reserved to member nodes*. To ensure this behavior, at the connection step a challenge will be sent to the connecting peer to sign a document with a random hash in it provided by the server peer. If the signature matches, and the signing key is a member, then the connection can be established.

Once the connection is set, we have a 2-way tunnel for sending/receiving documents: blocks, identities, transactions, etc.

We would have 3 zones of connection: *incoming*, *outcoming*, *sibling*.

* **incoming** would correspond to connections initiated by an external peer. Size 10.
* **outcoming** would correspond to connections initiated by the local node. Size 10.
* **sibling** would correspond to incoming connections with the same pubkey as the local node. Size unlimited.

A same pubkey (of a peer) cannot be more than once in the incoming+outcoming zone. The idea is to avoid connecting to a node that we already have a channel with.

Also, the usage of the legacy HTTP multicasting (through BMA URLs like `POST /blockchain/block`) would be lowered, yet still enabled and available. This allows mirror nodes to be in the place, which would still receive blocks and data through this legacy connection. Also, these mirror nodes would themselve share new documents to member nodes through this API.

**Comment by Insoleet** [comment]
> Here is the plan: we won't build another network interface, instead the new P2P protocol would rely on the existing BMA

I thought it would have been a good start to depend less on BMA, since this API is getting older and older. If we want to replace BMA one day, I think we should have less things depending on it.

**Comment by c-geek** [comment]
I don't have the energy to do it. So I recycle this old stable API until someone gets hangry enough to build a new one.

**Comment by c-geek** [comment]
Let's delay this feature to 1.5.0 to give it a chance to be implemented in a specific endpoint.

It could be the occasion to refactor this networking code.

**Comment by c-geek** [comment]
This issue is now a.k.a WS2P (#1084).
