### ISSUE TITLE
duniter-ui refuse to install a module via it's npm format : module-name@version

### ISSUE THREAD

**Issue by librelois** [duniter/duniter#1065]
I publish my duniter module on npm and I managed to install it on cli : 
duniter plug duniter-currency-monit@0.4.4

but when i try on web interface i get this error message :  "Package URL as wrong format"

**Comment by c-geek** [comment]
Are you sure that you pick the .tar.gz? The .zip does not work, indeed.

**Comment by c-geek** [comment]
Oh sorry, I just noticed that you were using NPM publishing.

Yes it fails in the UI, it's a bug.

**Comment by c-geek** [comment]
Please retry with Duniter 1.4.10 release.

**Comment by librelois** [comment]
yes it's work, thanks :)
