### ISSUE TITLE
Ucoin dans Duniter ui

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter#1077]
Mauvais lien pour le fichier conf.json 
ça devrait être : `~/.config/duniter/duniter_default/`

![duniter 1 4 15](https://user-images.githubusercontent.com/11737560/29412526-7b566a94-8359-11e7-8465-3ee2e6c75d71.png)

**Comment by librelois** [comment]
If we don't release a new version 1.6, it will be for 1.7.
