### ISSUE TITLE
Bug - v1.5.4 - Try to bind 10901 in any cases

### ISSUE THREAD

**Issue by florck** [duniter/duniter#1082]
Following upgrade to 1.5.4, I observe that duniter tries to bind port 10901 at startup even if it is not configured that it listens this one.
Configuration used :
https://gist.github.com/florck/09a1423432059300354352fe4784b7c1 
Error observed with an other anonymous node on this machine:
https://gist.github.com/florck/de946759c0df63711808c98292ec2858
Peering that confirms 10901 not used for this peer:
https://duniter.floth.fr/network/peering

**Comment by c-geek** [comment]
This seems legit, I see this in your conf:

     "port": 10901,

**Comment by florck** [comment]
Well caught.
Can't explain myself why before this was working.
No bug.
