### ISSUE TITLE
Gérer le préfixe de pair manuellement dans la configuration du nœud 

### ISSUE THREAD

**Issue by librelois** [duniter/duniter#1126]
BMA gère le préfixe de pair (premier caractère du nonce) afin d'éviter que deux nœuds partageant la même clé ne calculent la même preuve.  WS2P ne le gère pas encore.

**Comment by c-geek** [comment]
Je retranscrit mon message laissé sur le salon XMPP : 

> Après il y a quand même une problématique technique, c'est que les nœuds privés ne se publient pas dans la fiche de pair. Il n'y a donc aucun moyen de les détecter, sauf à savoir soi-même qu'on a plusieurs nœuds. Au final je me demande si le plus simple ce n'est pas de pouvoir gérer de façon générale ce préfixe dans la configuration de chaque nœud, indépendamment de ses API disponibles.

**Comment by librelois** [comment]
Dans le cadre de l'abandon futur de BMA, et afin que le code du cœur soit indépendant de l'API utilisée, il est effectivement préférable que le préfixe de pair soit saisi manuellement par l'utilisateur sur chacun de ses nœuds membre. je renomme l'issue.

**Comment by librelois** [comment]
@c-geek aoutch grand moment, ma 1ere contribution au code du cœur, j'ai peur d'avoir fait complètement n'importe-quoi mais toujours est t'il qu'en test ça fonctionne, mes nonce commence bien par le préfix que je configure !

J'ai voulu désactivé l'action de bma sur le préfix du nonce en supprimant le code qui fait le lien dans PeeringService.ts, et dans provert.ts mais comme je ne suis pas sûr de moi j'ai juste commenter dans un 1er temps.

**Comment by M5oul** [comment]
You may have push your modification on a new branch.

**Comment by c-geek** [comment]
Je mets en milestone 1.6 car le code m'a l'air bon et que je vais de toute façon livrer 2 autres correctifs, cela peut faire partie du même wagon.

**Comment by librelois** [comment]
Ok la prochaine fois je pousserai dans une nouvelle branche puis ferai une MR into dev, je ne savais pas que c'était la procédure :)

**Comment by c-geek** [comment]
Finalement j'ai fait quelques tests et il apparaît que la valeur max sûre est 899 pour le préfixe. Je vous laisse lire le commentaire pour comprendre pourquoi.

**Comment by c-geek** [comment]
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/MAX_SAFE_INTEGER
