### ISSUE TITLE
WebUI: Network view: display siblings?

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#1148]
I am not sure, but I think siblings (nodes with the same pubkey) are displayed as one node here:

![image](https://user-images.githubusercontent.com/969136/31405206-a77ac528-adfe-11e7-8593-845fcd6bb974.png)

**Comment by librelois** [comment]
I found the origin of the problem in the heart of duniter, I'm feeling like checking if there is also a problem with duniter-ui

**Comment by librelois** [comment]
Now the headsCache of the node contains several heads with the same key (1 per endpoint ws2p). But I don't see 2 heads of the same pukkey in duniter-ui, I think there's still a problem in duniter-ui.

**Comment by librelois** [comment]
I changed the headsMap index in duniter-ui (https://github.com/duniter/duniter-ui/commit/741932100f6303abdcb20726a004fbf64834b2df) but the tests are still not conclusive so I should be able to debug duniter-ui with the most recent duniter code.

@c-geek, can I create a pre-release duniter 1.6.11 that will not be built but will only be used for the environment to develop duniter-ui ?

**Comment by c-geek** [comment]
You don't need a release for that. Let met explain the trick:

* go into duniter core, and run `yarn link`
* go into duniter-ui, and run `yarn link duniter` 

Now un duniter-ui, the duniter module is *exactly* the code you have in the duniter core of your development environment!

Also, your tests are probably not conclusive because you miss a command in duniter-ui that *generates* the app.js:

    ./node_modules/brunch/bin/brunch build

This command actually gathers all the web sources (*.jade, *.html, *.css, *.js, ...) and compiles them to "app.js", "templates.js", "libraries.js", "*.css", ...).

You need to run this command every time you touch to a UI file. Or you can use the watching version:

    ./node_modules/brunch/bin/brunch watch

Anyway, before commiting, please run again the `build` and commit all the files. This is very specific to UI, this is a bad practice to commit the compiled files, but for now I get duniter-ui working this way.

**Comment by librelois** [comment]
Thank you very much for these explanations, it's going to be very useful to me, I'll rebuild a clean build to dunite-ui this midday.
