### ISSUE TITLE
Parsing lock function in transaction document 

### ISSUE THREAD

**Issue by maxime4duniter** [duniter/duniter#1159]
https://forum.duniter.org/t/doc-protocol-example-tx-format/3325/23

if a lock function is present  > alone < in document like XHX
we cant make an unlock to retrieve source...

so, duniter have to check the input transaction document to see if the output field contain a lock function like XHX (have to check CSV/CLTV) present alone without any others SIG conditions.

**Comment by librelois** [comment]
resolute
