### ISSUE TITLE
Is Stepmax hardcoded to 3 again?

### ISSUE THREAD

**Issue by Folatt** [duniter/duniter#1167]
I don't see stepmax being an option in the parameter wizard.

**Comment by librelois** [comment]
there is no command to fill in the parameters of a currency, you have to inject them hard into a modified version of the code, a minima on the node that will write the zero block.
it happens here: https://github.com/duniter/duniter/blob/dev/app/lib/constants.ts#L123-L144

We could very easily create options to configure the currency parameters but that would make it too easy to launch a new currency...
It is a complex act that must be thought through at length:)
