### ISSUE TITLE
Update doc contribute-french

### ISSUE THREAD

**Issue by vincentrou** [duniter/duniter#1171]
It seems that the documentation needs some update.
For example, the web ui is not a git submodule anymore https://github.com/duniter/duniter/blob/master/doc/contribute-french.md#installer-linterface-graphique

Add tutorial for vscode instead of webstorm ?

**Comment by librelois** [comment]
@c-geek  is currently working on it : 
https://forum.duniter.org/t/noeud-raspberry-pi-toujours-suffisant-pour-calculer/3514/40?u=elois

**Comment by c-geek** [comment]
A new tutorial is available here: https://duniter.org/fr/wiki/duniter/tutoriel-dev/
