### ISSUE TITLE
Error in unit test

### ISSUE THREAD

**Issue by vincentrou** [duniter/duniter#1173]
I follow this tutorial : https://github.com/duniter/duniter/blob/master/doc/contribute-french.md#lancer-les-tests
I get an error when I call `npm test`
>   634 passing (2m)
>   1 failing
> 
>   1) HTTP API "before all" hook:
>      Uncaught Error: listen EADDRINUSE 127.0.0.1:7778
>       at Object._errnoException (util.js:1024:11)
>       at _exceptionWithHostPort (util.js:1046:20)
>       at Server.setupListenHandle [as _listen2] (net.js:1351:14)
>       at listenInCluster (net.js:1392:12)
>       at doListen (net.js:1501:7)
>       at _combinedTickCallback (internal/process/next_tick.js:141:11)
>       at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by librelois** [comment]
yes the tests on the master branch does not pass any more it is no longer up to date, made the tests on the branch dev

**Comment by vincentrou** [comment]
Ok thanks test are passing.
So what is the git workflow ?
The dev is the default branch and master is no more used ? So PR should be made on dev branch ?

**Comment by librelois** [comment]
The master branch is maintained only for documentation purposes, so if your contribution concerns documentation, submit your PR on the master branch.
For the code instead, submit your PR on the dev branch.
The other branches are dev forks on which members of the duniter organization work (for example now I'm working on the proxy branch)
