### ISSUE TITLE
Two launching guides

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#118]
It would be great to have two differents guides:
- one to join an existing monetary system;
- and the other one to create a monetary system.

**Comment by mcl1234** [comment]
To join an existing community : to do 
To create a community : https://github.com/duniter/duniter/wiki/Launching-a-new-money

**Comment by M5oul** [comment]
I do not found this issue very relevant now.

**Comment by mcl1234** [comment]
it depends of your relativity ? :)

**Comment by M5oul** [comment]
Yep,
moul(t) ≠ moul(t + 1)

**Comment by M5oul** [comment]
With current web admin, we could add explanations when creating a currency.

**Comment by M5oul** [comment]
I close as I don't find this ticket relevant now.
