### ISSUE TITLE
BUG: {{ message | translate:'{number: current_number}' }}

### ISSUE THREAD

**Issue by GammaNu** [duniter/duniter#1196]
Contexte : 
Installation fraiche de Duniter-desktop-windows sur une machine qui n'a jamais accueilli de noeud. (windows7)

Avast n'est pas content de ne pas connaitre l’exécutable de l'installeur, jusqu'ici rien de choquant. Je l'autorise manuellement.
Après installation, je lance est là : 
La fenêtre Duniter 1.6.13 s'ouvre, le logo Duniter apparait brièvement puis j'ai un cercle qui tourne (chargement en cours) suivi du message : 
`{{ message | translate:'{number: current_number}' }}`
qui reste indéfiniment.
J'ai essayé de copier la config d'un nœud existant, ça à l'air de se passer mieux sans pour autant fonctionner parfaitement, mais ça c'est un autre problème. Pour un nouvel utilisateur, le fait que ça ne se lance pas correctement d'entrée de jeu me semble très gênant.

**Comment by GammaNu** [comment]
PS : dans `C:\Users\<nomUtilisateur>\.config\duniter\duniter_default`
remplacer en ligne 2 :
` "currency": null,`
par : 
` "currency": "g1",`
semble corriger le problème.

Du coup il manque un écran de sélection de la monnaie ? ou il existe mais ne se charge pas ?

**Comment by GammaNu** [comment]
Et pour que la syncro se termine correctement (la partie download c'est bien passé mais j'avais une erreur sqlite d'accès simultannée même après un reboot du pc pour la partie "Applying..." j'ai du supprimer le fichier duniter.db avant de relancer duniter. (alors qu'il s'agissait du duniter.db qu'il avait créé tout seul).

**Comment by c-geek** [comment]
> Pour un nouvel utilisateur, le fait que ça ne se lance pas correctement d'entrée de jeu me semble très gênant.

Tu n'es pas le 1er utilisateur Windows, loin de là, et ce bug tu es le 1er à le remonter.

J'ai des doutes sur le fait que, dès le tout 1er lancement, tu tombes sur l'écran affichant `{{ message | translate:'{number: current_number}' }}`. À mon avis tu as commencé par l'écran de sélection entre synchro et import d'ancienne sauvegarde.

Éventuellement la synchro a échoué, puis tu as rencontré le bug. Là oui ça me paraît cohérent, car so la phase d'application de la blockchain échoue, le nœud est dans un état instable.

N'est-ce pas plutôt ce scénario qui s'est produit ?

**Comment by librelois** [comment]
Bonjour @GammaNu et merci pour votre test.

Sachez que la version 1.6 n'est pas encore officielle, nous attendons justement des retour comme le votre pour la finalisée :)

Je viens de corriger l'origine du bug, causé par une de mes contributions.

**Comment by c-geek** [comment]
Tu peux le vouvoyer, mais je pense que tu le connais : c'est l'homme qui marche pieds Nu !

**Comment by librelois** [comment]
haha merci je n'est pas fait le lien entre le pseudo GammaNu et 1000i100 ^^
