### ISSUE TITLE
Avoid the DDoS attack by transactions

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#157]
This is an issue Bitcoin encountered, as explained here: http://motherboard.vice.com/read/great-job-everyone-bitcoiners-are-ddosing-bitcoin

**Comment by c-geek** [comment]
The issue seems to be that it is possible to make transactions with very low amounts, hence having a tremendous number of transactions being sent to consume every single fraction of Bitcoin available.

The Bitcoin client is overwhelmed by the number of legitimate transactions.

**Comment by c-geek** [comment]
Here, the very first solution is to have a spam solution (see #374). So once the sandbox is full, new transactions get refused.

Also, uCoin won't suffer the same way as Bitcoin since we have individual "miners" with rotations in writing, so each user do not need to get all the transactions. They may even prioritize their personal transactions first.

**Comment by galuel** [comment]
It seems nice.

**Comment by c-geek** [comment]
Duplicate of #374.
