### ISSUE TITLE
Instanciate several nodes with the same key

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#219]
Currently, each node emits it peering document across the network with a single interface that is known by him.

But one might want to instanciate several nodes under the same key. The problem is, today each node with the shared key will only declare its own interface, erasing the one of the other node.

This lead to a never ending switch of interface behing the shared key.

A solution would be, given the fact each instance publishes an interface, that each node recognizes another node shares the key with him as it is receiving a the peering document containing this interface *the local node did not write*.

So the local node could test the remote interface for fact checking, and if the interface answers, to *add the local interface* to endpoint list instead of overwriting local interface.

**Comment by c-geek** [comment]
And whenever the *non local* interface does not answer, the local node removes it from the peer document.

This issue is also linked to #337: if an unknown interface is written, the node should not remove it.

Linked to #499 as well, because we need to set a maximum length to the `Endpoints` field.

**Comment by c-geek** [comment]
Few words about the fix:

### Usage
To use it, you don't have any particular thing to do. It is fully automated.

### Recognition
Nodes will recognize other nodes with the same key, because they will find interfaces different from their personal one when receiving the peer document.

On document reception, each peer with the shared pubkey will check if the node is UP and has valid interface. It it fails, the interface is removed and a new peer document without the interface is generated. If it succeeds however, the interface is kept and will remain in the peer document (even when this document is regenerated, which occurs today every 30 minutes).

### Forwarding
When a new document is received/generated in Duniter, the node shares it with other nodes. This behavior remains, but we add an *extra* forwarding to *mirror peers*. That is, each node with a shared pubkey considers its mirrors as very important to have the same informations as local node and will broadcast them each new document.

We can see such mirror broadcasting in the logs through `Mx_` prefix while multicasting:

```
--> new Peer to be sent to 3 peer(s)
 `--> to peer M0_HgTTJLA [------] (localhost:10000)
 `--> to peer M1_HgTTJLA [------] (localhost:10001)
 `--> to peer M2_HgTTJLA [------] (localhost:10002)
```

**Comment by blavenie** [comment]
Excellent cette correction !
On va donc pouvoir faire du load balancing, non ?
par exemple avec un frontal [nginx configurer avec plusieurs noeuds](http://nginx.org/en/docs/http/load_balancing.html)

je vais tester ca !

**Comment by c-geek** [comment]
Oui, encore que le load balancing c'était déjà possible avant ... puisque les 2 noeud ont la même pubkey et la même interface distante.

Là, c'est avoir 2 noeuds avec pubkey identiques mais DNS/IP différentes.

**Comment by M5oul** [comment]
I doubt it works fine.
When I request nodes on the network on `/networks/peers`, they know only one of my member node.

**Comment by M5oul** [comment]
Finally, it's ok:
```bash
curl http://moul.re:8999/network/peering
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API misc.moul.re 78.227.107.45 8999",
    "BASIC_MERKLED_API desktop.moul.re 78.227.107.45 2a01:e34:ee36:b2d0:e79:cd45:ed65:147 24723"
  ],
  "block": "38338-0000FDEA57D2784A1E0F6288E7B5C5312D6E3A42021833288C9D99FAFE5F80C8",
  "signature": "CFsAT5VnDnRcCDRK17iOVmIe4JB+jxwVka02z8hX/c5Ox07hhNTZRcopyxx83J13qPOV7OKBVgrPhqhRpIrSBw==",
  "raw": "Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3\nBlock: 38338-0000FDEA57D2784A1E0F6288E7B5C5312D6E3A42021833288C9D99FAFE5F80C8\nEndpoints:\nBASIC_MERKLED_API misc.moul.re 78.227.107.45 8999\nBASIC_MERKLED_API desktop.moul.re 78.227.107.45 2a01:e34:ee36:b2d0:e79:cd45:ed65:147 24723\n",
  "pubkey": "J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3"
}⏎
```

**Comment by c-geek** [comment]
Maybe you understood the way it works: actually the 2 nodes go on the network thinking it is alone with its key, but if at some point it receives a Peer document with informations inconsitent with its network configuration, *the node assumes there might exist another node with the same key*.

So node A checks the given network interface in Peer document made by B, and if it answers, considers it is a valid second (third, fourth, ...) interface for this pubkey, and rewrite a new Peer document including interface A.

So we now have a Peer document with interfaces A and B. Of course B receives this document, sees its B interface, but also this A interface. If A is reachable, B does nothing more. But if A does not answer, B removes the interface A and reforge a new Peer document.

That's it!
