### ISSUE TITLE
Add CLI testing

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#222]
It should be found a way to test the CLI to avoid regressions on commands.

**Comment by cchaudier** [comment]
For this we can use bats https://github.com/sstephenson/bats
If you describe thes tests I can write them or we can do a pair programming session.

**Comment by c-geek** [comment]
Well the idea is to test the reaction of duniter commands according to some scenarios like:

```json
node bin/ucoind reset config
node bin/ucoind start
```

The `star` duniter command should fail, as no network configuration is available (`reset config` removed the network configuration, which is absolutely required to start).

I do not have all the tests in mind yet, but you get the idea.

**Comment by c-geek** [comment]
I tried to have another approach (commit ce704362dc5ca949bb0bbe97f1b84c153eaa934b) giving the possibility to make the tests "almost" like a command line call, but staying in JS unit tests.

The benefit to stay with JS is that it also feeds our code covering tool, whereas it would not with bats (I suppose).

However bats may be useful for #469 maybe?
