### ISSUE TITLE
Peer documents are not cleaned correctly

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#333]
In sakia, we can see twice @M5oul node.

One with his current pubkey, and another one with an old pubkey he published a some time ago.

We can see it here : 
https://moul.re/ucoin/network/peers
His wrong node (6YfbKWKkwsW2u8ZG168uHtpKd52cM66zqRSG5g44f6mg) is present, but the good one is present too (J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3)

**Comment by M5oul** [comment]
https://github.com/duniter/duniter/issues/426
