### ISSUE TITLE
Allow peer to have additional protocols (e.g. ES indexation)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#337]
Allow a peer document to declare additional protocol (not BASIC_MERKLE_API).
e.g. add a ElasticSearch indexation, for mobile application.

=> using a config entry ?

Use : a client app (e.g. mobile app) could found (using the signed peer document) that a node has optimized features enabled, and use it. (BMA need many HTTP request to get all user data)

**Comment by c-geek** [comment]
Yes, thanks for having added an issue.

**Comment by c-geek** [comment]
I will add a field under conf.json where additionnal endpoints can be entered. The file could be edited in two ways:

* using system tools
* through Duniter UI: a specific screen will be available to add endpoints

**Comment by c-geek** [comment]
I won't do the UI part, it's not the good moment. However you can do it using CLI:

### Add an endpoint

    duniter config --addep "SUPER_ENDPOINT_ELASTIC_SEARCH cgeek.fr blablabla 21020"

Will result in:

```json
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API cgeek.fr 88.174.120.187 2a01:e35:8ae7:8bb0:b468:a0c:a607:379f 9330",
    "BASIC_MERKLED_API 88.174.120.187 9333",
    "SUPER_ENDPOINT_ELASTIC_SEARCH cgeek.fr blablabla 21020"
  ],
  "block": "44041-0000297B14119AC6710D493D773821B11E016DBE317E778FF8B0B5BC347B8039",
  "signature": "tgNB44JiHBuP3G1DsQthkTFBrghNX7me1R5XACx15SQ1RC39yuqhaHWhy94rYttJRgsWNPOQPRmfuEDs6bM7BQ==",
  "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk"
}
```

### Remove an endpoint

    duniter config --remep "SUPER_ENDPOINT_ELASTIC_SEARCH cgeek.fr blablabla 21020"

Will result in:

```json
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API cgeek.fr 88.174.120.187 2a01:e35:8ae7:8bb0:b468:a0c:a607:379f 9330",
    "BASIC_MERKLED_API 88.174.120.187 9333"
  ],
  "block": "44041-0000297B14119AC6710D493D773821B11E016DBE317E778FF8B0B5BC347B8039",
  "signature": "tgNB44JiHBuP3G1DsQthkTFBrghNX7me1R5XACx15SQ1RC39yuqhaHWhy94rYttJRgsWNPOQPRmfuEDs6bM7BQ==",
  "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk"
}
```

### Precautions

A good practive is to set this configuration on **one node exclusively**, which will handle the specific endpoints. Because if you have:

* one node which adds the endpoint `EP1`
* one node which removes the endpoint `EP1`

Then you will fall in [ping-pong loop](http://fr.duniter.org/cles-partagees/#lestockdeblockstamp), which will consume all the available blockstamps for declaring your endpoints.

**Comment by M5oul** [comment]
It's not working well:
```bash
duniter config --addep "BMAS moul.re 78.227.107.45 443 /duniter/api"
2016-10-24T13:27:08+02:00 - debug: Plugging file system...
2016-10-24T13:27:09+02:00 - debug: Loading conf...
2016-10-24T13:27:09+02:00 - debug: Loading crypto functions...
2016-10-24T13:27:09+02:00 - error:  Error: TypeError: Cannot read property 'indexOf' of undefined
    at Error (native)
    at /opt/duniter/sources/app/cli.js:759:15
    at process._tickCallback (node.js:412:9)
2016-10-24T13:27:10+02:00 - error:  Error: TypeError: Cannot read property 'indexOf' of undefined
    at Error (native)
    at /opt/duniter/sources/app/cli.js:759:15
    at process._tickCallback (node.js:412:9)
```

**Comment by c-geek** [comment]
Try with SBMA instead.

**Comment by M5oul** [comment]
Same:
```bash
duniter config --addep "SBMA moul.re 78.227.107.45 443 /duniter/api"
2016-10-24T16:32:56+02:00 - debug: Plugging file system...
2016-10-24T16:32:57+02:00 - debug: Loading conf...
2016-10-24T16:32:57+02:00 - debug: Loading crypto functions...
2016-10-24T16:32:57+02:00 - error:  Error: TypeError: Cannot read property 'indexOf' of undefined
    at Error (native)
    at /opt/duniter/sources/app/cli.js:759:15
    at process._tickCallback (node.js:412:9)
2016-10-24T16:32:57+02:00 - error:  Error: TypeError: Cannot read property 'indexOf' of undefined
    at Error (native)
    at /opt/duniter/sources/app/cli.js:759:15
    at process._tickCallback (node.js:412:9)
```

**Comment by c-geek** [comment]
OK, the problem was coming from `duniter.sh` script, ignoring the quotes.

**Comment by M5oul** [comment]
I could add upper custom endpoint.
It's inside the configuration file.
But, even if the node is restarted, the endpoint isn't present on `network/peering`.
May be a conflict with the fact that there is two nodes sharing same pubkey?

**Comment by c-geek** [comment]
Weird, I could reproduce your bug at a moment but mine is now correct: http://cgeek.fr:9330/network/peering.

```json
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API win-dev.cgeek.fr 88.174.120.187 33036",
    "BASIC_MERKLED_API cgeek.fr 88.174.120.187 2a01:e35:8ae7:8bb0:b468:a0c:a607:379f 9330",
    "BMAS cgeek.fr 443 /duniter/api"
  ],
  "block": "52027-00000D7A8106D812D2AB393AEE50A3E1379688EC6BECA65BCF8ED944D509826A",
  "signature": "z6fASYSQ3QGlouoN1mOqfbWNU9MXNhsvKYuLITHu2uMaM2+zLaRyC715tbIX09HemSJ5CUXSxYqzqQ5AqmYECA==",
  "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk"
}
```

**Comment by c-geek** [comment]
OK: as soon as I shutdown the node which writes "BMAS", the 2 endpoints of this node disappear.

**Comment by c-geek** [comment]
Hope it will be better that time. You need all your nodes to include commit 91e7ae89e3a613efdc03c96279ceb5a3505b6f37 for BMAS endpoint to work.
