### ISSUE TITLE
Identity spam: a solution

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#374]
The initial raised problem is to know if new identities had some "problem to solve" to avoid DDOS attacks by sending and writing to the blockchain new identities that were massively generated.

To this, I answered that identities cannot be written without matching the WoT rules, so it is not that easy. During the time identities are being certified, they are in a sandbox of the nodes.

Yet, it is still possible to spam the sandbox of each node.

So @galuel proposed that:

> une possibilité serait que même une demande dans le bac à sable soit à minima validée préalablement par un membre (ce qui ne serait pas équivalent à signer). par le membre dépositaire du noeud en question pour être plus précis.

Which I would traduce by:

> nodes could refuse any new identity by default, requiring an initial validation from an existing member to be added to the node (which would be a different thing than certification).

This is a good idea, which made me imagine another:

> a given node could even *refuse any new identity* in its sandbox if it was not signed by an authorized key. By default, the only authorized key is the one of the local node. But the owner of a node can also manually or automatically add other authorized keys.

### First scenario: add your node and use it to publish your identity

This is a typical case where you do the most by yourself and don't ask anything to other people than getting certifications for your identity.

#### 1. Install your node

You download Duniter and create your identity in it. This is your node, you control it, you can add your identity in it. No problem.

#### 2. Connect it to the network

This is automated procedure, but just to mention you have to be connected to the network.

#### 3. Ask for certifications

People will be able to find your identity **on your personal node**. Once they certify it, their node will also add it to their database since the public key of the certification will match the key of the node.

The more certifications you get, the more your identity is spread over the network, the more nodes will accept to write it to the blockchain.

### Second scenario: ask someone to authorize your identity on its node

If you for some reason you do not want to add a node, just ask someone which has a node to accept the publication of your identity. Then, any certifier of your identity will find it on the hoster you asked to.

Of course, this method implies to spread people where to find your identity: because when you have your personal node, it spreads a peering information which contains your public key, so asking for certifications by giving your public key is enough to find it on the physical network.

It could be done on a website or any other support, since the certification is a human operation.

---------

Note that this procedure makes an identity be physically located on the network before being globally shared. This is an interesting point: identities emerge from localities, other individuals.

Also note of this is a breaking change, not in the protocol, but in the way clients like Sakia/uCoinApps/Cesium will publish and certify identities.

**Comment by Insoleet** [comment]
I can think of many limitations here : 

 - We will need to know the nodes where to find a given identity to be able to sign it. I think it will be totally not user friendly
  - Joining a network will start to be a real burden, with the difficulty to publish the identity + to get enough certifications when the certifications are slow to get

I would prefer if the user had to provide a proof of work to publish the identity on the network. It would burn CPU before being able to publish an identity and would be enough to discourage spam.

**Comment by c-geek** [comment]
The problem is: proof-of-work is not absolute trial, requiring 6 zeros might represent a week of work for someone like Moul which uses low consumption computers. So what is more complicated here? To make a one week costly identity, or simply install and run a software? Also, do you think someone who installed Bitcoin client, or Skype, or Word isn't able to install a node?

I don't see what is complicated here: you install and run your software, and you are done. What is difficult?

**Comment by Insoleet** [comment]
What is difficult is to find the identity on the correct node. You need an IP and a port for each new identity, to be able to certify it.

**Comment by c-geek** [comment]
Well it depends: the certifier will look for a public key, so it will check the peer entry with this pubkey and contact it directly. This supposes a node knows and accepts all the peer entries submitted to it however, which is not obvious I admit.

I have another suggestion then: let's say each node sets a size limit to its sandbox for identities. It will accept any new identity submitted until the maximum is reached.

On a regular basis, the identities with the least chances to be written gets pruned.

The "chances" criteria would imply:

* the number of certifications received yet
* the identity timestamp
* maybe some other criterias

So if an identity with a certification is submitted and the node sandbox is full and contains and identity with less chances than the incoming one, then the node could accept the incoming identity and make a pruning tour. So the sandbox size stays the same.

We could apply a similar algorithm for any document: a limited stock with a rotation using "least interest" algorithm for pruning.

**Comment by Insoleet** [comment]
Ok, I would add another rule : 
A published certification on an identity not present neither in the pool nor in the blockchain can instantiate a new identity in the blockchain.

This way, pools are no more the only way to find identities and sign them. If pools can spammed, we could still certify identities via other means (qr codes,..)

**Comment by c-geek** [comment]
> can instantiate a new identity in the blockchain

What? In the pool you mean? If yes, then we agree: this is what my example with certification meant.

**Comment by Insoleet** [comment]
Well I meant, the node does not need the identity document in the pool to add the identity in the blockchain. It can already find  via the certification. 

Also I agree : we need document prioritization on every document to have clear rules on nodes pool limits.

**Comment by c-geek** [comment]
Yes identity creation through certification is a must have, already implemented today. It would still be usable with pool limit.

So let's say we go on this solution? It would not be breaking change for clients.

**Comment by Insoleet** [comment]
:+1:
