### ISSUE TITLE
Nodes broadcast non-mainchain blocks through websockets

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#385]
That's why Sakia often displays nodes synced one time:

![image](https://cloud.githubusercontent.com/assets/969136/14556961/178ec6d0-02fb-11e6-93fd-e5d5e4cd35ae.png)

and unsynced few seconds later:

![image](https://cloud.githubusercontent.com/assets/969136/14556928/f2d709ec-02fa-11e6-8029-33c597a7a953.png)

**Comment by Insoleet** [comment]
Are you sure this is a bug ? I changed sakia behaviour in dev5 : https://github.com/ucoin-io/sakia/commit/1947aa3d9e62ca87f336ac8638bf305b33c02ec9

**Comment by c-geek** [comment]
Yes this is a bug, because I wanted uCoin to broadcast on websockets only blocks that were added on the main blockchain of the node. Today it also broadcasts fork blocks.

Note how this is different from the forwarding of the fork block to other nodes through HTTP POST, which is done today and OK.

**Comment by c-geek** [comment]
This bug no more exists because now Duniter only have 1 chain, no more fork blocks exist.
