### ISSUE TITLE
tx/history : received TX are missing (always empty)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#389]
When requesting TX history, ucoin does not return any received TX.

Example : 
 - G2C (uid=abc) has sent 150 super_currency to 5oc (kimaila), as we can see here : http://twiced.fr:9330/tx/history/G2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU
- but the tx/history of 5oc as an empty "sent" array : http://twiced.fr:9330/tx/history/5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of

**Comment by c-geek** [comment]
Duplicate of #410.
