### ISSUE TITLE
CPU is set to 100% by default

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#394]
That's probably not the best choice.
We could set as default 20 or 50%.

**Comment by c-geek** [comment]
It is a bug, I wouldn't have put it to 100%, I chose 60% as default.

I will investigate.

**Comment by M5oul** [comment]
I found that about CPU value and I draw two scenarios:

- The [Default value is set at 90%](https://github.com/duniter/duniter/blob/master/app/lib/entity/configuration.js#L18) and could be erased due to the graphical interface (May be linked to https://github.com/duniter/duniter/issues/398). Then [if this value is not assigned it goes to 100%](https://github.com/duniter/duniter/blob/master/app/lib/proof.js#L28).

- May be the [default value is set at 100%](https://github.com/duniter/duniter/blob/master/server.js#L74).
