### ISSUE TITLE
Generate again the peer document after a synchronization

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#397]
Because otherwise the node is not known by the network and don't get any new block forwarded..

**Comment by M5oul** [comment]
When I restart my node, it sync and do not share his peer document at the end of this process.
So, I can't see it in Sakia.
I need to restart the node to see it in Sakia.

**Comment by c-geek** [comment]
Note to me:

* add a `pulling` event to WebUI for issue #450 
* similarily, add a `self-peer` event telling our node has issued a new peer document

The `self-peer` event can be catched for Toast alert, indicating the event.
