### ISSUE TITLE
duniter command line: remoteIpv6 erased (if none) with ipv6 value

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#398]
from the command line tool 
> duniter wizard network-config

value of the 'ipv6' property is copied into remoteIpv6 (in the file ./config/duniter/duniter_default/conf.json), when i try to set 'remoteipv6' to 'None' value

I had the same issue on duniter-deskop

**Comment by M5oul** [comment]
I could reproduce it.

**Comment by M5oul** [comment]
Finally, I couldn't reproduce it from a42 to a43 :smile:

**Comment by M5oul** [comment]
I reproduce it when reset + sync.

**Comment by M5oul** [comment]
I am not sure it the same issue.
I migrate my issue to https://github.com/duniter/duniter/issues/434.

**Comment by c-geek** [comment]
Yes Moul this is probably 2 different issues.
