### ISSUE TITLE
Admin UI behind reverse proxy

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#401]
It's not working. I get :

>
error
The operation is insecure.

There isn't any urgency, thought :)

**Comment by M5oul** [comment]
Ah, this is what the issue I encounter for [YunoHost package](https://github.com/duniter/duniter_ynh/issues/12).

**Comment by M5oul** [comment]
I don't know if the [`node-http-proxy` module](https://github.com/nodejitsu/node-http-proxy) could be interesting.

**Comment by M5oul** [comment]
May be linked to this parts of the code:

- https://github.com/duniter/duniter/blob/master/app/controllers/webmin.controller.js#L56
- https://github.com/duniter/duniter-ui/blob/master/app/js/services/bma.js#L197-L201
- https://github.com/duniter/duniter-ui/blob/master/app/js/lib/conf/conf.js#L2-L3

I tried to modify this value.

**Comment by c-geek** [comment]
So, I checked with the Duniter node hosted at http://peer.duniter.org, and it works like a charm.

If you installed Duniter using the bash script, then you need [extra git+node operations](https://github.com/duniter/duniter/blob/master/doc/contribute-french.md#installer-linterface-graphique) to have the UI available.

Here is the Nginx configuration I used to have this UI available:

```
server { 
 
  listen 80; 
 
  server_name peer.duniter.org; 
 
  location ~ / { 
    proxy_set_header        X-Real-IP       $remote_addr; 
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header        Host            $http_host; 
    proxy_set_header        X-NgninX-Porxy  true; 
 
    proxy_pass http://localhost:9220;
    proxy_redirect          off; 
 
    # Socket.io support 
    proxy_http_version 1.1; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
 
  } 
} 
```

**Comment by M5oul** [comment]
I tried this nginx conf, I still have `The operation is insecure.`
![capture du 2016-08-07 23-24-13](https://cloud.githubusercontent.com/assets/4758871/17465397/3b3437fa-5cf6-11e6-8939-4c8621522bfb.png)

Did you tried with HTTP**S**?

**Comment by M5oul** [comment]
There must be an issue with socket connection with the Nginx proxy.

I tried to find a good nginx conf to handle `socket.io`, I didn't found something great:
- https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/
- https://stackoverflow.com/questions/29043879/socket-io-with-nginx
- https://gist.github.com/atma/6262642
- https://chrislea.com/2013/02/23/proxying-websockets-with-nginx/

**Comment by M5oul** [comment]
@Insoleet, does it works for you?
It's may be an issue with YunoHost SSO: [SSOwat](https://github.com/YunoHost/SSowat).

**Comment by Insoleet** [comment]
I didn't have time to try against it, and I won't have for a while, sorry :( sakia refactoring is consuming all my free time.

**Comment by c-geek** [comment]
I will check it tonight or tommorrow.

**Comment by c-geek** [comment]
I've fixed most the HTTPS problems but still, we have a last one issue which is: the UI *tries* to contact the node using its public interface, yet this interface is to be contacted using HTTP (default Duniter protocol) and the browser refuses to serve an HTTP request while we are using HTTPS protocol.

So we have a message like this:

![image](https://cloud.githubusercontent.com/assets/969136/17514837/2fac2fb0-5e35-11e6-83ae-1a14b73ac3a0.png)

But I plan to make a special check to display a different message if we are using HTTPS. See #514.

**Comment by M5oul** [comment]
Thanks that's awesome!
