### ISSUE TITLE
[install script] refresh terminal idea

### ISSUE THREAD

**Issue by Jimskapt** [duniter/duniter#403]
Hi, why the install script asks to close and (re)open the terminal ?
Can't we using something like following ?

``` bash
source ~/.bashrc
```
(if using bash) It worked, for me :)

[https://github.com/duniter/duniter/blob/a84743535a77e70f186aac12dd5b9eda43aa5afa/install.sh#L194-L198](
https://github.com/duniter/duniter/blob/a84743535a77e70f186aac12dd5b9eda43aa5afa/install.sh#L194-L198)

**Comment by M5oul** [comment]
It's [not possible to do it from the `install.sh` script](https://askubuntu.com/questions/64387/can-not-successfully-source-bashrc-from-a-shell-script).
Script will ask to run this command.

**Comment by Jimskapt** [comment]
Oh, well seen !
See you, M5oul !
