### ISSUE TITLE
NaClb build fail with root user

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter#412]
L'installation se passe sur un vps chez OVH
OS : Debian 8 (Jessie) (64 bits)

```
npm WARN ucoin@0.20.0-a57 license should be a valid SPDX license expression
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/root/.duniter/node/bin/node" "/root/.duniter/node/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! naclb@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the naclb@1.3.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the naclb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs naclb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls naclb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.duniter/npm-debug.log
```

La copie complète :
https://framabin.org/?d1b74f61aad0a578#Kr2KjfiqWPrYFqe0BKhEk7BvUYsKtTe9TmXJ2wDYgzw=

**Comment by M5oul** [comment]
J’ai déjà eu ce problème.

**Comment by c-geek** [comment]
Oui c'est l'installation en mode root qui ne fonctionne pas. C'était pareil sur ARMv4, c'est pour ça que j'ai fait des .deb pour permettre l'installation root.

@vincentux je te conseille de faire l'installation avec un utilisateur local, puis de déplacer le dossier où tu souhaites ensuite.

**Comment by vincentux** [comment]
Installation via un utilisateur : (_Et idem avec sudo devant :/_)
```
curl -kL https://raw.githubusercontent.com/duniter/duniter/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5966  100  5966    0     0  40351      0 --:--:-- --:--:-- --:--:-- 40585
=> Downloading duniter from git to '/root/.duniter'
=> mkdir: impossible de créer le répertoire « /root »: Permission non accordée
fatal: impossible de créer le répertoire de la copie de travail '/root/.duniter'.: Permission non accordée
bash: ligne 53 : cd: /root/.duniter: Permission non accordée
bash: ligne 54 : cd: /root/.duniter: Permission non accordée
=> Downloading 'http://nodejs.org/dist/v5.9.1/node-v5.9.1-linux-x64.tar.gz' to '/root/.duniter/node.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /root/.duniter/node.tar.gz: Permission non 
Warning: accordée
curl: (23) Failed writing body (0 != 3600)
Failed to download 'http://nodejs.org/dist/v5.9.1/node-v5.9.1-linux-x64.tar.gz'

=> Source string already in /home/vincentux/.bashrc
===> !Run the command 'source /home/vincentux/.bashrc' to start using duniter! <===
```

**Comment by c-geek** [comment]
Je veux dire : il faut utiliser un compte non-root et aller dans le home non root ! Par exemple : 

    cgeek@~$ curl -kL https://raw.githubusercontent.com/duniter/duniter/master/install.sh | bash

Là ça devrait passer.

**Comment by vincentux** [comment]
Oui je suis sur compte non-root : 
`vincentux@vps238114:~$ curl -kL https://raw.githubusercontent.com/duniter/duniter/master/install.sh | bash`

**Comment by c-geek** [comment]
Tu es dans le dossier /root, c'est certain :

    bash: ligne 53 : cd: /root/.duniter: Permission non accordée
    bash: ligne 54 : cd: /root/.duniter: Permission non accordée

**Comment by c-geek** [comment]
Ou a minima la commande est lancée avec sudo.

**Comment by vincentux** [comment]
Avec ou sans "sudo" même erreur ...
```
vincentux@vps238114:~$ pwd
/home/vincentux
vincentux@vps238114:~$ id
uid=1001(vincentux) gid=1000(vincentux) groupes=1000(vincentux),27(sudo)
```

**Comment by c-geek** [comment]
En fait, c'est : 

* soit la valeur de `$HOME` qui renvoie `/root`
* soit la valeur de `$DUNITER_DIR` qui renvoie `/root/.duniter`

Dans le 2ème cas, tu as peut-être une ligne qui a été ajoutée dans un `.bashrc` ou fichier similaire, du fait d'un précédent sudo je pense.

**Comment by vincentux** [comment]
Arg, effectivement j'avais toujours des lignes dans .bashrc
J'ai relancé le tout avec mon user et c'est ok ;)
Merci.

**Comment by c-geek** [comment]
Désolé je n'y ai pas pensé avant !

Je laisse le ticket ouvert car c'est un vrai problème cette histoire d'installation en root...

**Comment by c-geek** [comment]
There is absolutely no link with 5cefec3 ... the issue has been migrated here: https://git.duniter.org/nodes/typescript/duniter/issues/412
