### ISSUE TITLE
wot/lookup > Error : "Cannot read property 'uid' of undefined"

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#429]
This lookup :

http://cgeek.fr:9330/wot/lookup/HGYV5C16mrdvE9vpb1S9nMDHkVPsubBgANs9pSb6HWCV

return an error:

```
{
  "ucode": 1002,
  "message": "Cannot read property 'uid' of undefined"
}
```

May only for non-member ?
-> This one is KO : 9F3i2se7ujheZasMwoneoA49HikQsXv51McrhhbZmJoe
-> This one works : 5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of

**Comment by blavenie** [comment]
Bizarre, sur mon noeud ca fonctionne...
http://test-net.duniter.fr:9201/wot/lookup/HGYV5C16mrdvE9vpb1S9nMDHkVPsubBgANs9pSb6HWCV

Je suis aussi en version 0.20.0.a58, comme ton noeud

**Comment by c-geek** [comment]
Oui c'est un problème de données, donc ça ne se reproduit pas partout.

J'ai fait un dump, je vais me resynchroniser pour éviter de faire planter les clients. Je pense que c'est ça qui crée un bug quand on cherche "Ga" dans la communauté.

**Comment by c-geek** [comment]
Je confirme, réinitialiser le nœud règle le soucis.
