### ISSUE TITLE
Erased network conf with autoconf when restarting the desktop version after removed database

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#434]
After removing manually `~/.config/duniter_default/duniter/{duniter.db, stats.json, wotb.bin, indicators}` except `conf.json` and `duniter.log`.
When I restart with `./nw`, I am connected to the welcome page.
I sync and my network configuration went from:
```fish
 "port": 31550,
 "ipv4": "192.168.1.21",
 "ipv6": "2a01:e34:ee36:b2d0:82fa:5bff:fe28:389f",
 "upnp": false,
 "remotehost": "moul.re",
 "remoteipv4": "78.227.107.45",
 "remoteipv6": "2a01:e34:ee36:b2d0:82fa:5bff:fe28:389f",
 "remoteport": 31550,
```
to:
```fish
 "port": 31550,
 "ipv4": "127.0.0.1",
 "ipv6": "::1",
 "upnp": true,
 "remotehost": "moul.re",
 "remoteipv4": "78.227.107.45",
 "remoteipv6": "::1",
 "remoteport": 31550,
```
I could see my network conf erased with autoconf.
My key and my CPU conf stay the same.

It must be graphical interface which launch autoconf of the network.

May be linked issue https://github.com/duniter/duniter/issues/398.

**Comment by c-geek** [comment]
Just caught the faulty code!
