### ISSUE TITLE
Use a credentials file to avoid security problems in the command line

### ISSUE THREAD

**Issue by vtexier** [duniter/duniter#435]
A good practice, when you have to give passwords or sensible informations to a command in the command line is to use a text file.

Create a `credentials.txt` file in a secure place with proper permissions and put credentials in it, example : 

> mysalt
> mypassword

Add an option --credentials=/path/to/the/credentials/file.txt in the command parameters.

No more passwords in install scripts, shell history, etc...

Another solution is to have a full config file with all config parameters, and give the config file path as an option in the command.

**Comment by M5oul** [comment]
Linked to https://github.com/duniter/duniter/issues/233.

**Comment by c-geek** [comment]
Possible with duniter@1.2.3: `--keyfile` option. See [the docs](https://duniter.org/fr/wiki/duniter/commandes#option-keyfile).
