### ISSUE TITLE
Working with a `dev` branch

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#436]
Instead of directly working on master.

What to change:

* create a `dev` branch
* update the `release.sh` script so:
  * it merges all the work on master after the version commit
  * it also bumps automatically the current install version in `install.sh`

**Comment by c-geek** [comment]
cc @Insoleet when you will want to merge `organization` branch, you should do it in `dev` branch.

I will stop committing in `master` branch also.

**Comment by Insoleet** [comment]
Ok great ! I will probably merge organization before refactoring waterfall code. And do the waterfall code refactoring in another branch (named 'coroutines' ?)

**Comment by c-geek** [comment]
As you wish, why not to continue on organization branch?

**Comment by Insoleet** [comment]
As you want, I just like explicit branch names :)

I merged for your information !

**Comment by c-geek** [comment]
Fixed with 70d85ecd28310a3318ca981eefb6e32b22d04f0a.
