### ISSUE TITLE
Avoid DDOS attacks

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#438]
Recently we had an issue with nodes being spammed (duniter/sakia#424), acting like a DDOS attack (a peaceful one).

It is time to think about mechanisms to avoid this kind of events.

**Comment by M5oul** [comment]
Yep, I get sometime up to 300 Kio/s upload from my node.

**Comment by c-geek** [comment]
Yes, I was thinking about limits by IP like:

* max X1 requests / second
* max X2 requests / 10 seconds
* max X3 requests / 30 seconds
* ...
* max Xn requests / day
