### ISSUE TITLE
Change account password

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#440]
Could it be possible to change the account password?
Or, it is hard coded in the public key?

**Comment by c-geek** [comment]
It is hardcoded. However, you could store the private/public key and put a password on it, which would be by construction *editable*.

**Comment by M5oul** [comment]
Ok.
That could be a great feature.

**Comment by c-geek** [comment]
You could see for example duniter/sakia#223.

**Comment by Insoleet** [comment]
We could also imagine a document meaning "My identity didn't change but here is my new pubkey", signed by both old private key and new private key.

**Comment by c-geek** [comment]
Hmmm ... I like the idea. :+1:

**Comment by Insoleet** [comment]
Par contre ça demande de trouver un mécanisme permettant de bloquer la prise de contrôle de son identité par un vol de clé privée. 
Par exemple, le document de révocation pourrait encore être valide quelques temps après le changement de clé pour détruire l'identité si on se rend compte du vol ?

**Comment by c-geek** [comment]
There is absolutely no link with 2533b21 ... the issue has been migrated here: https://git.duniter.org/nodes/typescript/duniter/issues/440
