### ISSUE TITLE
encounter a node.js missing error after deb package installation (v0.20.0a59)

### ISSUE THREAD

**Issue by canercandan** [duniter/duniter#444]
I have successfully installed the new version of the DEB package v0.20.0a59 on my Ubuntu 15.04.

But when I launched the command line `duniter --help` I got this error:

```
Node.js is not embedded in this version of Duniter
```

I found a way to go around this error by creating the variable `DEV_MODE` and changing the directory to `/opt/duniter/sources`:

```
$ export DEV_MODE=1
$ cd /opt/duniter/sources
$ duniter --help
```

PS: you made an amazing work so far, long and successful life to Duniter ;-)

**Comment by c-geek** [comment]
If you are on a desktop, prefer `duniter-desktop` command which will launch the UI.

**Comment by c-geek** [comment]
Hmmm even `duniter-desktop` should miserably crash. I will make an alpha60 release this evening.

**Comment by c-geek** [comment]
`duniter` command still procudes the "Node.js ..." error.

**Comment by c-geek** [comment]
I will make another version tomorrow evening.
