### ISSUE TITLE
Export from command line interface

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter#453]
Pour ceux qui non pas accès à l'interface web de duniter, il serait bien de pouvoir faire les exports de compte via le terminal.

**Comment by c-geek** [comment]
De mémoire, je crois que tu parlais de l'export CSV. Je le note ici pour ne pas oublier :smile:

**Comment by c-geek** [comment]
Après réflexion, je ne vais pas développer cette fonctionnalité en CLI car c'est vraiment spécifique à l'interface graphique. A la limite ça devrait même être sorti du cœur pour être mis dans un module d'administration, à part.

Donc vu ce n'est pas un truc important à court terme, et que plein de personnes seront capables de le faire par d'autres moyens plus tard, je préfère clore cette issue.
