### ISSUE TITLE
Wrong symlink and wrong path at ARM debian package creation

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#454]
On my ARM board, after removing and reinstalling with `dpkg`:
```fish
which duniter
/usr/bin/duniter
```

The [symlink is not pointing to the good place as in issue #420](https://github.com/duniter/duniter/issues/420):
```fish
ls -al /usr/bin/duniter*
lrwxrwxrwx 1 root root 31 May 25 12:36 /usr/bin/duniter -> /opt/duniter/sources/bin/ucoind
```
```fish
duniter --version
0.20.0a66
```

I did a good symlink, but when running `duniter`, [I get issue #444 ](https://github.com/duniter/duniter/issues/444):
```fish
Node.js is not embedded in this version of Duniter
````

**Comment by M5oul** [comment]
The issue is that duniter sources and node are in seperated folders.
https://github.com/duniter/duniter/blob/master/duniter.sh#L12

Can't works [here](https://github.com/duniter/duniter/blob/master/duniter.sh#L23-L24):
`/opt/duniter/sources/node` does not exist but `/opt/duniter/node` exist.

But when, I change this line, `/opt/duniter/bin/daemon` can't be find.
Because it's in `opt/duniter/sources/bin/daemon`.

Finally, I made it works with this [hack](https://github.com/duniter/duniter/pull/456/files).

But, I think it break other way of distributions.

I think, the [the path where were copy node was wrong at ARM deb package creation](https://github.com/duniter/duniter/pull/457/files).

**Comment by M5oul** [comment]
Fixed with https://github.com/duniter/duniter/commit/b0f9062cb247cff160350e956b4190e7cd04495b.

**Comment by M5oul** [comment]
So, tested with alpha 67,

The symlink is the same and I don't know why from the code. Do you use the current code to built ARM debian package?

The `DEB_PACKAGING=` isn't at true `true` because there is [no graphical interface](https://github.com/duniter/duniter/commit/308f61db42114be561b85d0afe8ce91a95dc37b1).

**Comment by c-geek** [comment]
Could you try again with [release alpaha77](https://github.com/duniter/duniter/releases/tag/v0.20.0a77)?

**Comment by M5oul** [comment]
Well, it's a bit better now.
The symlink is good.
But [`DEB_PACKAGING` variable](https://github.com/duniter/duniter/blob/master/duniter.sh#L9) in [duniter.sh](https://github.com/duniter/duniter/blob/master/duniter.sh#L9) is not at `true`.
I manually tried the [sed](https://github.com/duniter/duniter/blob/8ee12e86aa46c29f9394c7116e2d08bdfcf4326c/ci/travis/debian/DEBIAN/postinst#L24) which put it at `true`.

`node` repository is not in `/opt/duniter` nor in `/opt/duniter/sources`.

**Comment by c-geek** [comment]
OK I've made [this fix](https://github.com/duniter/duniter/commit/dba8cb16dbb19f3b3d813a8a1957eea9912fb581#diff-1c0c28400d8e213171f27dd0a0280d31R23) ([also row 25](https://github.com/duniter/duniter/commit/dba8cb16dbb19f3b3d813a8a1957eea9912fb581#diff-1c0c28400d8e213171f27dd0a0280d31R25)). Could you try the [release alpha78](https://github.com/duniter/duniter/releases/tag/v0.20.0a78)?

**Comment by M5oul** [comment]
I still can't find `node` repository.

**Comment by c-geek** [comment]
Indeed.

**Comment by c-geek** [comment]
Aaaaand now you can try [release alpha80](https://github.com/duniter/duniter/releases/tag/v0.20.0a80).

**Comment by M5oul** [comment]
Ok, everything is fixed.
But, I get an issue related to https://github.com/duniter/duniter/issues/381:
```fish
module.js:341
    throw err;
    ^

Error: Cannot find module '/opt/duniter/sources/node_modules/sqlite3/lib/binding/node-v47-linux-arm/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/duniter/sources/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
With Node.js 5.8 and 5.11.

**Comment by M5oul** [comment]
When I build it manually, I get:
```fish
> sqlite3@3.1.4 install /root/duniter/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@6.2.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
```
There is no pre-built sqlite@3.1.4 and node@6.2.0.
I suceed to build sqlite@3.1.4 \o/

**Comment by M5oul** [comment]
Ok, it's fixed :smile_cat:
