### ISSUE TITLE
Current block late for certain nodes

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#461]
I can see that Galuel and Inso nodes have frequently they current block one or two blocks late than the pool of other nodes.

![capture du 2016-05-29 17-43-08](https://cloud.githubusercontent.com/assets/4758871/15634472/d84cb13e-25c4-11e6-9167-5a0d966c05ef.png)

That's may be why Inso node get sometime corrupted.

That's an issue because, this is an open door to blockchain forks and their are generating already generated blocks for nothing.

Where could come that problem? When nodes have a new block, they spread it to all nodes they know.
May be this two nodes don't receive new blocks. They get new blocks only when they search by themselves.
It could come from their network configuration which don't allow entering connections.

I tried to forward them blocks and they get same current block than the pool of nodes.

**Comment by M5oul** [comment]
May be https://github.com/duniter/duniter/issues/476 could solve it.

**Comment by M5oul** [comment]
- It's may be due to network latency.
Close nodes are get directly last block.
- Or, it's could be due to peer sheet wrongly spread at re-sync process.

**Comment by M5oul** [comment]
It's seems to be better nowadays.
May be with https://github.com/duniter/duniter/commit/b00ef4b9ce5cbc69397bd24f00c7b6aecf4a4236.

**Comment by c-geek** [comment]
Yes it is better for @Insoleet because of a new configuration of Nginx reverse proxy for WebSockets.

By the way, I should add this configuration example in #615.
