### ISSUE TITLE
Use git subtree instead of git submodule on dependencies

### ISSUE THREAD

**Issue by vtexier** [duniter/duniter#466]
Git submodules are deprecated in favor of subtrees to handle sub-repositories.
- [French subtree tutorial](http://www.git-attitude.fr/2015/01/30/git-subtrees)
- [English more in-depth explanation of subtree](http://www.mos6581.org/git_subtree_alternative)

**Comment by M5oul** [comment]
- [French submodules tutorial](http://www.git-attitude.fr/2014/12/31/git-submodules)

**Comment by M5oul** [comment]
Finally, I found that subtree is a very great tool.
I understand it with [two first videos on YouTube](https://www.youtube.com/results?search_query=git+subtree).

I made it works without too much difficulty on my other project.
I do it for Duniter and explain it.

**Comment by M5oul** [comment]
Ok, it's done on [substree branch](https://github.com/duniter/duniter/tree/subtree).

I let you play with it, if it's ok for you.

**Comment by c-geek** [comment]
I will have a look, thanks!

**Comment by M5oul** [comment]
For instance, on my project, I did [a modification on the main git repo](https://moul.re/repo/42/21sh/commit/4df0f1b9f612874849f30aeb15c5e51d1a8a4b6d) and [on the subtree](https://moul.re/repo/42/libft/commit/30e906145900ef7eb52b68b2c3d670a3e5e873a4).
I commited for both repos with one command.
I pushed which pushed for main repo.
And for subtree, I pushed with:
```bash
git subtree push --prefix=tree tree master
```
That's it.

And first clone only needs `git pull`, which also retrieve the subtree \o/

**Comment by c-geek** [comment]
French tutorial (same author as your link, Moul): http://www.git-attitude.fr/2015/01/30/git-subtrees/

**Comment by c-geek** [comment]
I've to think a bit more about this, I delay it to another milestone.

**Comment by c-geek** [comment]
Finally, we will externalize non-core code as a module. This does not require git to be implemented.

Fixed by #738
