### ISSUE TITLE
Node not accessible from localhost

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#481]
Node is not accessible from localhost

``` fish
curl localhost:8999
```

We could have something like [that](https://github.com/afaqurk/linux-dash/blob/master/server/index.js#L9) in this [file](https://github.com/duniter/duniter/blob/master/server.js).

**Comment by c-geek** [comment]
Your node is available at `--ipv4` or `--ipv6 value`, and port `--port`. Why would you need `localhost`?

**Comment by M5oul** [comment]
Many apps have that possibility to access from `localhost` endpoint.
For YunoHost packages (Cesium and duniter-ui), it's more easy to do a `reverse_proxy` from `localhost` to [avoid STS issue](https://github.com/duniter/duniter_ynh/issues/12) (node API accessible without HTTPS, duniter web interface accessible with HTTPS).

**Comment by M5oul** [comment]
[Done on YunoHost package](https://github.com/YunoHost-Apps/duniter_ynh/blob/master/scripts/install#L61).
`ipv4` parameter need to be set to `localhost`.
