### ISSUE TITLE
Erreur certifiers-of and certified-by don't find identity "1pact"

### ISSUE THREAD

**Issue by naivalf27** [duniter/duniter#484]
L'identité `1pact` (94T2H35EiFuPxTtGhjospYJzsUiGsYBYAT1h9CoEFG1G) se retrouve dans le requirement et dans le lookup, mais une erreur est retournée dans `certifiers-of` et `certified-by`.

**Comment by c-geek** [comment]
Quel genre d'erreur ? Personnellement je rencontre l'erreur ci-dessous : 

```json
{
ucode: 2004,
message: "No member matching this pubkey or uid"
}
```

Ce qui est tout à fait normal étant donné que l'identité n'est pas membre (les URIs `/certifiers-of` et `certified-by` ne renvoient des informations que pour les membres).

Tu peux rouvrir cette issue si tu as eu une autre erreur que celle ci-dessus.
