### ISSUE TITLE
Node changed many times branch during a big fork

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#486]
I saw Inso node changing of branch between two forks.
From it's initial branch it goes to the other one then came back to it's original branch.

**Comment by M5oul** [comment]
Surely linked to https://github.com/duniter/duniter/issues/385.

**Comment by c-geek** [comment]
Have you seen such behavior again? It is hard to reproduce.

**Comment by c-geek** [comment]
I close it, please reopen if it happens again.
