### ISSUE TITLE
Have a different personal difficulty rule

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#492]
Today the rule is the following:

    PERSONAL_DIFF = MAX [ PoWMin ; PoWMin * FLOOR (percentRot * (1 + nbPreviousIssuers )/ (1 + nbBlocksSince)) ]

Which leads to difficulty curves like this:

[![image](https://cloud.githubusercontent.com/assets/969136/16496745/d1fa2d32-3ef3-11e6-9579-ee0eaaaf7f92.png)](https://forum.duniter.org/t/common-and-personnal-proof-of-work-difficulties/924/9)

Maybe we could have smoother curves, or be able to have only 1/3 of the members with the common difficulty instead of 2/3 like we can see in this graph (for percentRot = 0,9).

**Comment by c-geek** [comment]
The easiest solution seems to use `percentRot = 1`.

For the smoothness, we could simply remove the `FLOOR` function or put it earlier in the function like:

    PERSONAL_DIFF = MAX [ PoWMin ; FLOOR(PoWMin * percentRot * nbPreviousIssuers / (1 + nbBlocksSince)) ]

But I actually like the function as of today `PoWMin * FLOOR (percentRot * nbPreviousIssuers / (1 + nbBlocksSince))` since it keeps away attackers as long as it has not precisely `PoWMin` difficulty.

I will not change anything in the code, but let's target `percentRot = 1` for production currency.

**Comment by c-geek** [comment]
I reopen this issue, we could smoothen the difficulty curve so it becomes more linear with a `powMin + 2`, `powMin + 1` difficulties some anyone can start computing, without having to wait for `powMin` difficulty.

**Comment by M5oul** [comment]
New issuers could have a higher personal difficulty like they come to compute a new block.
With that, we could avoid spam from new comers and reduce common difficulty :smile_cat:

**Comment by c-geek** [comment]
Nope, I think we say two different things. You speak about having a difficulty higher than `PowMin` for users who don't have computed a block for a long time, or even never issued one. This, to avoid a potential spam from new issuers because they can "speak immediately", since they are not part of the "pow excluded" members.

But on my side, I was speaking about the "pow excluded" members, precisely. I was thinking about making the curve smoother, so it doesn't make the stairs we currently have for 1/3 of the members, but rather a curve which quietly goes from the hardest levels to the `powMin` one. I would have prefered, instead of this:

![image](https://cloud.githubusercontent.com/assets/969136/18844438/887b51b2-841d-11e6-8e86-8ca06d975ce5.png)

Something like this:

![image](https://cloud.githubusercontent.com/assets/969136/18844407/70bb8268-841d-11e6-8856-4138eeb9f85a.png)

But if we look at the equivalent « real » hardness in termes of computing difficulty, here is what we have with our new rule:

![image](https://cloud.githubusercontent.com/assets/969136/18844535/e3f4229e-841d-11e6-97cb-8506fffb3516.png)

In fact it is quite similar to what we have today. So ... maybe we just really *don't need* to change the difficulty rule. I don't know, now.

**Comment by c-geek** [comment]
Take into account what was said by @ktorn on https://forum.duniter.org/t/block-issuance-distribution/1312

**Comment by c-geek** [comment]
Do not forget to modify the /blockchain/difficulties call to simulate for `Version: 4` difficulty.
