### ISSUE TITLE
TX: allow outputBase to be higher than max(inputBase), when possible

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#493]
Pourquoi ne pas autoriser des TX avec des inputs en base 0, vers des outputs en base 1, si cela tombe juste ?
Ca permet de supprimer au fur et à mesure les bases inféieur, sans avoir besoin forcément de source en base 1

En fait comme Cesium ( @Insoleet et peut etre Sakia ?) fait  des transferts "rond" (avec zéro final) dès que la BlockChain a permutée de base, on aura très vite avoir uniquement des sources compatibles avec la base supérieure.

**Comment by blavenie** [comment]
réponse de @c-geek (chat) : oui dès que la nouvelle base sort, le moindre transfert peut alors transformer les sources ... c'est très bien, j'aurais pu y penser, faut le faire

**Comment by mmpio** [comment]
En considérant que l'on puisse avoir deux fois la meme clé publique dans les outputs #485 , je propose qu'il soit possible, voire forcé, de convertir meme si le montant n'est pas juste en scindant la source vers des output en base N et base N-1 mais en n'autorisant en base N-1 que de montant inférieurs à 10

Par exemple, je possède 449736 unités en base N-1 dont je souhaite envoyer la totalité. 
Je pourrais ou devrais avoir comme output
44973 en base N
6 en base N-1.

Ainsi nous n'aurons en base N-1 que des petits montants qui pourront facilement etre combiné puis convertis et il n'y aurais plus de condition bloquante pour l'envoi de monnaie.

**Comment by c-geek** [comment]
@mmpio ok, mais il faut généraliser en base N-x, car le montant envoyé peut être en base N-2 par exemple.

Mais je trouve l'idée bonne. Je rajouterai à cette fin un nouveau champ `CurrentBase` dans les transactions, afin que celle-ci soit explicite et permette une vérification locale de cette règle.

J'ajouterai également 1 champ temporel `BlockchainTime` qui serait un BUID (Block Unique ID) pour des contraintes d'intégrité (CurrentBase doit être démontré par un BlockchainTime compatible) et ajouter une notion de temps qui fait cruellement défaut aujourd'hui.

**Comment by Insoleet** [comment]
> Mais je trouve l'idée bonne. Je rajouterai à cette fin un nouveau champ CurrentBase dans les transactions, afin que celle-ci soit explicite et permette une vérification locale de cette règle.
J'ajouterai également 1 champ temporel BlockchainTime qui serait un BUID (Block Unique ID) pour des contraintes d'intégrité (CurrentBase doit être démontré par un BlockchainTime compatible) et ajouter une notion de temps qui fait cruellement défaut aujourd'hui.

Ok, par contre ça signifie qu'au bloc 100K, on peut envoyer des transactions avec un currentbase 0 en référençant un des premiers blocks dans le BUID ?

Ou alors un paramètre sur l'age maximum des transactions intégrées va bloquer ça ?

Aussi, pour vérifier ma compréhension : 
- On doit toujours envoyer des transactions de base courante
- Mais les petits montants ne sont pas perdus et peuvent être convertis sur le moyen-long terme

Charge aux clients de rendre ça transparent pour l'utilisateur...

**Comment by c-geek** [comment]
@Insoleet Oui j'ai oublié de le mentionner, mais du coup cela va permettre d'ajouter un âge maximum pour une transaction. Par exemple 1 mois me semble convenable, cela permet de faire des transactions crosschain assez librement, puisqu'elles sont censées avoir un rollback sur 72h voire un peu plus.

> * On doit toujours envoyer des transactions de base courante

Exactement. Sauf bien sûr si le montant ne peut pas être exprimé dans cette base, par exemple si le montant est trop petit (c'est le cas d'un reste d'une transaction précédente, justement).

> * Mais les petits montants ne sont pas perdus et peuvent être convertis sur le moyen-long terme

Oui.

> Quand on est en base 2, est-ce que le reste est forcément en base 0 ? Ou est-ce qu'il peut être en base 1 ?

Je ne me suis pas encore décidé  là-dessus, mais *a priori* la base devra être la plus grande possible.

**Comment by mmpio** [comment]
> Quand on est en base 2, est-ce que le reste est forcément en base 0 ? Ou est-ce qu'il peut être en base 1 ?  

L'idée est que si un montant est exprimé dans une base inférieure à la base courante, il ne peut être supérieur à 9 sinon c'est qu'il est convertible dans une base superieure.

Avec une base courante de 2 :
54321(0) - > 543(2) + ~~21(0)~~
54321(0) -> 543(2) + 2(1) + 1(0)

**Comment by c-geek** [comment]
J'ai de nouveau réfléchi au problème, et pour des raisons de souplesse je propose la solution suivante : 

## Blockstamp

Toute transaction aura désormais un champ que je nomme `Blockstamp`, qui comme son nom l'indique est un timestamp mais de type "bloc". C'est simplement un BUID comme dans tout autre document et qui permet d'avoir une date fiable dans le passé. Ceci servirait à limiter les transactions à être 1 mois en dehors de la blockchain avant d'expirer.

## Montants

Je supprimerai la règle trop contraignante actuelle : 

> * Each `OutputBase` must be equal to the maximum `InputBase` available.

Et je la remplacerai par les suivantes : 

### Règle 1

> Def.: `MaxInputBase` is the maximum value of all `InputBase`
> Def.: `InputBaseSum` is the sum of amounts with the same `InputBase`.
> Def.: `OutputBaseSum` is the sum of amounts with the same `OutputBase`.
> Rule: For each `InputBaseSum` **except** `MaxInputBase`, it cannot exists `OutputBaseSum > InputBaseSum`.
>
> Example:
>
> INPUTS: 15(1) + 30(1) + 20(2)
> VALID OUTPUT: 45(1) + 20(2)
> VALID OUTPUT: 15(1) + 23(2)
> VALID OUTPUT: 25(1) + 22(2)
> INVALID OUTPUT: 55(1) + 19(2)

### Règle 3

> Def.: `MaxOutputBase` is the maximum value of all `OutputBase`
> Rule: `MaxOutputBase` cannot be higher than current block `UnitBase`

## Commentaire

En fait, cela signifie qu'il n'y a qu'un seul sens de transformation pour les unités : d'une plus basse vers une plus élevée, tout en ayant une limite haute à la base courante en blockchain.

Ce qui fait que les clients peuvent bien réaliser les montants qu'ils souhaitent, mais jamais ils ne pourront diviser des unités hautes vers des unités plus basses. C'est très très souple pour réaliser toute transaction, avec un comportement identiques avec les pièces métalliques actuelles.

Dites moi ce que vous en pensez, mais *a priori* ce comportement me convient tout à fait.

**Comment by c-geek** [comment]
J'ai un contre-exemple pour la règle proposée ci-dessus : 

> INTPUT 7(1) + 7(1) + 1(2) + 5(3)
> VALID OUTPUT 4(1) + 2(2) + (3)

Or, la règle indique que `2(2) <= 1(2)`, ce qui est manifestement faux.

## Nouvelle proposition

En fait, tout ce que l'on souhaite est avoir une transformation uniquement dans le sens base inférieure => supérieure. On peut donc supprimer la règle : 

> <s>Rule: For each InputBaseSum except MaxInputBase, it cannot exists OutputBaseSum > InputBaseSum.</s>

Et remplacer par une règle plus générale : 

> Def.: `BaseDelta = OutputBaseSum - InputBaseSum`, expressed in `CommonBase`
> For each `OutputBase`:
>   * if `BaseDelta > 0`, then it must equal the sum of all preceding `BaseDelta`
>   * if `BaseDelta < 0`, then it must equal the sum of all preceding `BaseDelta`

Ce qui dit simplement que, pour toute base de sortie, la somme des montants en cette base ne peut provenir que de la base même et des montants des bases précédentes.

Je vais partir là-dessus.

**Comment by Insoleet** [comment]
Je ne comprends pas bien cette règle: `BaseDelta`, `OutputBaseSum` et `InputBaseSum` sont des montants ou une base ?

**Comment by c-geek** [comment]
Il faut prendre le suffixe pour comprendre le type : *Delta* et *Sum* sont des montants.

L'idée est de dire qu'il peut y avoir un écart entre un montant en entrée et un montant en sortie pour une base donnée. Ex. : 

    I: 12(1) + 1(1) + 2(2)
    O: 3(1) + 3(2)

On peut calculer les deltas:

    Base1: 3(1) - 12(1) - 1(1) = 30(0) - 120(0) - 10(0) = -100(0)
    Base2: 3(2) - 2(2) = 300(0) - 200(0) = 100(0)

On a donc un déséquilibre en Base1, mais qui est compensé en Base2 : on a donc une transformation de base 1 vers 2, ce qui est acceptable. Si les montants avaient créés une transformation de base 2 vers 1 en revanche, cela n'aurait pas été acceptable et une telle transaction serait rejetée.

**Comment by Insoleet** [comment]
Ok. Il n'y a pas une erreur dans la règle que tu as écrite (copier/coller) ? 

> 

    Def.: BaseDelta = OutputBaseSum - InputBaseSum, expressed in CommonBase
    For each OutputBase:

        if BaseDelta > 0, then it must equal the sum of all preceding BaseDelta
        if BaseDelta < 0, then it must equal the sum of all preceding BaseDelta

**Comment by c-geek** [comment]
Si ! La 2ème règle devrait dire : 

    if BaseDelta < 0, then it must equal the sum of all **following** BaseDelta

Mais en réalité  cette règle n'est pas testée, car la combinaison de la précédente règle avec la règle de montant total en entrée = montant total en sortie implique déjà cette 2ème règle.
