### ISSUE TITLE
Make the salt not viewable

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#498]
As said in #460 : the salt is a kind of password field, it should not be displayed while typing it.

**Comment by M5oul** [comment]
This is during the configuration prompt wizard?

**Comment by c-geek** [comment]
You have this in:

* Create a new currency (wizard)
* Settings > Change Keyring

**Comment by M5oul** [comment]
> - Settings > Change Keyring

You mean in graphical interface?
The password is hidden when writing it.
