### ISSUE TITLE
Duniter 0.22.0 peers tab error

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#518]
Impossible to connect to "home/peers" tab, I obtain that screen capture : 
![duniter20peers](https://cloud.githubusercontent.com/assets/5245398/17550065/7cd66d46-5ef3-11e6-88c5-0c8681a07e2c.png)

**Comment by M5oul** [comment]
Do you have any logs about that error?

**Comment by galuel** [comment]
Voici la partie du fichier log générée pendant l'opération : [log.txt](https://github.com/duniter/duniter/files/410819/log.txt)

Je vais en profiter pour ouvrir une issue sur l'export des logs

**Comment by M5oul** [comment]
I could reproduce it on desktop package.
It's working well with YunoHost package.

**Comment by vincentux** [comment]
Même erreur chez moi, une copie d'écran pour compléter le rapport de bug ;)

![11-08-2016-22-02](https://cloud.githubusercontent.com/assets/11737560/17584440/cc187728-5fb6-11e6-8fe5-679181b65431.png)
