### ISSUE TITLE
Duniter 0.22.0 log file

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#519]
It should be nice to be export to export log file for debug and upload it on github, with a button. Perhaps some information in the log window : 

"to help debugging Duniter if you find an error, activate debug during operation, and export log file with the export log button. If Duniter crashes during operation, log  file can be found in /path/.../log.txt"

It will help many not-technical testers to upload log file without many efforts.

NB : I'm able to Ctrl C / Ctrl V part of the log file to put it in a txt file, but the right clic mouse doesn't open the usefull menu to make the same. I often use the right clic mouse to do that, so I suppose it is a standard way to make copy/paste for any program.

**Comment by c-geek** [comment]
I will add 2 buttons: 

* one which opens the log file with the default system editor
* one which automatically upload the last X lines from the log file to [hastebin](http://hastebin.com/about.md) and return a link to be copied by the user

**Comment by c-geek** [comment]
Finally it will just be a link to hastebin.com, because opening the text editor is only possible for Desktop version.
