### ISSUE TITLE
unknown version

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#520]
Using YunoHost package and Duniter 0.22:
![capture du 2016-08-10 12-56-46](https://cloud.githubusercontent.com/assets/4758871/17551388/020d38cc-5efa-11e6-9dfc-d5bbcb84c282.png)

**Comment by M5oul** [comment]
It do not happen on Desktop version.

**Comment by c-geek** [comment]
Sorry, I thought I still had the bug on 0.31b3, but I was on 0.30.16.
