### ISSUE TITLE
L'interface Duniter ne se lance pas

### ISSUE THREAD

**Issue by JeanFe** [duniter/duniter#526]
Je suis sur Ubuntu 16.4
J'ai dl duniter-v0.22.0-linux-x64.deb et double cliqué dessus pour l'installer. Puis je l'ai cherché mais aucune trace nulle part. J'ai tenté de le lancer par terminal:

$ duniter webstart
Starting duniter_default daemon...
duniter_default daemon started. PID: 12985

Mais l'interface graphique n'apparait pas.
Je ne le trouve pas dans les processus non plus. 
Je l'ai donc désinstallé.

**Comment by c-geek** [comment]
Tu peux tenter de lancer `duniter-desktop`, ça fonctionnera bien.

Pour une raison que j'ignore, les raccourcis ont du mal à apparaître sur Ubuntu.

**Comment by M5oul** [comment]
From @JeanFe:
>La version duniter 0.3 s'installe parfaitement, on peut cloturer l'issue. Merci.

**Comment by c-geek** [comment]
Je rouvre pour conserver une trace du problème de raccourci Ubuntu qui n'apparaît pas, c'est à corriger.

**Comment by c-geek** [comment]
Désormais connue sous le ticket #546.
