### ISSUE TITLE
Automatically retrieve Cesium and disable ES/market place

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#542]

**Comment by M5oul** [comment]
I think we should automatically retrieve latest available release as it's [annoying to manually update that version number](https://github.com/duniter/duniter-ui/blob/master/cesium.js#L6).
I [did it for YunoHost package of Cesium](https://github.com/duniter/cesium_ynh/blob/master/scripts/install#L25).
And, on [Duniter package](https://github.com/duniter/duniter_ynh/blob/master/scripts/functions.sh#L5-L6), where `version` is also retrieve.

Must be easily done in JS?

**Comment by c-geek** [comment]
Yes but I need @blavenie to make a release without `es` plugin enabled, maybe like:

* cesium-web-0.2.1.zip (the version we need withtout es plugin)
* cesium-gchange-web-0.2.1.zip (the version we have today)

Because otherwise, I need to handle the `config.js` file of Cesium which contains dynamic informations like the build number, version, etc.

**Comment by c-geek** [comment]
I keep it open, we will close it once we have an automatic version retrieval.

**Comment by M5oul** [comment]
Yep, you are right, https://github.com/duniter/cesium/issues/65 need to be fixed to disable market place and ES.
I don't think an other build need to be done without ES.
We, as packager, only need to provide that config file with what we want and what we don't.

**Comment by blavenie** [comment]
duniter/cesium#65 has been closed

**Comment by c-geek** [comment]
Fixed in duniter/duniter-ui@e78c0e31d301026712b899a74d08ddd664ed1492
