### ISSUE TITLE
Propose node to sync or currency at launch

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#545]
As new user may not know on which port sync is node.
They could be find to have proposition of actual addresses of nodes with the currency name.

As it's a P2P network, that node could be down, there could be many currencies…etc

**Comment by modulix** [comment]
A way is perhaps a dns entry like $(currency_name).duniter.org which can be used as "default" value. This pool could return the "best" peers for your IP (nearest from you). Issue is it will become a single point of entry and also a SPOF. So, in any cases i'm afraid that it should remain as an external and optional feature. Like create a global OpenLDAP by currency (easy to subscribe share and browse) of available nodes is also another possible project.

**Comment by c-geek** [comment]
We could give 2 options:

* a list of known public peers like what suggests modulix, in a combobox
* a manual input like today

This way the user can choose the option he prefers, he still have the control but is also suggested some default values.
