### ISSUE TITLE
Separate peers IP between private and public...

### ISSUE THREAD

**Issue by modulix** [duniter/duniter#560]
Hi,

About "--remoteh" value :
If someone use a "private" IP (10.0.0.0/8, 172.16.0.0/12 or 192.168.0.0/16) for his node, please do not forward on internet, only to "local" peers. In this case, local are sent to locals and only public are sent on internet. Another way should be to create a flag to switch between public/private addresses.
Goal is avoid to spent time to try to reach something which will never respond...

**Comment by M5oul** [comment]
In fact, that makes too much useless requests.
A solution could be to not share private IPs addresses (even IPv6 ones `fe80::`).
That's not a huge problem to not share local addresses with local nodes because there is so much other node which could be reached.

**Comment by modulix** [comment]
so --remoteh may be a public IP, private not allowed and it's done ?

**Comment by M5oul** [comment]
`--remoteh` must be a public IP address.

But the issue, is that, with automatic configuration, local IP addresses could appear in the configuration.

**Comment by modulix** [comment]
I agree, but seems we need to add some code, just before recording --remoteX args in .config, to detect private IP and raise error with "Remote can not be on a private network" isn't it ?
(or something like that)

**Comment by M5oul** [comment]
Linked to #571.

**Comment by c-geek** [comment]
We should let the user put the values he wants for its configuration, we never know what does he want to do.

However, indeed, automatic configuration should not propose private IP as a public IP whenever a public IP is available: the latter should have the priority.

**Comment by M5oul** [comment]
May we close this ticket?

**Comment by c-geek** [comment]
No, just *prefer* the remote to the local.
