### ISSUE TITLE
Impossible to generate the root block

### ISSUE THREAD

**Issue by b3j0f** [duniter/duniter#564]
Hi,
I just created a new node, accessible from the http api, and I connected a new participant (not a member actually) from the sakia interface.
Then, I tried to create a root block, and I got this error (I haven't got time to put a newcomer to add...):
```bash
lyst@lyst:~$ duniter gen-root
2016-08-27T10:24:49-04:00 - debug: Plugging file system...
2016-08-27T10:24:49-04:00 - debug: Loading conf...
2016-08-27T10:24:49-04:00 - debug: Loading crypto functions...
2016-08-27T10:24:49-04:00 - debug: Upgrade database...
? Newcomers to add: (Press <space> to select)
❯◯ b3j0f2016-08-27T10:24:49-04:00 - error:  httpCode=400, ucode=2018, message=Wrong new block: cannot make a root block without members
2016-08-27T10:24:49-04:00 - error:  Error: [object Object]
    at Error (native)
    at /opt/duniter/sources/app/cli.js:829:15
    at process._tickCallback (node.js:412:9)
2016-08-27T10:24:49-04:00 - error:  Error: [object Object]
    at Error (native)
    at /opt/duniter/sources/app/cli.js:829:15
    at process._tickCallback (node.js:412:9)
```

Then, I tried to write the next block and the process is still running with this output...

```bash
2016-08-27T10:26:39-04:00 - debug: Plugging file system...
2016-08-27T10:26:40-04:00 - debug: Loading conf...
2016-08-27T10:26:40-04:00 - debug: Loading crypto functions...
2016-08-27T10:26:40-04:00 - debug: Upgrade database...
2016-08-27T10:26:40-04:00 - debug: Block to be sent: #0 (1 newcomers, 0 certifications)
2016-08-27T10:26:40-04:00 - info: Generating proof-of-work with NaN leading zeros followed by [0-undefined]... (CPU usage set to 60%)
2016-08-27T10:26:50-04:00 - info: Mesured max speed is ~106 tests/s. Proof will try with ~64 tests/s.
```

Did I miss something ? Or the command "gen-root" is became useless ?

**Comment by M5oul** [comment]
To launch a money, you need at least two members if one certification is needed to become members.
Certifications must be done on both ways before computing first block.
Did you put the future member pubkey on the node?

`gen-root` command is still useful and relevant.

**Comment by c-geek** [comment]
Yes I've encountered the bug as well, you need to click on "Stop HTTP" and then "Start HTTP" to have the block generated. This is a bug.

**Comment by b3j0f** [comment]
I don't have access to the webadmin to create the root block. I just use the command line. I will try tomorow with two registered people not yet member. 
If you know how to get them such as members before creating the root block, it will be helpful cause the root block creation does not permit me to indicate member names (it crashes before :/).

**Comment by M5oul** [comment]
> If you know how to get them such as members before creating the root block

In fact, there must be an implemented trick which permits creating root block with futures members identities.

> root block creation does not permit me to indicate member names (it crashes before :/)

What do you mean? You only need to put Secret key and password on the node.
Secret key and password are like an alias of the identity name.

**Comment by b3j0f** [comment]
I should have miss something. I don't know where to put secret key and password on the node.

Maybe in the configuration file... 

I'll do some tests this afternoon and tell you later what happened.

**Comment by M5oul** [comment]
- You could configure it this command:
```bash
duniter config --salt <salt> --passwd <password>
```

- or editing `~/.config/duniter/duniter_default/conf.json`.

Then, the node need to be restarted.

**Comment by b3j0f** [comment]
I succeed to access to the webadmin interface and ends at the root block creation.

I pushed "give a try" and I got the message "Wrong new block: cannot make a root block without members".
I tried to stop the http and start, but I have the same message.
I am sorry, I know I need to add members before but I don't know how to do it.

How can I put a pubkey in the node ?

**Comment by M5oul** [comment]
@b3j0f, why don't join current testing currency `Test-Net` at `duniter.org:8999`?
Creating a currency is more tricky to do.
Furthermore, we don't create a new currency everyday.

**Comment by b3j0f** [comment]
I already joined this currency. I try to launch a new currency for a local group in order to use a it in a concrete case. The dividend frequency of Test-Net is not ok for our use.

**Comment by M5oul** [comment]
Ok,

First you will need two identities which certifiy each-others.
Then put credentials on the node as [explained upper](https://github.com/duniter/duniter/issues/564#issuecomment-243735763).
Then start the node, it should create root block.
If it doesn't works, there must be a bug, as we didn't tried to much this functionality since a while.

**Comment by c-geek** [comment]
Please retry with [Duniter v0.31.0a5](https://github.com/duniter/duniter/releases/tag/v0.30.0a5). The release will be available in the coming minutes.

**Comment by b3j0f** [comment]
I retried and this time it works from the webadmin interface. Thank you.

After starting the root block, other block have been created after ... 0s !
Maybe I mess some configuration properties.

I will tell you what's wrong this time in another issue if I don't success to fix my problem.

Thank you for resolving this bug. Cya

**Comment by c-geek** [comment]
Yes it is normal about the 0 second. If you wait some minutes, Duniter will increasse the difficulty enough to reach the average block time you configured in the currency parameters.
