### ISSUE TITLE
Impossible to start the webserver with the commands "webwait" or "webstart"

### ISSUE THREAD

**Issue by b3j0f** [duniter/duniter#565]
Hi,
I have a new node without members and no block.

When I use both webwait or webstart, it is like I just want to start the server:
```bash
lyst@lyst:~$ duniter webwait
Starting duniter_default daemon...
duniter_default daemon started. PID: 22113
```
And the webinterface is not accessible (only the http api is accessible after starting the server).

Maybe it could help but if the server is down and I start the "webwait" command, I have a server process in my process stack but the http api is not accessible. Then, even if I do duniter start or duniter webstart, nothing new, a process duniter_default is still running and the http api is not accessible.

And I don't have any information in the log file.

**Comment by M5oul** [comment]
If you want the node and the web admin to start at the same moment, you have to run `duniter webstart`:
```bash
duniter --help
start          Start Duniter server.
webwait        Start Duniter web admin.
webstart       Start Duniter web admin + immediately start the server.
```

Did you installed it by yourself? If so, you [have to install](https://github.com/duniter/duniter/blob/master/doc/contribute-french.md#installer-linterface-graphique) [duniter-ui](https://github.com/duniter/duniter-ui) submodule.

**Comment by b3j0f** [comment]
I installed the node with the debian package.

I am unable to start the webadmin, whatever the command I use.

starting with a server down...
- start : start a duniter_default process and the http api is ok
- webwait : start a duniter_default process and the http api is not ok
- webstart : start a duniter_default process and the http api is not ok

All cases have the same output, but the two last ones do not permit to start the http api even if I use the start command after.

**Comment by M5oul** [comment]
Stange, did you checked the web admin is accessible with `curl -s localhost:9220`?

---

What do you means by `http api`?
- the duniter http api, for instance `/node/summary`
- the web admin?

**Comment by b3j0f** [comment]
Ok, the webadmin is available from the localhost address (I thought it was available from the local ipv4/v6 address configured from duniter config), thanks.

The http api (which resolves "/node/summary") is not accessible after doing commands "duniter webwait; duniter start" or "duniter webwait; duniter webstart" or "duniter webstart".

Therefore, I have to choose between the webadmin without accessible API (and maybe the server as well) or the server without webadmin.

**Comment by M5oul** [comment]
> webadmin is available from the localhost address.

Yep, the fact that web admin is only available from localhost, it's for security reasons

---

> http api (which resolves "/node/summary") is not accessible

- Did you tried with?:
```bash
curl -s <host>:<port>/node/summary
```
- Does network configuration seems good?

You can take a look at it on `~/.config/duniter/duniter_default/conf.json`.

You will have to restart the node if you modify the conf.

**Comment by b3j0f** [comment]
The http api is available only if I do "duniter start" or "duniter webstart" after "duniter stop".

If I use "duniter webwait" before or after a "duniter start", the http api is no more available.

Therefore, I will use only "duniter webstart" if I want both webadmin and http api.

**Comment by M5oul** [comment]
> The http api is available only if I do "duniter start" or "duniter webstart" after "duniter stop".

Yep, it works like that.

I don't know what `duniter webwait` command is for.

**Comment by b3j0f** [comment]
ok, thank you very much !
