### ISSUE TITLE
[Cesium] Transaction issue...

### ISSUE THREAD

**Issue by modulix** [duniter/duniter#566]
Hi,

I got this message on http://cesium.duniter.fr/#/app/registry/view/AVa71832VNaLy5n_s86y/remuniter
when trying to send money (around 21:14 today)...It is not the first time. Have someone idea from where can come this issue ?

![capture d ecran de 2016-08-27 21-16-53](https://cloud.githubusercontent.com/assets/14559496/18029581/130713f0-6c9c-11e6-89f7-4b331294ffc5.png)

**Comment by M5oul** [comment]
Why didn't you opened it on Cesium bugtracker?

**Comment by modulix** [comment]
Because i'm stupid ;-). Sorry, i'm going to create a new one in the right project... Close this one plz.

**Comment by modulix** [comment]
Done in https://github.com/duniter/cesium/issues/126
