### ISSUE TITLE
When changing CPU PoW to 0%, it's not changed

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#567]
When I put to CPU to 0%, it don't change on the conf file.
It change when going to 1% for instance.

**Comment by c-geek** [comment]
Currently fixing it, haha, it's quite fun to hear the fan is rotating quicker as CPU is set to 100%, and rotating silently when CPU is set to 1%, on-the-fly :smile:

**Comment by M5oul** [comment]
Well done, it's almost immediate modification on my desktop computer.
