### ISSUE TITLE
Add "enp0s3" in the priority list of network interfaces

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#571]
Note: I don't know at all what is this interface name ... is it a local one? private network?

**Comment by c-geek** [comment]
Here is the faulty code: https://github.com/duniter/duniter/blob/master/app/lib/system/network.js#L303-L315

**Comment by c-geek** [comment]
See http://blog.devarieux.net/2015/08/comprendre-la-prediction-de-noms-des-interfaces-reseau-de-systemd/

**Comment by c-geek** [comment]
Also http://p3ter.fr/debian-ubuntu-eth0-c-est-fini.html

**Comment by c-geek** [comment]
@M5oul si tu te sens d'attaque ... hésites pas ! En plus tu sais faire des préversions, ça peut aider Jean_F à avoir son noeud qui tourne !

**Comment by M5oul** [comment]
Ok, je regarde ça plus tard.

**Comment by M5oul** [comment]
So, it could exist [many network interfaces names](https://community.spiceworks.com/topic/975404-what-does-enp0s3-mean-stand-for?page=1#entry-4658625) with this new conventions:

>"ethernet network peripheral # serial #"﻿

I already found:

- enp3s0f1 (on my Fedora interface)
- enp0s3 (on upper links)
- enp3s0 (on upper links)
- wlp4s1 (on upper links) for Wi-Fi.

It seems it could take many values.

I could temporally add them.

How could we match them all?

**Comment by modulix** [comment]
I guess that a good start should be to use list given by :
`$ ip link show`

**Comment by M5oul** [comment]
Yep, we could also found them with `ifconfig` command.

**Comment by modulix** [comment]
For me, the best way to find the best interface to use is to get it by routing:
`$ ip route | grep ^default | awk '{print $5}'`
(no need to know which name it have)

**Comment by c-geek** [comment]
In [these lines of code dedicated to our issue](https://github.com/duniter/duniter/blob/master/app/lib/system/network.js#L303-L313), you can match them all by adding 2 regexps like:

```js
if (entry.name.match(/^enp\ds\d/))  return 0;
if (entry.name.match(/^wlp\ds\d/))  return 1;
```

But to find the prefered one, maybe you need specific OS commands.

You also have [Node.js documentation about network interfaces](https://nodejs.org/api/os.html#os_os_networkinterfaces).

**Comment by modulix** [comment]
I was looking on https://www.npmjs.com/package/network but your regex sound good... it seems to be a very good solution.

**Comment by c-geek** [comment]
We also have to handle Windows interfaces! I discovered it today with #573. I hope MacOS it just like Linux on this side.

**Comment by M5oul** [comment]
> $ ip route | grep ^default | awk '{print $5}'

This command return nothing on my Fedora instance.
Not sure it would be easy to found an universal  shell command which could easily grep this network interface name.

The best way would be to match them all with a JavaScript regex.

**Comment by modulix** [comment]
>    $ ip route | grep ^default | awk '{print $5}'
> This command return nothing on my Fedora instance.

Sorry, it was not a real proposition of code to use, but more to show the logic i use to obtain interface name. Start from the routing table and select default gateway to get interface name... But it's much more complicated to do that in js!  For now, the regex seems very good ;-)

**Comment by c-geek** [comment]
Just tested on my Ubuntu 16.04, works like a charm :+1:
