### ISSUE TITLE
Add higher logo resolution for desktop version

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#578]
![duniter_logo](https://cloud.githubusercontent.com/assets/4758871/18136673/dd1f60b4-6fa5-11e6-953f-3fbd38208540.png)

**Comment by c-geek** [comment]
![image](https://cloud.githubusercontent.com/assets/969136/18881886/57438572-84dd-11e6-8e1b-5b7d49015b81.png)

Fixed.

**Comment by M5oul** [comment]
Finally, logo resolution is not enough large for HiDPI 4K sceen:
![capture d ecran de 2016-09-27 18-21-27_cut](https://cloud.githubusercontent.com/assets/4758871/18882483/a019df38-84df-11e6-91a7-4dec919f839c.png)

**Comment by c-geek** [comment]
On Ubuntu, I had to remove the `.local/share/applications/v[0.30.x]_.desktop` file before seeing the new icon.

**Comment by M5oul** [comment]
I found nothing related to Duniter on `~/.local/share/applications/` and `~/.local/share/`.

**Comment by c-geek** [comment]
That's because you are not on Unity, I guess.

**Comment by c-geek** [comment]
I don't see any difference between your 2 screenshots, it's like nothing have changed for you. However it did change on my side, so I suppose there are some artificats on your machine (desktop files?) avoiding the good display of the logo.

**Comment by M5oul** [comment]
I use tar archive and not debian package, so the logo shouldn't be stored somewhere.
[I tried to search for Duniter logo wit](https://askubuntu.com/a/52432) with [this names](https://github.com/duniter/duniter/tree/master/images) and found no logo path.
Furthermore, nothing on [`/usr/share/icons`](https://askubuntu.com/questions/6009/where-are-icons-stored).

**Comment by c-geek** [comment]
Can you give me your system configuration so I can reproduce it on a VM?

**Comment by M5oul** [comment]
It's [Fedora 24](https://getfedora.org/en/workstation/download).

**Comment by c-geek** [comment]
Or even better: you should make a VM and test on it. :smile:

**Comment by M5oul** [comment]
Ok :smile:

**Comment by M5oul** [comment]
It seems it's same problem on a fresh VM:
![capture d ecran de 2016-09-27 20-26-11_cut](https://cloud.githubusercontent.com/assets/4758871/18886677/2792655a-84f1-11e6-90c9-f4ca9fc6880f.png)

**Comment by c-geek** [comment]
Ok, so I will check that tommorrow.

**Comment by c-geek** [comment]
OK I succeed to make the test, it still fails... I really don't know what to do. I remove this issue from milestones 0.4x.

**Comment by M5oul** [comment]
Yep, same problem.

**Comment by c-geek** [comment]
There is absolutely no link with 557a373 ... the issue has been migrated here: https://git.duniter.org/nodes/typescript/duniter/issues/578
