### ISSUE TITLE
Wallet button should be moved to an other place

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#583]
I have the habit to click on all tab without thinking, and when click on Wallet, It open Cesium in a new tab. I found that annoying.

It would be better to put the button to open Cesium in an other place than in the middle of other tabs.
On the right, with other button could be great.

**Comment by c-geek** [comment]
Agreed.

**Comment by c-geek** [comment]
It will now be located here:

![image](https://cloud.githubusercontent.com/assets/969136/18920374/829d4dce-85a1-11e6-861d-02af2cc295af.png)
