### ISSUE TITLE
Benefit from multi-cores for PoW computing

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#584]

**Comment by c-geek** [comment]
@M5oul could you confirm you no more have issues with child processes (engines) not being closed when you exit Duniter? The engines are now self-killing them after 10 seconds without messages from main process.

**Comment by c-geek** [comment]
Note: you can confirm with beta6 when released.

**Comment by M5oul** [comment]
Nice job, `proof.js` process suicide them-selves a while after `duniter stop` command is launched.
