### ISSUE TITLE
Better way for endpoints display

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#594]
It would be better to store endpoints on a dict (key => value).
Should ever client implement something an annoying parsing algo or should the node do it?
```json
curl http://moul.re:8999/network/peering
{
  "version": 2,
  "currency": "test_net",
  "endpoints": [
    "BASIC_MERKLED_API misc.moul.re 78.227.107.45 8999",
    "BASIC_MERKLED_API desktop.moul.re 78.227.107.45 2a01:e34:ee36:b2d0:e79:cd45:ed65:147 24723"
  ],
  "block": "38338-0000FDEA57D2784A1E0F6288E7B5C5312D6E3A42021833288C9D99FAFE5F80C8",
  "signature": "CFsAT5VnDnRcCDRK17iOVmIe4JB+jxwVka02z8hX/c5Ox07hhNTZRcopyxx83J13qPOV7OKBVgrPhqhRpIrSBw==",
  "raw": "Version: 2\nType: Peer\nCurrency: test_net\nPublicKey: J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3\nBlock: 38338-0000FDEA57D2784A1E0F6288E7B5C5312D6E3A42021833288C9D99FAFE5F80C8\nEndpoints:\nBASIC_MERKLED_API misc.moul.re 78.227.107.45 8999\nBASIC_MERKLED_API desktop.moul.re 78.227.107.45 2a01:e34:ee36:b2d0:e79:cd45:ed65:147 24723\n",
  "pubkey": "J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3"
}⏎
```

From client point of view, parsing implementation seems annoying to do even with one endpoint.
Sometimes `domain` or `ipv6` fields are not here.
It could looks like:
```json
"endpoints": [
   {
     "protocol": "BASIC_MERKLED_API",
     "domain": "misc.moul.re",
     "ipv6": null,
     "ipv4": "78.227.107.45",
     "port": "8999"
   },
   {
     "protocol": "BASIC_MERKLED_API",
     "domain": "desktop.moul.re",
     "ipv6": "2a01:e34:ee36:b2d0:e79:cd45:ed65:147",
     "ipv4": "78.227.107.45",
     "port": "24723"
   },
   {
     "protocol": "ESLASTIC_SEARCH_API",
     "domain": "es.moul.re",
     "ipv6": "2a01:e34:ee36:b2d0:e79:cd45:ed65:147",
     "ipv4": "78.227.107.45",
     "port": "45454"
   }
]
```

**Comment by Insoleet** [comment]
Well, each endpoint can have its own format. For example, an endpoint could need more info than only domain/ipv4/ipv6/port. How could we encode in JSON unknown formats ?

**Comment by M5oul** [comment]
With unpredictable formats we could add some new field?

**Comment by Insoleet** [comment]
Yes, that's how it's done with Sakia : 

- For each endpoint, we try to parse it using known endpoints parsers (at the moment, only BMA is managed)
- If the endpoint could not be parsed, it's handled as a unknown endpoint and never used.

Duniter is agnostic of the endpoints it is handling. It officially handles BMA, but users are free to add more specific endpoints to their node. That's why Duniter exposes its endpoints in raw format !

**Comment by M5oul** [comment]
Ok, thanks for the anwser.
Now, let's parse this raw endpoints :smile_cat:
