### ISSUE TITLE
Send success or fail status at the end of command

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#596]
I launched this commands:

``` bash
npm i && duniter stop && duniter reset data && duniter sync duniter.org 8999 && duniter start
```

last command was launched while sync command fail.
Duniter command line tool must send success or fail status at the end of command execution.
I think it would be great to have it for every duniter commands.

**Comment by c-geek** [comment]
There is absolutely no link with 8889a36 ... the issue has been migrated here: https://git.duniter.org/nodes/typescript/duniter/issues/596
