### ISSUE TITLE
Duniter 0.30.17 infinite loop

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#597]
Duniter 0.30.17 c'est curieux... Avec Peer = 100% il monte le Network de 0% à 100%, puis revient à 0% -> 100% plusieurs fois... Puis il recommence avec Peer 0%... il s'arrête pas...

Ah ça y est c'est bon, "Next Sync in..." ah non ça recommence... Peer 0% Network 0% c'est reparti... => infinite loop (since 45 minutes now...)

Log file : [log.txt](https://github.com/duniter/duniter/files/474094/log.txt)

PS : enhancement : it misses a button in the log console to export the log file (save as...) I made a copy/paste, but the text in the console move.. (including whith "pause log"), so it is not easy to do...

**Comment by c-geek** [comment]
There is a share button in 0.31, but this version is not released yet.

**Comment by c-geek** [comment]
La synchronisation intervient toutes les 5 minutes environ, c'est normal de voir l'événement de façon récurrente (infinie).

Quant au yoyo 0% -> 100%, je vais le corriger, c'est un choix d'affichage pas forcément pertinent de ma part.
