### ISSUE TITLE
Use an url path instead of a port number?

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#598]
As mentioned by @blavenie on the chat room:

> [09:35:16] <kimamila> cgeek: ce Peut on configurer Duniter pour publier une adresse de noeud du genre : "https://duniter.fr/test_net"

I have ever think to use a solution like that for Duniter and Cesium YunoHost apps to facilitate connections.

This is to [solve https issues to join nodes with Cesium app](https://github.com/duniter/cesium/issues/122#issuecomment-247609242).

It could be done with a proxy conf.

**Comment by c-geek** [comment]
BMA does not allow such URL schemes, but you can circumvent this using revert proxy configuration. Such configuration should like the following using Nginx:

```
server { 
 
  listen 443; 
  server_name some.node.myadress.org; 
  ssl on; 
  ssl_certificate /etc/ssl/certs/https.crt; 
  ssl_certificate_key /etc/ssl/private/https.key; 
  ssl_session_timeout 5m; 
 
  location / {  
    proxy_set_header        X-Real-IP       $remote_addr;  
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;  
    proxy_set_header      X-Forwarded-Proto $scheme; 
    proxy_set_header        Host            $http_host;  
    proxy_set_header        X-NgninX-Porxy  true;  
  
    proxy_pass http://localhost:8999; # Duniter node, HTTP
    proxy_redirect          off;  
  
    # Socket.io support  
    proxy_http_version 1.1;  
    proxy_set_header Upgrade $http_upgrade;  
    proxy_set_header Connection "upgrade";  
  
  }   
}                                        
```

It seems to already work on duniter/cesium#122.

**Comment by blavenie** [comment]
What we need is to be able to configure a Dunitr node on any web address, not only [host + port].
like : protocole, host, port, path

**Comment by c-geek** [comment]
(09:43:30) cgeek: Ouai mais, là encore, c'est quelque-chose que je n'ai pas besoin de développer depuis https://github.com/duniter/duniter/issues/337 : il suffit d'ajouter une entrée que vous nommez comme vous voulez, "SBMA" par exemple, et qui définit cette norme. C'est d'autant plus justifié que là on est dans un cas d'utilisation d'administrateur réseau, et pas le cas général qui n'utilise pas HTTPS.

**Comment by c-geek** [comment]
(09:43:42) cgeek: Ce sera dispo en 0.40 par contre :)
(09:44:19) cgeek: Bref vous pouvez le faire sans moi, tout de suite, en installant une 0.40.0aX

**Comment by c-geek** [comment]
Problème résolu !

**Comment by M5oul** [comment]
Yep, it will be a Duniter extension. We don't need to overload Duniter code source.
We could let open this ticket to develop and discuss this new API.
We could documented it on Duniter doc or by opening a new repository on Duniter organization.

**Comment by c-geek** [comment]
There is absolutely no link with 9c40d1c ... the issue has been migrated here: https://git.duniter.org/nodes/typescript/duniter/issues/598
