### ISSUE TITLE
Multiple instances of Duniter "desktop" under Windows7

### ISSUE THREAD

**Issue by pifpafpof** [duniter/duniter#599]
After installing Duniter 0.31.0a9 under Windows 7 (not pro), the application is launched 5 times in a row.
So 5 (clients) instances are displayed.

After stopping all instances and re-launching Duniter from the desktop shortcut, Duniter is launched properly i.e. only one window runs.
But bizzarely, the task bar does not display the right icon.

Stopping the server, and relaunching the Duniter application seems to resolve this small issue.

**Comment by pifpafpof** [comment]
J'ai installé aussi duniter sous LinuxMint 17.3 (Debian).
Comportement assez similaire lors de la 1ère execution de "duniter desktop" 0.30.17, 2 fenêtre s'ouvrent !?
Si je les ferme et ré-execute, une seule fenêtre cette fois.
Next time in english ;-)

**Comment by M5oul** [comment]
Oui, je vois ce que tu veux dire.
J’ai aussi ce problème : 
J’ai une fenêtre centrale qui s’ouvre puis qui se ferme immédiatement, puis une seconde fenêtre, plus grande et centrée sur la gauche, s’ouvre. Cette dernière fenêtre est celle que j’utilise au final.

**Comment by c-geek** [comment]
Devrait être corrigé par la #578.

**Comment by M5oul** [comment]
Yep, seems better. Shouldn't happen.

**Comment by c-geek** [comment]
Please retry with latest 0.31.0 beta version, or with 0.31 when officially released (in the coming days or hours).
