### ISSUE TITLE
Enhancement: Duniter desktop 0.31.0a9 Money Units details & explanations ?

### ISSUE THREAD

**Issue by pifpafpof-thomasL** [duniter/duniter#600]
Despite the fact it is the "server interface, on Duniter 0.31.0a9  under Settings / Currency / Money Units
1) 
the fields "UD period", "Delay between.." and all other time related fields could mention the fact it is in **seconds** and maybe in bracket could mention the corresponding time in hours (or days).
For example:
UD period : 86400
could become
UD period : 86400 seconds (1 day)

2)
Also C shall be related to a period of time (days, years?) and it is not mentioned on the UI.
A ? icon could explain that if a setting of 0.1 years means after 10 years the user is entitled to 77% of the DU, and 99% of the DU after 40 years (to be confirmed)
Actually this ? icon could be for the Cesium UI which is more user oriented. 

3) UD could be written in full text :
UD (Universal Dividende)

**Comment by c-geek** [comment]
Yes, you are right ... I will let this kind of changes to UI contributors, there will be a guide of contribution soon, see #605

**Comment by c-geek** [comment]
Finally, creating a new money is no more handled in the UI, it is considered to be an exceptional use case requiring usage of CLI.

**Comment by c-geek** [comment]
Note: this could be explained in the docs, though.
