### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ktorn** [duniter/duniter#602]
Running into a build issue on Mac OS 10.11.6, node v6.6.0, and npm 3.10.7.

```
npm ERR! wotb@0.4.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wotb@0.4.11 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wotb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wotb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wotb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/dev/duniter/npm-debug.log
```

More info: [npm-debug.log](https://gist.github.com/ktorn/b8d5b9ba4f7c7861ee4609873232d547)

**Comment by M5oul** [comment]
Duniter can't works with Node.js 6.x for now. See https://github.com/duniter/duniter/issues/496 and https://github.com/duniter/duniter/issues/381.

Build issue you encounter looks like to https://github.com/duniter/duniter/issues/412.
Did you use `root` user to compile? There is some issues compiling with `root`.

**Comment by ktorn** [comment]
Not using root, and I have also tried with:
- node v4.5.0
- npm  v2.15.9
But still fails.

I think the issue may be related to [this](http://stackoverflow.com/questions/21752172/invalid-deployment-target-for-stdlib-libc-on-osx-10-8). I will give it a try later and report back here.

**Comment by M5oul** [comment]
Yep, you may be the first one trying to compile Duniter on Mac OS.
That could be the issue.

**Comment by ktorn** [comment]
OK, I finally managed to build Duniter on Mac OS 10.11.6.

For future reference, after lots of trial and error I was always running into one of 2 problems with module `wotb`:

`../wotcpp/include/AbstractWoT.h:4:10: fatal error: 'cstdint' file not found`
and
`clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)`

Finally managed to solve it by running the following exports:

`export MACOSX_DEPLOYMENT_TARGET=10.7`
`export CXXFLAGS="-stdlib=libc++ -std=c++11 -mmacosx-version-min=10.7 -DGTEST_USE_OWN_TR1_TUPLE=1"`

Only then `npm install` completed successfully.

**Comment by c-geek** [comment]
@ktorn, @Insoleet: do you know if, using Travis, I could reproduce the MacOS environment? So that such errors could be detected earlier. Also, I will write a common developer guide in the coming days/weeks, because the french one is 1) in french 2) focused on WebStorm 3) Linux & Windows only.

**Comment by Insoleet** [comment]
Yes you can. I do MacOS + Linux build on travis ! You have to use the matrix configuration like for sakia : https://github.com/duniter/sakia/blob/master/.travis.yml

**Comment by c-geek** [comment]
I've tried with Travis, unfortunately I do not reproduce @ktorn's error. So this is not exactly the same environment.

I will add the above MacOS tips in the docs, anyway.
