### ISSUE TITLE
CPU proof-of-work doesn't respect setting limit percentage

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#607]
`htop` shows process up to 70% by cores for 60% CPU limit setting:
![capture du 2016-09-22 14-14-43](https://cloud.githubusercontent.com/assets/4758871/18747943/36b08bae-80d0-11e6-8ed1-13c6dad42364.png)

**Comment by M5oul** [comment]
On my ARM board it's not respected, with setting set to 40%:
![htop_duniter_arm](https://cloud.githubusercontent.com/assets/4758871/18781371/b7903b00-8181-11e6-9b4a-11f8b52c5f89.png)

**Comment by M5oul** [comment]
There is still an issue on my ARM board, CPU is set to 50% and two processes takes most than 85%.

**Comment by M5oul** [comment]
There is almost no issue on my desktop computer, but on my ARM board it's crazy, I can't let Duniter take all CPU.

**Comment by M5oul** [comment]
There might be some issue running on ARM.
I still encounter [Proof-of-work computation canceled](https://github.com/duniter/duniter/issues/619) with 0.31.2b3.

**Comment by RavanH** [comment]
Yes, on my Raspberry Pi 2b3 keeps throwing the cancellation errors. Only when I set cpu to 0.1 it works without errors. As soon as CPU is set higher, it will run at 100% CPU usage constantly. With cpu set to 0.1 the actual usage (reported by htop) is about 60% for each core.

**Comment by c-geek** [comment]
I do lot have much time these days to investigate. However if you want to do it, you just need to have a look at proof.js file, see where the CPU var is used and try to see what is wrong, you can also make modifications and restart your node to see the effect.

**Comment by c-geek** [comment]
Reproduced on Raspberry PI 3.

**Comment by c-geek** [comment]
I can give you a first tip: using `duniter direct_start` command fixes all the problems.

But this does not explains why the normal commands produce this crazy 100% use and PoW cancellations..

**Comment by c-geek** [comment]
Fixed in 0.31.2. Just released.

> Please note that `htop` on a low computer like Raspberry PI won't reflect exactly 50% CPU usage by setting 50% CPU parameter. If you really want to dive into this particular point, please open a new ticket and refer to this one as a sidenote.

**Comment by M5oul** [comment]
Thanks. It's better now.
That's strange because, my ARM node found no blocks since PoW refactoring to multi-processes.
Also, It seems there is no matched blocks using following command:
```bash
cat ~/.config/duniter/duniter_default/conf.json | grep -i Matched
```

**Comment by RavanH** [comment]
Installed 0.31.2 and all seems well with cpu 0.1... top reports around 14% cpu usage for each of the 4 processes.

However, with cpu 0.6 the actual usage seemed to float around 82% at the start but after a few minutes it spiked to 100% and now stays there constantly... Log reports nothing unusual. Calculation, pulling and posting to peers is being done.
