### ISSUE TITLE
Message d'erreur avec l'option UPnP

### ISSUE THREAD

**Issue by vincentux** [duniter/duniter#611]
Suite à l'installation de duniter_ynh j'ai eu le message suivant : 
`2016-09-23T10:33:36+00:00 error No UPnP gateway found: your node won't be reachable from the Internet. Use --noupnp option to avoid this message.`

@M5oul m'a conseillé de décocher l'option UPnP dans l'interface graphique de duniter, ce que j'ai fait 
![23-09-2016-06-05](https://cloud.githubusercontent.com/assets/11737560/18784023/99870e28-818f-11e6-8176-e661c5cd9b31.png)

mais j'ai de nouveau le message : 

![23-09-2016-06-51](https://cloud.githubusercontent.com/assets/11737560/18784027/9fbc32a0-818f-11e6-8d74-bcb523564874.png)

**Comment by M5oul** [comment]
Reported on this ticket: https://github.com/duniter/duniter_ynh/issues/24.
If fact, UPnP gateway is still researched even if UPnP option is disabled.

**Comment by c-geek** [comment]
You need to restart the node before the option is even considered. Have you done it?

**Comment by vincentux** [comment]
j'ai bien redémarré mon nœud, mais j'ai toujours ce message ...
Comment vérifier que l'option est bien pris en compte ? Où est le fichier conf.json ?

**Comment by M5oul** [comment]
> Où est le fichier conf.json ?

Here `~/.config/duniter/duniter_default/conf.json`.

**Comment by vincentux** [comment]
Heu c'est moi ou il est pas comme d'hab ? il n'y a pas la config réseau ...
```
{
 "sync": {},
 "createNext": true,
 "routing": true,
 "cpu": 0.6,
 "c": 0.007376575,
 "dt": 2629800,
 "ud0": 100,
 "stepMax": 3,
 "sigPeriod": 0,
 "sigStock": 40,
 "sigWindow": 604800,
 "sigValidity": 31536000,
 "msValidity": 31536000,
 "sigQty": 5,
 "idtyWindow": 604800,
 "msWindow": 604800,
 "xpercent": 0.9,
 "percentRot": 0.6666666666666666,
 "blocksRot": 20,
 "powDelay": 0,
 "avgGenTime": 960,
 "dtDiffEval": 10,
 "medianTimeBlocks": 20,
 "rootoffset": 0,
 "forksize": 100,
 "salt": "936244255",
 "passwd": "807333224",
 "pair": {
  "pub": "6k3kagQSf48TXCXUQQ329JCwFbYw1RoYkbnXfJ8HWRcT",
  "sec": "5JVqEpoVrfwiMnk3hXyttJSEXb5DXVSvC1vxMUss64qThKNhJjvayQyVUjtAW5VwMncxXMEBu3rJ7kzbqbMA9J2b"
 }
}
```

**Comment by M5oul** [comment]
Oui, c’est l’[un des seul nœud du réseau qui ne propose qu’un nom de domain et un port](https://github.com/duniter/silkaj#example). :smile:

**Comment by vincentux** [comment]
celui que tu me montre c'est le nœud de mon rpi "duniter.vincentux.fr" mais là j'essai d'en installer un autre avec yunohost sur un vps "testnet.vincentux.fr" et lui est en rouge avec sakia :/

**Comment by M5oul** [comment]
Ah, dans ce cas il doit y avoir un problème à la configuration réseau.

**Comment by vincentux** [comment]
voila le fichier conf.json de mon rpi
{
 "currency": "test_net",
 "port": "8999",
 "ipv4": "192.168.0.18",
 "ipv6": null,
 "upnp": true,
 "remotehost": "duniter.vincentux.fr",
 "remoteipv4": null,
 "remoteipv6": null,
 "remoteport": "8999",
 "salt": "***********",
 "passwd": "***********",
 "cpu": 0.9,
 "upInterval": 3600000,
 "c": 0.1,
 "dt": 86400,
 "ud0": 100000,
 "stepMax": 5,
 "sigPeriod": 10800,
 "sigValidity": 31557600,
 "msValidity": 15778800,
 "sigQty": 1,
 "xpercent": 0.9,
 "percentRot": 0.66,
 "blocksRot": 40,
 "powDelay": 0,
 "avgGenTime": 300,
 "dtDiffEval": 25,
 "medianTimeBlocks": 12,
 "participate": true,
 "httplogs": false,
 "udid2": false,
 "timeout": 3000,
 "routing": true,
 "isolate": false,
 "forksize": 100,
 "sync": {},
 "createNext": true,
 "sigStock": 40,
 "sigWindow": 2629800,
 "idtyWindow": 604800,
 "msWindow": 604800,
 "rootoffset": 0
}

**Comment by vincentux** [comment]
C'est bon je l'ai trouvé ici : 

`./root/.config/duniter/duniter_default/conf.json`

il m'a l'air bon
```
{
 "currency": "test_net",
 "port": 8999,
 "ipv4": "127.0.0.1",
 "ipv6": null,
 "upnp": false,
 "remotehost": "testnet.vincentux.fr",
 "remoteipv4": null,
 "remoteipv6": null,
 "remoteport": 8999,
 "salt": "joe@example.tld",
 "passwd": "supersecretpassword",
 "cpu": 0.8,
 "upInterval": 3600000,
 "c": 0.1,
 "dt": 86400,
 "ud0": 100000,
 "stepMax": 5,
 "sigPeriod": 10800,
 "sigValidity": 31557600,
 "msValidity": 15778800,
 "sigQty": 1,
 "xpercent": 0.9,
 "percentRot": 0.66,
 "blocksRot": 40,
 "powDelay": 0,
 "avgGenTime": 300,
 "dtDiffEval": 25,
 "medianTimeBlocks": 12,
 "participate": true,
 "httplogs": false,
 "udid2": false,
 "timeout": 3000,
 "routing": true,
 "isolate": false,
 "forksize": 100,
 "sync": {},
 "createNext": true,
 "sigStock": 40,
 "sigWindow": 2629800,
 "idtyWindow": 604800,
 "msWindow": 604800,
 "rootoffset": 0
}
```

**Comment by vincentux** [comment]
Pffff comprend pas ... j'ai bien l'option UPnP à "false" pourtant :'(
```
2016-09-26T16:12:32+00:00 info UPnP: configuring...

2016-09-26T16:12:34+00:00 warn 

2016-09-26T16:12:36+00:00 error No UPnP gateway found: your node won't be reachable from the Internet. Use --noupnp option to avoid this message.

2016-09-26T16:12:51+00:00 info Checking UPnP features...

2016-09-26T16:12:53+00:00 error Error: timeout
    at Timeout._onTimeout (/opt/duniter/sources/node_modules/nnupnp/lib/nat-upnp/client.js:178:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

2016-09-26T16:12:32+00:00 info UPnP: configuring...

2016-09-26T16:12:34+00:00 warn 

2016-09-26T16:12:36+00:00 error No UPnP gateway found: your node won't be reachable from the Internet. Use --noupnp option to avoid this message.

2016-09-26T16:12:51+00:00 info Checking UPnP features...

2016-09-26T16:12:53+00:00 error Error: timeout
    at Timeout._onTimeout (/opt/duniter/sources/node_modules/nnupnp/lib/nat-upnp/client.js:178:14)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by c-geek** [comment]
C'est probablement un bug. Je vérifierai.

**Comment by c-geek** [comment]
Sera résolu dans la prochaine version corrective.

**Comment by vincentux** [comment]
Tu as trouvé ?

**Comment by c-geek** [comment]
Oui, regardes le commit au-dessus de mon message : en fait, à chaque fois que tu allais sur la page d'accueil de l'UI, cela envoyait une trame UPnP. J'ai corrigé en enrobant ce code d'un "if (upnpActivé)". Et voilà.
