### ISSUE TITLE
Debian ARM build issues on 0.31.0b1{6,7}

### ISSUE THREAD

**Issue by RavanH** [duniter/duniter#617]
Trying to upgrade 0.31.0b13 to the latest 0b17 release, the process takes a very long time while I do **not** see any of the many usual "inflating/creating/extracting" messages:

    $ sudo dpkg -i duniter-v0.31.0b17-linux-armv7l.deb
    (Lecture de la base de données... 32127 fichiers et répertoires déjà installés.)
    Préparation du dépaquetage de duniter-v0.31.0b17-linux-armv7l.deb ...
    rm: impossible de supprimer « /usr/bin/duniter-desktop »: Aucun fichier ou dossier de ce type
    Dépaquetage de duniter (0.31.0b17) sur (0.31.0b13) ...

Then after a while, I get:

    Paramétrage de duniter (0.31.0b17) ...
    Archive:  /opt/duniter/duniter-desktop.nw
      inflating: /opt/duniter/sources/github-release  
      inflating: /opt/duniter/sources/logs  
      inflating: /opt/duniter/sources/make_deb_package.sh  
       creating: /opt/duniter/sources/node_modules/
      inflating: /opt/duniter/sources/npm-debug.log  
    chmod: impossible d'accéder à « /opt/duniter/sources/bin/ucoind »: Aucun fichier ou dossier de ce type
    sed: impossible de lire /opt/duniter/sources/bin/ucoind: Aucun fichier ou dossier de ce type
    Traitement des actions différées (« triggers ») pour mime-support (3.58) ...

Then:

    $ duniter start
    -bash: /usr/bin/duniter: Aucun fichier ou dossier de ce type

With 0b16 it's the same... Downgrading to 0b13 solved the issue.

**Comment by M5oul** [comment]
Thanks it seems there is an issue for [ARM Debian builds for 0.31.0b1{6,7} as they only weight 10 Mo](https://github.com/duniter/duniter/releases).
They generally weight 30 Mo. 0.31.0b15 is working well on my ARM board.

**Comment by RavanH** [comment]
Ah yes...

Deb packages for the 0.31.0b15 tag are not available anymore on github so I'll stick with 0b13 for now ;)

**Comment by c-geek** [comment]
Yes there is an error during upload, sorry. I will investigate today.

**Comment by c-geek** [comment]
It's OK for 0.31.0b17, beta16 is coming.
