### ISSUE TITLE
Error: Proof-of-work computation canceled

### ISSUE THREAD

**Issue by RavanH** [duniter/duniter#619]
On ARM board (Raspberry Pi 3), `top` shows 4 node processes running...

One of the many entries from duniter.log:

    2016-09-27T18:50:54+00:00 - info: Generating proof-of-work with 5 leading zeros followed by [0-9A-F]... (CPU usage set to 60%) for block#42329 9Hrc2f
    2016-09-27T18:51:01+00:00 - info: Matched 3 zeros 00046C97EFA0CACEC954CB96ECB921DB2C5C3DC1D7682BFE7406254299842998 with Nonce = 400000000188 for block#42329 by 9Hrc2f
    2016-09-27T18:51:01+00:00 - info: POST Peer BnSRjMjJ7g#42328
    2016-09-27T18:51:05+00:00 - info: Proof-of-work interrupted for some unknown reason, restarting..
    2016-09-27T18:51:05+00:00 - warn: Proof-of-work computation canceled
    2016-09-27T18:51:05+00:00 - error: Proof-of-work computation canceled

https://forum.duniter.org/t/error-proof-of-work-computation-canceled/1288

**Comment by RavanH** [comment]
These errors come with v0.31.0b13 while after downgrade to v0.30.17 the errors are gone and PoW works fine.

**Comment by RavanH** [comment]
https://github.com/duniter/duniter/issues/607 related?

**Comment by c-geek** [comment]
It is because you are on the beta branch, on which we now use multiple cores computing. See #584

**Comment by c-geek** [comment]
Also see https://forum.duniter.org/t/error-proof-of-work-computation-canceled/1288/3

**Comment by RavanH** [comment]
Testing with different configs for CORES_MAXIMUM_USE_IN_PARALLEL and **cpu** with Duniter v0.31.0 on ARM 4-cores, I have found so far:

    cpu      CORES_MAXIMUM_USE_IN_PARALLEL     Found in log
    _____________________________________________________________
    0.6            8                Proof-of-work interrupted for some unknown reason
    0.6            4                Proof-of-work interrupted for some unknown reason
    0.6            2                Proof-of-work interrupted for some unknown reason
    0.6            1                Proof-of-work interrupted for some unknown reason
    0.2            4                Proof-of-work interrupted for some unknown reason
    0.2            1                Proof-of-work interrupted for some unknown reason
    0.1            1                OK
    0.1            2                OK
    0.1            4                OK
    0.1            8                OK

So, it seems only the **cpu** setting plays a role here... which is surprising as the cpu 0.1 setting does **not** reduce the cpu usage to 60% by any means, while (apparently) it does have influence on PoW computation somehow... Weird.
