### ISSUE TITLE
With shared keyring, try not to compute the exact same proof

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#634]
Indeed, if all the nodes with a shared keyring uses the same Nonce schema and have the exact same data to include into the block, then the computed proof will be exactly the same, repeated on each node.

Which is a pure waste of time and energy.

**Comment by Insoleet** [comment]
The simplest solution seems to use a random noonce generator. Don't you think so ?

**Comment by c-geek** [comment]
Possibly, or we could simply prepend the Nonce by the index of the peer in the Endpoints list, which is easy and a 100% collision free method.
