### ISSUE TITLE
Certification Cesium 0.3.8

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#636]
In Cesium 0.3.8 there is a problem in the certification process when going to "Annuaire -> member -> certification" Cesium allow the certification with only an "alert box", and wihtout asking the secret key / passkey, again, allowing then easy mistakes.

Cesium should not stock ever any secret key / passkey, and ask for it for any task that need it in Duniter.

**Comment by c-geek** [comment]
Cesium is proposed as a default client in Duniter, but duniter repo won't particularly handle the Cesium issues, so I close it.
