### ISSUE TITLE
Add block hash to cert_time in certified-by / certifiers-of

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#639]
Because of new Sakia features indexing all data received by websockets, I need to be able to handle blockchain rollbacks for certifications.
But to be able to detect blockchain rollbacks on certification data, I need to know the hash in addition to the block number of a certification.

https://github.com/duniter/duniter/blob/b87480153e6e9a065c5b4639b0e53e52f0381abf/app/controllers/wot.js#L117

The change is easy, I can do a commit if you want. But before doing so I'd just want to make sure that you agree on the principle. 

``` json
      "cert_time": {
        "block": 1474,
        "hash": "0000298BA43173BD353DE91C2C1BD0627B9ABBB4947DAF7D2B382AA0136C88FE",
        "medianTime": 1461861258
      }
```

**Comment by Insoleet** [comment]
Thinking back about it, I don't think I need this field to check for rollbacks. It's field to check document validity before accepting it in a block. We can probably cancel this issue.

**Comment by c-geek** [comment]
OK. :-)
