### ISSUE TITLE
sqlite 3.1.5 is making the build crash

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#643]

**Comment by c-geek** [comment]
It seems to be a conflict with naclb package.

**Comment by M5oul** [comment]
Linked to https://github.com/mapbox/node-sqlite3/issues/720.
Should be fixed with 3.1.6.

**Comment by c-geek** [comment]
Yep, already trying it here: https://travis-ci.org/duniter/duniter/builds/165775365

**Comment by c-geek** [comment]
Fixed since 0b32f789fa987bfdb773b91f7b1b49a9e8b3e584

**Comment by c-geek** [comment]
Done. 😃
