### ISSUE TITLE
SQLite Error on block#0, when joiners has certification from pubkey without uid

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#646]
Cas observé : 
- Le block #0 est généré par `gen-root`, en sélectinnant toutes les identités publiés;
- Le block #0 est envoyé à un noeud sans block (toujours par `gen-root`)
- Le noeud sort une erreur SQLLite "I/O Error" sur l'insertion dans `memership`

En débuggant, j'ai trouver qu'un des joiners du block #0 généré était certifié par une pubkey qui n'avait pas publié son uid (sans doute liée à une erreur dans les identifiatn de connexion, dans Cesium).
Or ce joiner n'avait que 4 autre certifications valides sur les 5 requises. La derniere étant donc invalide.

Le problème a disparu en ajoutant une certification "valide" au joiner.
Que l'on garde ou non la certification non valide ne change rien.

Désolé de n'etre pas allé plus loin. Mais fatalement cela pourra arriver lors d'une lancement en grande échelle d'une monnaie (phase d'inscription des membres fondateurs).

**Comment by c-geek** [comment]
OK je viens de comprendre. On devrait pouvoir le reproduire sur FakeNet alors, en étape de lancement.

**Comment by c-geek** [comment]
Ou tout simplement, je peux faire un Test Automatisé !

**Comment by c-geek** [comment]
We will fix this during GTest initialization, because the root block is handcrafted with development tools.

**Comment by c-geek** [comment]
It did not occur. Anyway, if it occurs, I will fix it during Ğ1 init.
