### ISSUE TITLE
Make the release author the one which tag

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#651]

**Comment by c-geek** [comment]
Do you know how to do this?

**Comment by M5oul** [comment]
Nope, it's seems releases are triggered with tags.
Travis should do the release with Travis account.
So, it won't be easy if it's linked to the account.

**Comment by M5oul** [comment]
It seems it works now.

**Comment by c-geek** [comment]
Yes, fixed by #952.

**Comment by M5oul** [comment]
Nice!
