### ISSUE TITLE
CLI is missing restart and webrestart commands

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#659]
```bash
  Commands:

    start                                   Start Duniter server.
    webwait                                 Start Duniter web admin.
    webstart                                Start Duniter web admin + immediately start the server.
    wizard [step]                           Launch the configuration Wizard
```

**Comment by c-geek** [comment]
I will do it, sure.

**Comment by c-geek** [comment]
Sorry, wrong issue, I was talking about #658

**Comment by c-geek** [comment]
No I think the fix is not correct, because restart commands are made by the duniter.sh script.

**Comment by M5oul** [comment]
`duniter.sh` calls `bin/daemon` for `restart` and `webrestart` sub-commands.
This commit only display the command and the description on CLI help.
Should we add two new functions on `app/cli.js` to handle specific things?

**Comment by c-geek** [comment]
OK I did not understand your commit. But yes, it would be nice to add 2 functions returning a message saying "you need to launch this command using duniter.sh" in case a user launch bin/duniter directly.

**Comment by M5oul** [comment]
Ok, understood, as these two sub-commands use `bin/daemon` it's great to prevent users to use `duniter.sh` and not `bin/duniter` which won't launch the daemon.

This is a specific and rare case which could happen to admin or programmer.

It's not very convenient to display a message. After launching theses sub-commands seems non-sense? on the CLI help isn't that good?

Furthermore [start, stop, restart sub-commands](https://github.com/duniter/duniter/blob/master/duniter.sh#L48-L49) lack of same problem.

This message could be displayed on documentation.

Oh, I missed `webstop` sub-command.

**Comment by c-geek** [comment]
Yes it could be displayed on documentation, but do you think having a documentation saying "please do not use this command" is clearer? I think it is more confusing, on my side. So I would have prefered to have a message from the cli.js which detects the error, and warns the user. Also, it is super easy:

```js
program
  .command('restart')
  .description('Restart Duniter node.')
  .action(() => logger.error('This command must not be launched directly, but by duniter.sh script'));
```

What's your opinon? We could ask for @Insoleet's opinion also, to decide by opinion of the majority :-)

**Comment by M5oul** [comment]
Yep, on documentation is far from the code and that's not the best solution.

Ok, I didn't write it on last comment, but I use all commands calling `bin/daemon` from `duniter …` as `duniter start` `duniter webrestart`. And it works perfectly.

Strange, using upper solution, no error logs was displayed on logs.

**Comment by c-geek** [comment]
Yes sorry, a correct code:


```js
program
  .command('restart')
  .description('Restart Duniter node.')
  .action(() => new Promise((resolve) => {
    logger.error('This command must not be launched directly, but by duniter.sh script');
    resolve();
  }));
```

> Ok, I didn't write it on last comment, but I use all commands calling bin/daemon from duniter … as duniter start duniter webrestart. And it works perfectly.

Sorry, I don't understand. You mean you call directly the daemon? That also works yes.

**Comment by M5oul** [comment]
> Sorry, I don't understand. You mean you call directly the daemon? That also works yes.

Yep, I mean I use `duniter.sh` from bash. So in fact it works.

----

Understood, running following command throw this error message:

```bash
./bin/duniter restart
2016-10-12T10:14:56+02:00 - error: This command must not be launched directly, but by duniter.sh script
```

But, for other sub-commands using `bin/daemon` it fail: 
```bash
[moul@moulinette duniter]$ ./bin/duniter stop
Unknown command 'stop'. Try --help for a listing of commands & options.
2016-10-12T10:15:06+02:00 - error:  Error: Exiting
    at Error (native)
    at Command.<anonymous> (/home/moul/projects/duniter/app/cli.js:845:11)
    at emitOne (events.js:77:13)
    at Command.emit (events.js:169:7)
    at Command.parseArgs (/home/moul/projects/duniter/node_modules/commander/index.js:617:12)
    at Command.parse (/home/moul/projects/duniter/node_modules/commander/index.js:458:21)
    at /home/moul/projects/duniter/app/cli.js:39:15
    at next (native)
    at onFulfilled (/home/moul/projects/duniter/node_modules/co/index.js:65:19)
    at /home/moul/projects/duniter/node_modules/co/index.js:54:5
```

I will add a function to handle all sub-commands using `bin/daemon`: `webwait|webstart|webstop|webrestart|start|stop|restart`

Also, `webstop` needs to be added.

I will do a pull request before merging the code.

**Comment by M5oul** [comment]
I tried to do a function with upper code but calling this function doesn't works.
I don't understand `promise` and what `() =>` syntax means.

**Comment by c-geek** [comment]
`() =>` is [an arrow function](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Fonctions/Fonctions_fl%C3%A9ch%C3%A9es), it is a shorcut for declaring a function.

About promises, you just need to understand here that we need to return one promise per command in cli.js, otherwise the Node engine might stop the program due to the async nature of the code.

Also, I missed to give you the `subCommand` function, as it is used for `webwait` or `webstart` commands. So here is a final code we could use:

```js

program
  .command('restart')
  .description('Restart Duniter node.')
  .action(subCommand(() => {
    logger.error('This command must not be launched directly, but by duniter.sh script');
    return Promise.resolve();
  }));
```

If you want to have the same behavior for several commands, you could also write:

```js
function needsToBeLaunchedByScript() {
    logger.error('This command must not be launched directly, but by duniter.sh script');
    return Promise.resolve();
}

program
  .command('restart')
  .description('Restart Duniter node.')
  .action(subCommand(needsToBeLaunchedByScript));



program
  .command('stop')
  .description('Stop Duniter node.')
  .action(subCommand(needsToBeLaunchedByScript));
```

**Comment by c-geek** [comment]
I'm pretty sure the daemon won't start if you try to use the `start` command, as [theses lines do not seem correct](https://github.com/duniter/duniter/blob/0.40/app/cli.js#L148-L149).

Also, it would be nice if we can still use `bin/duniter start`, which is also used by `bin/daemon direct_start` command. Could you do this?

**Comment by M5oul** [comment]
> I'm pretty sure the daemon won't start if you try to use the start command, as theses lines do not seem correct.

In fact, you are right, `start` command do not works.

Ok, I removed this blocking on `start` command.
