### ISSUE TITLE
Try to build duniter using Yarn

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#663]
`yarn` is pretended to be really faster and reliable than `npm`. I've already tried to build duniter using `yarn`, but at the moment it does not build because of  `vucoin` dependency. So let's try again once #662 is done.

If yarn is really faster and reliable, why not prefering to use it both in the developers' documentation + CI scripts (Travis + Appveyor).

**Comment by M5oul** [comment]
It seems a great tool as Node.js package manager:

- [Repository](https://github.com/yarnpkg/yarn)
- [Website](https://yarnpkg.com)
- [Facebook liberation post](https://code.facebook.com/posts/1840075619545360)
- [Blog post](http://yehudakatz.com/2016/10/11/im-excited-to-work-on-yarn-the-new-js-package-manager-2)

**Comment by c-geek** [comment]
Thanks for the references.

**Comment by c-geek** [comment]
Given by @vincentux: https://www.grafikart.fr/tutoriels/nodejs/dependances-npm-yarn-828

**Comment by M5oul** [comment]
I tried and succeed to build duniter dependencies using Yarn.
It was much faster.
It works fine.

**Comment by M5oul** [comment]
I also succeed to build web admin interface.
It's so much faster :smile:

**Comment by c-geek** [comment]
For Travis + AppVeyor: https://yarnpkg.com/en/docs/install-ci

**Comment by c-geek** [comment]
Works very well now.
