### ISSUE TITLE
Only propose duniter.org nodes by default

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#670]

**Comment by M5oul** [comment]
`duniter.org:8999` is not all the time up.
Why?

**Comment by c-geek** [comment]
Because of #680. It crashed.

**Comment by c-geek** [comment]
Clue:

    2016-10-30T10:17:11+01:00 - error: Proof-of-work error, but no listener is attached.

Is the last message displayed by `duniter logs` on duniter.org.
