### ISSUE TITLE
Revocation written on blockstamp

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#676]
To index correctly the blockchain, we need to know the information about the revocation blockstamp date of a given identity. 

At the moment, if we find the information `revoked: true` we need to parse the `https://github.com/duniter/duniter/blob/master/doc/HTTP_API.md#blockchainwithleavers` and the blocks found in this url if we want to get the blockchain date of the revocation to be able to handle rollbacks.

I think it is also the case for the `written on` information of a given identity (which seems to be the first document containing a given self certification written in the blockchain).

**Comment by c-geek** [comment]
You could have prefered [with/excluded](https://github.com/duniter/duniter/blob/master/doc/HTTP_API.md#blockchainwithexcluded) instead.

Anyway, I implemented the following: `/wot/lookup` now also returns a `revoked_on` field, which is the block number where the revocation was written.

So you can have 3 different couples:

```json
{
    "revoked": true,
    "revoked_on": 34500
}
```

...when an explicit revocation was written on block 34500.

```json
{
    "revoked": true,
    "revoked_on": null
}
```

...when an implicit revocation happened (the block is not remembered, I will do it later if it becomes necessary).

```json
{
    "revoked": false,
    "revoked_on": null
}
```
...when the identity has not been revoked at all.
