### ISSUE TITLE
Wrong hash in identity BlockUID

### ISSUE THREAD

**Issue by vtexier** [duniter/duniter#677]
My identity (vit) has been created at the block number 1965 when I do a lookup: 

```
"meta": {
"timestamp": "1965-C7D6EB3A71314BD9466C5E86C0E10F5363D4A4B43C8F0F4112C00DC42C639F08"
},

```

The hash is weird, it lacks the zeros at the start !

If I look at the block, it is confirmed, the hash (pow) of block 1965 is not the same:

`"hash": "00003332CA7183F54654E90FC68DE7BC3276A80A87263E8B190B35841F68EFEA"`

@Insoleet (inso) identity is wrong as well.

But kimamila identity is good:

wot/lookup/kimamila

```

 "meta": {
            "timestamp": "1132-00041ABB5CF5DBD607A9DCB7748520B2B23D56CBA11FA22671C67287A4CE7EFD"
          },
```

**Comment by c-geek** [comment]
Confirmed.

Solution: consider in the protocol that the blocks versionned 1 to 4 does not need, for their identities, to match a real block hash. Only the number must match an existing block.

For blocks with version 5, however, the hash will have to match.

I'm investigating on how much identities are impacted.

**Comment by c-geek** [comment]
We have 78 identities (on 167 => 46,7%) which have a wrong blockstamp.

You can verify it by yourself using the following SQL statement on your personal node database:

```sql
select i1.*, substr(i1.buid, instr(i1.buid, '-') + 1) bs_hash from idty i1
where bs_hash not like 'E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855' and not exists(
	select * from block where hash = bs_hash
);
```

**Comment by c-geek** [comment]
Note to myself: check if the same bug exists for the other documents.

**Comment by c-geek** [comment]
Checked: it's OK for other documents.
