### ISSUE TITLE
Block spreading through WebSocket not effective

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#678]
I noticed I oftenly had in Sakia a network split into 2 parts when a new block is issued: 

![image](https://cloud.githubusercontent.com/assets/969136/19815388/e3d0f38a-9d42-11e6-96e2-dba0d1c60a00.png)

However if I restart Sakia, I get this screen:

![image](https://cloud.githubusercontent.com/assets/969136/19815399/fa3b855e-9d42-11e6-9c81-e6aaa8eaa2a1.png)

So there is something wrong with network refresh. I first wondered if the problem was coming from Sakia, so I've tested with an ad hoc mirror on TestNet.

And I get the same issue: the new block is not spread correctly through WebSocket all the time by all the nodes, **even if the node did well receive and accepted the block**.

So the problem must come from Duniter.

**Comment by c-geek** [comment]
cc @Insoleet @vtexier @M5oul

**Comment by M5oul** [comment]
Yep, I reproduce it.

**Comment by c-geek** [comment]
Apparently it works very well in the first moments after starting a node.

Let's see how much time is necessary to have the problem coming again.

**Comment by c-geek** [comment]
I could observe that [block#50926](http://cgeek.fr:9330/blockchain/block/50926) was not shared correctly across the network, only few nodes were aware of it.

An hypothesis: the problem has nothing to do with WebSockets, but with `server.js` stream being closed, which has for consequence:

* to stop sharing any data through WS or HTTP API

And more particularly:

* to stop block sharing through WebSockets
* to stop block sharing through HTTP API

This would also explain why I cannot reproduce it after 24 hours.

**Comment by c-geek** [comment]
The hypothesis of closed `server.js` stream seems wrong, as I still see logs like this:

	info: Block #51419 added to the blockchain in 498 ms
	warn: Blockchain changed!
	trace: PoW loops = 899
	info: 95.157.211.148 - POST /blockchain/block HTTP/1.1 200 1592 - 564.026 ms
	debug: Trial = 151, powMin = 74, pubkey = HnFcSm
	warn: Too high difficulty: waiting for other members to write next block
	debug: --> new Block to be sent to 10 peer(s)
	info: POST Block block#51419
	debug:  `--> to peer 7WANX3x3Lv [member] (78.202.22.75:9000)
	debug:  `--> to peer BR5DDeKff8 [member] (107.170.192.122:8999)
	debug:  `--> to peer 8marFcm8bc [member] (37.187.0.204:8999)
	debug:  `--> to peer XeBpJwRLkF [member] (151.80.40.148:8999)
	debug:  `--> to peer J78bPUvLjx [member] (78.227.107.45:8999)
	debug:  `--> to peer 2GF9YTSMdF [member] (duniter.youpeek.net:8999)
	debug:  `--> to peer 4jT89qUKAu [------] (88.174.120.187:9331)
	debug:  `--> to peer CFxAJT7Wqg [------] (88.174.120.187:61637)
	debug:  `--> to peer TENGx7WtzF [------] (88.174.120.187:16120)
	debug:  `--> to peer AZ2JPAUch9 [------] (88.174.120.187:9332)

This means we reach `multicaster.js` stream, itself reached by `router.js` stream, fed by `server.js`.

I'm looking at another lead...

**Comment by c-geek** [comment]
I've tested some code in-production, and have never gotten the problem again. I will integrate this code, hoping the problem is solved.
