### ISSUE TITLE
Missing members in /wot/members

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#679]
When requesting /wot/members  on node `cgeek.fr:9330`, i found missing uid.

My membership uid (kimamila / pubkey=5oc...) seems not present.

**Comment by M5oul** [comment]
I could reproduce: I can't find `kimamila` and his associate pubkey using `wot/members` on my nodes.

There is 170 members:
```bash
curl -s moul.re:8999/wot/members | grep uid | wc -l
170
```

`kimamila` identity is missing?

**Comment by c-geek** [comment]
It's simple: the identity `kimamila` was [excluded on block 50253](http://cgeek.fr:9330/blockchain/block/50253) by lack of membership renewal. On TestNet, membership lasts 6 months only.
