### ISSUE TITLE
In tx/history response, locktime is a string instead of an integer

### ISSUE THREAD

**Issue by vtexier** [duniter/duniter#681]
When I send a transaction document with the python api, the locktime field is an integer.

`{'transaction': 'Version: 3\nType: Transaction\nCurrency: test_net\nBlockstamp: 50925-00000194B666ABB4CCC8814DAC9316B3A5FF47B0E93B049AC27906FC7B8494A8\nLocktime: 0\nIssuers:\nRdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS\nInputs:\n180953:0:D:RdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS:8266\nUnlocks:\n0:SIG(0)\nOutputs:\n180953:0:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)\nComment: \nSy1KOhyRAId1sJ4uenvklAST94ZnlYZpFjjKSSoi1TfghpzqRX1NItL81ruDxWi/S6LsZck3GZFI4RY1gGe1Bg==\n'}`

When I verify my transaction with a tx/history/pubkey request, I get a string for the locktime field:

```
{

    "version": 3,
    "issuers": [
        "RdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS"
    ],
    "inputs": [
        "180953:0:D:RdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS:8266"
    ],
    "outputs": [
        "180953:0:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)"
    ],
    "comment": "None",
    "locktime": "0",
    "blockstamp": "50924-000002DB4482FA508B0ADBB9E7A087F9755C0980C201E003C32C75D73166DAE7",
    "blockstampTime": 1477833155,
    "signatures": [
        "v4AM47sxiaXnww8If/H+ZDBQPRLvxvhm3nKg3SPKggbbq0IUD97PilWYikYoRPKmU5f+W9rQmTnSqOwkN8zNCg=="
    ],
    "hash": "08505A7615F8C8156D1F40CF1661818D3196A6C486E949DFA87B843B3D88E71D",
    "block_number": null,
    "time": null,
    "received": 0

}
```

[Bug is here](https://github.com/duniter/duniter/blob/8225ff2efdc3313036fbf4c62a978370f804e6c9/app/lib/streams/dtos.js#L85)

**Comment by c-geek** [comment]
OK, we just need to replace `String` by `Number` in dtos.js.
