### ISSUE TITLE
Command line to install Duniter desktop with .deb

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#684]
Tu remove (-r) an older version : 

`$sudo dpkg -r duniter-desktop`

To install (-i) a newest version of Duniter with .deb package in command line (example for v0.40.3) : 

`$wget https://github.com/duniter/duniter/releases/download/v0.40.3/duniter-desktop-v0.40.3-linux-x64.deb`
`$sudo dpkg -i duniter-desktop-v0.40.3-linux-x64.deb`

ERROR when updating to v0.40.3 : "SQLITE_ERROR: duplicate column name: revoked_on"

+ terminal messages give information about v0.40.a6 not 0.40.3 I don't know why...

```
~$ duniter-desktop
2016-11-04T14:47:42+01:00 - debug: Plugging file system...
2016-11-04T14:47:42+01:00 - info: Duniter web admin listening on http://localhost:9220
2016-11-04T14:47:42+01:00 - debug: Loading conf...
2016-11-04T14:47:42+01:00 - debug: Loading crypto functions...
2016-11-04T14:47:42+01:00 - debug: Opening SQLite database "/home/bobby/.config/duniter/duniter_default/duniter.db"...
2016-11-04T14:47:43+01:00 - debug: Upgrade database...
2016-11-04T14:47:44+01:00 - error: Error: SQLITE_ERROR: duplicate column name: revoked_on
    at Error (native)
2016-11-04T14:47:44+01:00 - warn: SQLITE_ERROR: duplicate column name: revoked_on
```

**Comment by c-geek** [comment]
Could you make a screenshot?

**Comment by galuel** [comment]
![duniter](https://cloud.githubusercontent.com/assets/5245398/20009623/7cb7014a-a2a5-11e6-92e1-c5533c939fdf.png)

**Comment by galuel** [comment]
![duniter](https://cloud.githubusercontent.com/assets/5245398/20009758/f7c65322-a2a5-11e6-81f1-08fe420c915c.png)

**Comment by c-geek** [comment]
You also said v0.40.a6 was displayed somewhere, could you tell me where?

**Comment by galuel** [comment]
A chaque fois que j'installe une nouvelle version, Ubuntu me dit que c'est la version antérieure qu'il installe...

**Comment by c-geek** [comment]
OK, I reproduce the "v.40.a6" thing about Ubuntu.

But I do not reproduce your SQL error. A workaround: delete the files under `~/.config/duniter/duniter_default/` **BUT** `conf.json` file. Restart Duniter, sync again.

I let the ticket opened.

**Comment by c-geek** [comment]
Linked to #685.

**Comment by galuel** [comment]
I removed ~./config/duniter and then restarted, syncronisation ok, all is ok.

**Comment by c-geek** [comment]
I will also make the unzip phase quiet in next versions, so we can see the installation messages: 79209291acd20c59d3a38ea377767d882c7aef2c.

**Comment by c-geek** [comment]
S'est produit de nouveau: https://forum.duniter.org/t/version-corrective-0-40-3/1389/4?u=cgeek
