### ISSUE TITLE
/wot/lookup/  : Add cert_time into signed identities

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#692]
Je valis finalement avoir besoin de la date de certification dans les "signed", car les certifications en attente ne sont résentes dans wot/certifiers-of/, si l'identité n'est pas membre.

Actuellement, la seule info disponible est la date de l'identité (sigDate), ce qui ne permet pas de déterminer la date de fin de validité (avant écriture) de la certification

**Comment by c-geek** [comment]
Juste pour prévenir : je ne rajouterai que le n° de bloc, pas le "medianTime" du bloc ni le hash, car alors il faut que j'aille les chercher, ce qui surcharge l'appel de lookup déjà très (trop) lourd.

On aura donc comme entrée dans "signed" : 

```json
{
  "uid": "ncharlot",
  "pubkey": "Esp8TnSg58A1Ap7f2RernDqXm3wPDpH6QQtAZhjz72JV",
  "meta": {
    "timestamp": "24483-39EBDC280B89D45D84610765510E00F12063C9E9A2564518E32BE5268C656EEB"
  },
  "cert_time": {
    "block": 24538
  },
  "isMember": true,
  "wasMember": true,
  "signature": "c0WmUp3xuRD5TDihYVe9+Bbz/YbheleIa1I35Sq1voj0wBblEUZe7aenMGesx16DVgTrQMrkt+h7H64BGIM9AA=="
}
```

**Comment by blavenie** [comment]
@c-geek oui, pas de soucis, car je vais déjà chercher le medianTime par requetes annexes.

Merci pour cette prise en compte rapide !
