### ISSUE TITLE
configure duniter-server using the comand line wizard 

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#696]
I try to configure a node from duniter-server (.deb) package.

when i run : 

```
duniter wizard network
```
I choose a value for network. But then the process freeze:
```
2016-11-09T12:10:23+01:00 - debug: Plugging file system...
2016-11-09T12:10:23+01:00 - debug: Loading conf...
2016-11-09T12:10:23+01:00 - debug: Loading crypto functions...
2016-11-09T12:10:23+01:00 - info: Checking UPnP features...
? IPv4 interface eth0 192.168.0.5
```
The second question is never display...

**Comment by M5oul** [comment]
Reproduced on my side.

**Comment by c-geek** [comment]
The inquirer.js module was upgraded and I've made my tests with the old one. Reproduced with the real version.

**Comment by c-geek** [comment]
As a workaround, you can use the `config` command and its options. The easiest way is to use `config --autoconf`, or use the UI.
