### ISSUE TITLE
The block version number is not well controlled

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#697]
TestNet upgraded to DUP 0.5 few minutes ago, and we were surprised that *even 0.40 nodes* accepted the V5 block.

This must be a bug in the version acceptance, the nodes probably accept any version whereas they **should not**.

**Comment by M5oul** [comment]
Why did this didn't happen migrating from protocols versions 0.3 –> 0.4?

**Comment by c-geek** [comment]
It probably happened. But since there was a WebSocket issue, we were in the fog of Sakia not showing the exact state of the nodes. Addded the fact it was not a programmed migration, we also had a lot of forks which added a lot of complexity.

So it was there, we haven't seen it.

**Comment by c-geek** [comment]
The version is well controlled when coming from HTTP API, but not when pulled by the node. That's where the flaw comes from.
