### ISSUE TITLE
Installing 0.50.0 still 0.40.0a6 shown !?

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#702]
`~$ sudo dpkg -i duniter-desktop-v0.50.0-linux-x64.deb
Sélection du paquet duniter précédemment désélectionné.
(Lecture de la base de données... 840440 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de duniter-desktop-v0.50.0-linux-x64.deb ...
Dépaquetage de duniter (0.40.0a6) ...
Paramétrage de duniter (0.40.0a6) ...
Traitement des actions différées (« triggers ») pour bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Traitement des actions différées (« triggers ») pour gnome-menus (3.13.3-6ubuntu3.1) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.22-1ubuntu5) ...
Traitement des actions différées (« triggers ») pour mime-support (3.59ubuntu1) ...
`

**Comment by c-geek** [comment]
What if you do it again?

**Comment by galuel** [comment]
I did it yet...

**Comment by c-geek** [comment]
OK, I think I got it.

We will see this in 0.50.1, next week.

**Comment by c-geek** [comment]
Fixed as of 0.50.1a2
