### ISSUE TITLE
Duniter 0.50 not working

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#703]
After installing Duniter 0.50 on another PC (my laptop) with dpkg -r duniter and then dpkg -i duniter-desktop-v0.50.0-linux-x64.deb

The button "get back to previous screen" doesn't work. See screen capture.
![duniter](https://cloud.githubusercontent.com/assets/5245398/20205056/d4422d2e-a7d5-11e6-8912-5abb5dec6682.png)

**Comment by galuel** [comment]
Installed 0.40.3 it works. Then installing again 0.50.0 seems to work (probably config folders were created by 0.40.3 and not by 0.50.0). But then I can see only my own peer in the network. One single peer...

**Comment by galuel** [comment]
Trying to reset the node with automatic configuration give again only one peer in the network. But then reseting the node with manual configuration on cgeek.fr:9330 give good results, I can see many peers now in Duniter.

**Comment by galuel** [comment]
And now I can see my node on both Cesium and Sakia ! So installation of 0.50.0 need to install first 0.40.3, and then only manual configuration of the connexion to the network (chosen peer to connect to), and then it's ok.

Need a special information on this procedure, or we can consider it is a bug !? ;)

**Comment by c-geek** [comment]
Kined to #710
