### ISSUE TITLE
Difficulty 79 shown in /blockchain/difficulties

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#713]
This value makes no sense, as said in https://github.com/duniter/duniter/issues/569#issuecomment-260368934

For example, we can see such a difficulty when a node HEAD is 53684.

**Comment by M5oul** [comment]
Ah, it's impossible to have a difficulty of 79?
It can only be 78, then 80.
Same for every zero augmentation in the hash?

**Comment by c-geek** [comment]
Same for every number before a multiple of 16: 15, 31, 47, 63, 79, 95, ...

**Comment by M5oul** [comment]
Wow, funny!
That would explain many things
And why I had difficulties to found a great formula for my explanations on https://github.com/duniter/duniter/issues/569.
Furthermore, PoW computation on Silkaj needs to be reviewed: https://github.com/duniter/silkaj/issues/15.

**Comment by c-geek** [comment]
Note how it's not "impossible", but there is no difference between 15 and 16 in terms of PoW hardness, that's why I make a jump and why Duniter `PowMin` is a linear function: if you don't jump, you don't change difficulty.

**Comment by c-geek** [comment]
I've found the cause, here is the explanation: for personalized difficulty, I had the following code:

```js
if (personal_diff + 1 % 16 == 0) {
 personal_diff++;
}
```

So if personal_diff = 79, the actual test is:

```js
if (79 + (1 % 16) == 0) {
 personal_diff++;
}
```

Which of course, returns false, because 80 != 0. So 79 is not incremented to 80.

The fix is to put brackets around `personal_diff`:

```js
if ((personal_diff + 1) % 16 == 0) {
 personal_diff++;
}
```

-----

I wondered if the blockchain `PowMin` value has ever been 79 due to this bug. Actually: no, because I luckily wrote the good code for this part:

```js
if ((previous.powMin + 2) % 16 == 0) {
  // Avoid (16*n - 1) value
  resolve(previous.powMin + 2);
} else {
  resolve(previous.powMin + 1);
}
```

However, it may explain a bit #633 some times because `PowMin` could equal `80` and `personal_diff` could equal `79`, which would be equivalent to a proof `00001*` in Duniter code (it is not correct, I know, it should be `00000*` but this case was not supposed to exist, so I [arbitrarily decided it would be equivalent to 78](https://github.com/duniter/duniter/blob/659c4accf01d15aae978646214f7d78a82d50c25/app/lib/constants.js#L288)). But of course if PowMin is 80, and we propose a proof with level 78, the block is rejected.
