### ISSUE TITLE
Bug on PoW?

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#714]
```bash
2016-11-16T12:10:22+01:00 - warn:  Error: Wrong proof-of-work level: given 4 zeros and '1', required was 5 zeros and an hexa char between [0-9A-F]
    at Error (native)
    at /opt/duniter/sources/app/lib/rules/global_rules.js:83:13
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
```

**Comment by M5oul** [comment]
It's seems there is a bug to join main branch.
I switched my node to 0.50.0 as it seems no consensus is happening with 0.50.1 nodes.
And branches from 0.50.1 nodes seems stucked.

**Comment by M5oul** [comment]
Finally, it was global sync process which didn't bring on main branch when syncthing on main branch.
Then, I checkout 0.50.0, global sync to main branch, checkout 0.50.1, then it's ok!

**Comment by M5oul** [comment]
My node experimented a fork on tag v0.50.1 and didn't want to join back main branch wĥen reverting blocks with upper logs errors.
I finally checkout on tag v0.50.0 :smirk_cat:

**Comment by c-geek** [comment]
A 0.50.2 is on its way.
