### ISSUE TITLE
conf.json contiens des secrets génant en clair

### ISSUE THREAD

**Issue by GammaNu** [duniter/duniter#716]
Lorsque je crée un noeud duniter, dans sa configuration, si je veux pouvoir calculer des block, je dois m'authentifier en tant qu'utilisateur du réseau, donc avec mes salt et passwd. Ceux-ci sont stocké en clair dans conf.json au lieu de n'y stocké que les données dérivée (qui sont stocké aussi)
Si je les supprime alors que la partie pair est généré, au lieu de se servir des infos en pair, un salt et passwd aléatoir est généré, et les clefs dérivés sont écrasées pour de nouvelles a partir des identifiants aléatoire.

```
{
"salt": "monId",
 "passwd": "monMotDePassEnClair",
"pair": {
  "pub": "maClefPublic",
  "sec": "maClefPrivée"
 }
}
```

**Comment by M5oul** [comment]
Linked to https://github.com/duniter/duniter/issues/233.
