### ISSUE TITLE
lors de la  re-synchronisation de mon noeud, message : dao.getRemoteBlock is not a function

### ISSUE THREAD

**Issue by gege53** [duniter/duniter#733]

**Comment by M5oul** [comment]
Es-ce que tu peux copier les logs ici ?
Es-ce que ça bloque la re-synchronisation ?

**Comment by gege53** [comment]
depuis j'ai vidé les répertoires et tout réinitialisé, par contre depuis ce matin le noeud est décalé ce soir il est au bloc 57803 alors que les noeuds sont à 57818

**Comment by M5oul** [comment]
Oui, le fait que les nœuds ne rejoignent pas la branche principale est un [bug connu](https://forum.duniter.org/t/etat-du-reseau-0-5/1452).

Essaye de rester synchronisé sur la branche la plus avancée.
Ce problème sera corrigé plus tard.

**Comment by gege53** [comment]
si je lance la synchro sans avoir fait 
>cd~
> cd .config
> rm -rf duniter

est ce la bonne manip car à chaque fois il faut refaire salt et passwd

**Comment by M5oul** [comment]
Tu peux faire :
`duniter reset data`
Ça supprimera les données et ça conservera la configuration du nœud (réseau et identifiants).

**Comment by gege53** [comment]
ok

Merci le noeud est à 57818 ...

**Comment by gege53** [comment]
je viens de réinitialisé mon noeud mais idem (pour info je suis bien en .50.2) en faisant la synchro sur duniter.org:8999 j'ai recommencé une 2eme fois sur cgeek.fr:9330 : ok

**Comment by Smyds** [comment]
J'ai eu le même problème "dao.getRemoteBlock is not a function" lors de la synchronisation (quelque soit le nœud auquel j'essaie de me synchroniser). Après un "duniter reset data" la synchronisation refonctionne.
