### ISSUE TITLE
error "tx already processed" use a generic ucode=1002

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#758]
Dans Cesium, j'ai voulu détecter l'erreur "tx already processed" pour en avoir une gestion particulière dans mon code. J'ai utilisé le code "1002" qui semblait etre associé à l'erreur. Mais je m'aperçois que celui-ci est utiliser pour d'autres erreurs.

Par exemple j'ai obtenu (en 0.60.0) l'erreur suivante, avec le même code 1002 : 

```json
{
  "ucode": 1002,
  "message": "Cannot read property '$null' of null"
}
```

Demande : avoir un code spécifique pour l'erreur "tx already processed"

**Comment by c-geek** [comment]
Oui en effet, le code 1002 est un code erreur [générique](https://github.com/duniter/duniter/blob/48e332e83a456cf911ff7631fbe760c597a110d6/app/lib/constants.js#L57).
