### ISSUE TITLE
membership IN > received by node, but not visible in  /wot/requirements

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#769]
[MichelDuchemin](http://cesium.duniter.fr/#/app/wot/6JmSvsQV849mqvnX14GkiKF5mbUt6Q3McGDpqV4quCCa/VEUILLE%20%3Cem%3EMichel%3C%252Fem%3E) (pubkey `6JmSvsQV849mqvnX14GkiKF5mbUt6Q3McGDpqV4quCCa`)
sent a membership IN (using Cesium). It has been received by node (Cesium received the acknowledge without error), but is not visible in [/wot/requirements](http://cgeek.fr:9330/wot/requirements/6JmSvsQV849mqvnX14GkiKF5mbUt6Q3McGDpqV4quCCa) (`membershipPendingExpiresIn` = 0):

```json
{
  "identities": [
    {
      "pubkey": "6JmSvsQV849mqvnX14GkiKF5mbUt6Q3McGDpqV4quCCa",
      "uid": "MichelDuchemin",
      "meta": {
        "timestamp": "63240-00000CAE3FE7D47DA09727369D21116DF284936CA1BDD95473724B124D86E197"
      },
      "expired": true,
      "outdistanced": false,
      "certifications": [],
      "membershipPendingExpiresIn": 0,
      "membershipExpiresIn": 0
    }
  ]
}
```

**Comment by blavenie** [comment]
je viens de comprendre : à priori, c'était que ``"expired": true``

Mais est-ce normal que le noeud ne renvoi pas d'erreur, quand une adhésion utilise une IDTY expirée ?

**Comment by c-geek** [comment]
L'identité peut être périmée, l'adhésion est tout de même valide isolément. Alors oui, on pourrait dire que dans ce cas Duniter renvoie une erreur "adhésion sur une identité devenue obsolète". Mais bon, l'info se trouve déjà dans `/wot/requirements`, donc pour le moment je laisse comme cela.

Éventuellement, il sera possible de faire cette amélioration plus tard.

**Comment by blavenie** [comment]
je ferme. c'est résolu coté Cesium.
Désolé du dérangement ;)
