### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#781]
After db reset.
For a global sync, it stays stuck at:
```bash
Download: [||||||||||||||||||||] 100 %
Apply:    [                    ] 0 %

Status: Getting chunck #280/280 from 70000 to 70188 on peer raspi3.cgeek.fr:8999```
```

And the address is changing:
```bash
testnet.duniter.tednet.fr:89
cgeek.fr:9330
testnet.vincentux.fr:899
…
```

**Comment by c-geek** [comment]
Please use the releases at https://github.com/duniter/duniter/releases.

You are having this error because you are building from sources (either dev or master) which is currently not compliant with TestNet.

**Comment by c-geek** [comment]
Or you can select `0.80` branch to build from sources.

**Comment by M5oul** [comment]
It works.
Thanks.

**Comment by modulix** [comment]
Sorry, but i have the same issue as M5oul.
I'm trying to sync for days after a "reset data", and stay always in a for ever loop on the last part of the blockchain. I'm on the master branch of github using "test_net" currency. I'have already tried a "wizard network" without success. Help, please.

**Comment by c-geek** [comment]
@modulix Have you selected the `0.80` branch?

    git clone https://github.com/duniter/duniter.git
    cd duniter
    git checkout 0.80
    yarn
    bin/duniter reset data
    bin/duniter sync cgeek.fr 9330

**Comment by modulix** [comment]
No, i'm on "master" one (by default).
Ok, i'm going to swith to 0.80

**Comment by modulix** [comment]
Cool, seems work, my node is applying... Thank's a lot for a so fast resolution !

**Comment by c-geek** [comment]
Np, thanks for testing :smile:
