### ISSUE TITLE
'webstart' & 'webrestart' cmds do not works

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#796]
The daemon is stopped may be due to an issue with the web admin:

```bash
duniter.sh webstart
Starting duniter_default daemon...
duniter_default daemon stopped.
```

```bash
duniter.sh webrestart
Stopping duniter_default daemon...
duniter_default daemon stopped.
Starting duniter_default daemon...
duniter_default daemon stopped.
```

**Comment by M5oul** [comment]
```bash
duniter.sh webrestart
Stopping duniter_default daemon...
duniter_default daemon stopped.
Starting duniter_default daemon...
duniter_default daemon stopped.
```

**Comment by c-geek** [comment]
Please give the Duniter distribution (server, ARM, desktop?) to give the context of the bug.

Anyway, you could try some alternatives:

* use the `--webmhost` and `--webmport` options to change the host and port for the WebUI

**Comment by M5oul** [comment]
It happen on the ARM build and on using `git` version (server one) on my desktop computer.

**Comment by M5oul** [comment]
Ok, on my `git` version, the web-ui should be well installed as this options `--webm{port,host}` do not exist.
I tryed to reinstall npm dependencies.
Strange, `duniter-ui` [is not here](https://moul.re/zerobin/?1bfea948d7d300a8#kH6RlranTbT6kiSDN+trnc9ZMBaLa/hbcSdjpVF+EsY=).

**Comment by c-geek** [comment]
Yes, because from now on, the UI is optionnal. It is a duniter module. You can add it using the following command:

    npm install --save duniter-ui

From that moment, you will have new options (`--webmhost` and `--webmport`) and new command (`webstart`) available.

**Comment by M5oul** [comment]
Ok, thanks.
I could install `duniter-ui` and make it works without `--webm{host,port}` options.
