### ISSUE TITLE
CLI wizard network > remoteipv4 cannot be cleaned ?

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#807]
In my node (gtest.duniter.fr:10900), when i clean `remoteipv4` (field using `wizard network` or directly in `conf.json`), it appears again, but with value of `ipv4` (a local address like `192.168.0.x`).

Then [network/peering](http://gtest.duniter.fr:10900/network/peering) show this local IP as remote IP...

Duniter : 0.90.3

**Comment by c-geek** [comment]
Which explains why I've seen this for gerard94 as well.

**Comment by c-geek** [comment]
Fixed by duniter/duniter-bma@6bcffccae28923f477f8a55542219b7dfd80912d.
