### ISSUE TITLE
One source seems to be missing

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter#811]
Hello,

It seems that one source is missing from my url /tx/sources : 

http://gtest.duniter.org:10900/tx/sources/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

I cannot find this one : 
Identifier : "8C61C877D5DACB4EA6CE41C87490FA5A1181B2FD9782E841DCC6DD11E4E24E9C"
Offset: "0"
Type : "T"
Amount : "20"
Base : "0"

Whereas sakia cannot finds a transaction where it would have been parsed. Could you help me investigate ?

**Comment by c-geek** [comment]
This source was consumed by in this block: http://cgeek.fr:10900/blockchain/block/341

Consumed source a trimmed from the database, so it no more exists.

**Comment by Insoleet** [comment]
If I understand correctly it is not the same source : 

http://cgeek.fr:10900/blockchain/block/341

```
"received": [
      {
        "version": 10,
        "issuers": [
          "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk"
        ],
        "inputs": [
          "8600:0:T:289E9F9868209FB5D48CCFE8EB6AC52AEDEFA689EB3EEC7A906D9C687FF38FEC:1"
        ],
        "unlocks": [
          "0:SIG(0)"
        ],
        "outputs": [
          "20:0:SIG(8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)",
          "8580:0:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)"
        ],
        "comment": "Hop quelques centimes de G",
        "locktime": 0,
        "blockstamp": "321-00008EA137E75C0B13F405ED71411C47AD5AA3AE726F27AC48D1421F11C5B64B",
        "blockstampTime": 1485257015,
        "signatures": [
          "3w5+Jr5pn2/GG12OewGIW03fQW4k5iIXqXtwVGfkOCrn38KMxwp4gOCnUgMlos3+7mgm3b3UdgpPUI9FcHwsAA=="
        ],
        "hash": "8C61C877D5DACB4EA6CE41C87490FA5A1181B2FD9782E841DCC6DD11E4E24E9C",
        "block_number": 323,
        "time": 1485257468,
        "received": 0
      },
```

There are two outputs : 
```
          "20:0:SIG(8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)",
          "8580:0:SIG(HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk)"
```

In the lock 341, the source consumed is the output of 8580 amount.

**Comment by c-geek** [comment]
Indeed, I gave you the consumption of `8C61C87..:1`. You ask me about `8C61C87..:0`.

I'm trying to find it, but surprisingly, I do not find it...

**Comment by c-geek** [comment]
So this is a major bug, since it locks low amounts. A software update will be necessary.
