### ISSUE TITLE
From 0.90.4 to 0.90.5

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#821]
I left my PC running 0.90.4 with 8 blocks made at 17h00, when I returned I was disapointed : always 8 blocks... at 23h40

Then, I saw 0.90.5 new version, I installed it, and it shows me 15 blocks made... So I guess there is a refresh issue somewhere...

**Comment by c-geek** [comment]
Fixed by https://github.com/duniter/duniter/commit/a613ea6d42b148ae9c4d94c2e6d09327245d6ef3
