### ISSUE TITLE
Duniter 0.90.5 Cesium refresh issue !?

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#822]
After installing Duniter 0.90.5 launching wallet gives old Cesium 0.90.7 and not Cesium 0.90.18. Probably a refresh issue !? There is no refresh button, and F5 doesn't make anything, so how to refresh to be sure we have the good embeded version !?

- I suggest to put somewhere a link to show the Duniter Desktop directly in the browser (localhost:9090 ?) as well as the Cesium embeded wallet. Perhaps in the menu "i" with a "?" help submenu. http://localhost:9220
- It seems the embeded Cesium version in Duniter 0.90.5 is Cesium 0.90.7 and not 0.90.18

**Comment by c-geek** [comment]
Fixed by https://github.com/duniter/duniter/commit/a613ea6d42b148ae9c4d94c2e6d09327245d6ef3
