### ISSUE TITLE
Revocation doc not processed

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#832]
I tried to revoke my identity, but this is not working...

Document sent:
```Version: 10
Type: Revocation
Currency: gtest
Issuer: 5ocqzyDMMWf1V8bsoNhWb1iNwax1e9M7VTUN6navs8of
IdtyUniqueID: kimamila
IdtyTimestamp: 0-E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
IdtySignature: KbQW0EnIVPzDmg7NOPuFd5qE667QLqEpEK+MIfQyy3PIsL0lV0yMG+vesyPlSnCjgCmtEX0Cv6s1FCa+U06yBg==
YpF7VkuMiMGiKbaSI/aj2H0/ZuzFkLuUB30OkYSH0J/mbWzCES2EbJVBv/lw3vQQc/XRiCN4DbmfigJAiIi+BA==
```

node response:
```
{
  "result": true
}
```

Using the blockchain explorer, I see that [there no revocation done](http://gtest.duniter.fr/#/app/blockchain/search?q=_exists_:revoked) in gtest...  we need to test it to be sure.

**Comment by b3j0f** [comment]
Maybe your revocation will be done after the blockchain synchronisation ?

**Comment by c-geek** [comment]
Yes that's probably the problem: the revocation was sent to `gtest.duniter.org:10900` or another node, but it wasn't shared with member nodes. So it has never been included in a block.

I've tried locally, and my node is ready to fire me :grin: 

So I have a bug: a revocation is not broadcasted!
