### ISSUE TITLE
Avoid TX to himself (without any change)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#833]
See this TX : http://gtest.duniter.org:10900/blockchain/block/4722

inso (key EHRCKQn8Tua39rRkMtvaj5tpFGcg7yeKyr8S9fJnVKwE) has sent one input to one output (same unitbase).

This is like pure noise ;) Why not to exclude such TX ?

**Comment by c-geek** [comment]
The nodes may refuse it, but it respects the protocol and, even if I don't see why such a transaction would be made, I think someone can judge it useful.
