### ISSUE TITLE
duniter config --keyprompt problem

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#841]
`duniter config --keyprompt` generate a wrong pubkey putting my credentials.
Doing it from webadmin, the pubkey is good.

**Comment by c-geek** [comment]
In the [readme file](https://github.com/duniter/duniter-keypair#cli-options), you can see that `--keypromp` does not store the derived key.

You have to use `wizard key` for this.

**Comment by M5oul** [comment]
Ok.
