### ISSUE TITLE
Je suis encore membre alors que mes certifications recus ont expiré

### ISSUE THREAD

**Issue by Tortue95** [duniter/duniter#842]
Hello, 

j'ai remarqué que je suis considéré comme membre alors que j'ai perdu mes certifications
(aujourd'hui il ne m'en reste qu'une)

l'on peut voir mon état `IsMember=True` [ICI](http://gtest.duniter.org:10900/wot/certifiers-of/Tortue)
j'ai donc reçu mon DU et la possibilité de signer des blocs: [exemple ici](http://gtest.duniter.org:10900/blockchain/block/8668)

Bon debug !

**Comment by c-geek** [comment]
En effet, tu aurais dû être exclu au bloc#8468, donc, approximativement il y a 1 jour.

La faute à la règle [`BR_G95`](https://github.com/duniter/duniter/blob/master/doc/Protocol.md#br_g95---exclusion-by-certification) qui est incorrecte. En effet, la règle compte les certifications actuellement valides via : 

    COUNT(GLOBAL_CINDEX[receiver=CERT.receiver])

Or cette instruction retourne toutes les certifications reçues, même celles périmées. Une instruction correcte devrait se focaliser sur celles encore valides : 

    COUNT(REDUCE_BY(GLOBAL_CINDEX[receiver=CERT.receiver], 'issuer', 'receiver')[expired_on=0])

Mais *en plus*, il y avait un second bug : la règle requérant l'exclusion ([`BR_G86`](https://github.com/duniter/duniter/blob/master/doc/Protocol.md#br_g86---excluded-to-be-kicked)) n'était pas appliquée, la faute à un `yield` manquant.

Les corrections sont déjà réalisées, il ne me reste plus qu'à verrouiller cela avec un TU, faire une release et préciser aux utilisateurs de rebrancher leur nœud sur une blockchain valide.
