### ISSUE TITLE
/wot/requirements  expired=false but membershipExpiresIn=0

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#854]
On [this identity](http://gtest.duniter.org:10900/wot/requirements/F9m6KBE9qeNqL6rjQrWxbk9y7GwTuAzwvx6CUnczkFYR) (Paulart), `wot/requirements` returns :

```json
{
  "identities": [
    {
      "pubkey": "F9m6KBE9qeNqL6rjQrWxbk9y7GwTuAzwvx6CUnczkFYR",
      "uid": "Paulart",
      "meta": {
        "timestamp": "318-00000922B1C89DEEB766A03563F810225DA3F7D047629BB833C37064C2218917"
      },
      "revocation_sig": null,
      "revoked": false,
      "revoked_on": null,
      "expired": false,
      "outdistanced": false,
      "isSentry": false,
      "certifications": [
        {
          "from": "DAi1xsc1r9q92QZtpKW1U5AJJLca3pRqfASLTBgftoKx",
          "to": "F9m6KBE9qeNqL6rjQrWxbk9y7GwTuAzwvx6CUnczkFYR",
          "expiresIn": 624217
        },
        {
          "from": "ERQJAWCvDoDus3tzUuz8vZ2jutEiZ1z4UZhYxBbbEr9T",
          "to": "F9m6KBE9qeNqL6rjQrWxbk9y7GwTuAzwvx6CUnczkFYR",
          "expiresIn": 797144
        },
        {
          "from": "8marFcm8bcGn3p9r4356VP8anV6UVbHVcudvW97c2a7o",
          "to": "F9m6KBE9qeNqL6rjQrWxbk9y7GwTuAzwvx6CUnczkFYR",
          "expiresIn": 1238431
        },
        {
          "from": "2zcSdoEj1VEeRBqFooNBZW5XhzbuzyoqAUcvaVc61G4H",
          "to": "F9m6KBE9qeNqL6rjQrWxbk9y7GwTuAzwvx6CUnczkFYR",
          "expiresIn": 1336737
        }
      ],
      "membershipPendingExpiresIn": 0,
      "membershipExpiresIn": 0
    }
  ]
}
```

=> I don't understand why `isExpired=false`, if `membershipExpiresIn=0`
Is this member expired or not ?

**Comment by c-geek** [comment]
`expired` means "expired in sandboxes"

Paulart has been a member once, so he will forever have `expired: false`. But `membershipExpiresIn = 0` means he is not a member, because he has no membership that could expire.

**Comment by blavenie** [comment]
ok, je vois.
Cepedant, un compte qui aurait fait une demande d'adhésion, mais qui ne l'a pas obtenu, aura le même `/wot/requirements` d'un compte qui a été membre mais dont l'adhésion est expirée, non ?

J'ai le problème actuellement sous Gtest : mon compte `kimamila` est expirée, et celui de `gab` a exactement le même état. Comment faire pour indiquer, sous Cesium, que `kimamila` doit renouveller, alors que `gab doit adhérer` ?

**Comment by c-geek** [comment]
De façon un peu détournée : si l'URL `/wot/certifiers-of/` renvoie un résultat (même vide), alors il s'agit d'un ancien membre. Si une erreur est renvoyée, il s'agit à coup sûr d'une identité inconnue en blockchain.

Je vais en tout cas ajouter un champ "wasMember" dans /wot/requirements.

**Comment by blavenie** [comment]
> Je vais en tout cas ajouter un champ "wasMember" dans /wot/requirements.

Un truc qui fera gagner du temps à Cesium, c'est d'avoir le nombre de certification en attente, dans /wot/requirements.
Actuellement, je récupère cela auprès de /wot/lookup, en faisant plein de croissement... un peu barbare... (bon c'est hors sujet vis à vis de ce ticket, je peux en créer un autre)

**Comment by c-geek** [comment]
Oui crées un autre ticket stp.
