### ISSUE TITLE
dal.getBlockByBlockstampBuggy is not a function while trying to sync with v0.90.9

### ISSUE THREAD

**Issue by mmpio** [duniter/duniter#861]
I get this error when I try to sync from v0.90.9

```
Progress:

Download: [||||||||||||||||||||] 100 %
Apply:    [                    ] 0 %

Status: dal.getBlockByBlockstampBuggy is not a function
All done.

```

**Comment by c-geek** [comment]
Are you using a release package, or is it a developing environment?

**Comment by mmpio** [comment]
I'm using the developper environment and launch it using
```
./duniter start
```
within the duniter/bin folder

**Comment by c-geek** [comment]
OK, I suggest you to fetch the last changes from git + upgrade your packages using `yarn upgrade`, and try again. I've made several fixes this morning.

**Comment by c-geek** [comment]
Maybe you don't even need to fetch the git changes, you probably have a too old `duniter-crawler` dependency.

**Comment by mmpio** [comment]
`yarn upgrade` did the trick. I was using npm until now.
