### ISSUE TITLE
Full sync on ARM board takes too much time

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#862]
With Ğtest, with almost 10.000 blocks, synchronization takes at least one hour.
Download is very fast, but blockchain check takes too much time.
Only one process is running on one CPU core and it's not taking all core available load.
It's between 30 and ~70 %.

**Comment by c-geek** [comment]
I understand it is « long », but not « too long ».

Maybe I will do something about it, but not yet.

**Comment by M5oul** [comment]
Yep, in fact, corrected.

**Comment by c-geek** [comment]
Note to me: havea look to the PM @jytou sent to me about SQL queries diagnostic.

**Comment by c-geek** [comment]
Rewritten to #908.
