### ISSUE TITLE
Do not store keypair in the conf.json file, but in an external one

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#882]
In a keypair.yml, it would be OK.

**Comment by galuel** [comment]
Don't store the keypair ! Encrypt the keypair and launch duntier with decrypt code. duniter -decrypt xxxx start

**Comment by c-geek** [comment]
Also see https://forum.duniter.org/t/clef-derive-pour-emettre-dans-la-blockchain/2349/4

We can store the keypair, either clearly or encrypted (depends on the user's choice). Default could be clear in a first step, and encrypted in a second step.

Because if the key in encrypted and we do not have the decryption code, Duniter should be waiting for it, and we need to imagine a way (or several) to give the decryption code.

For instance some nodes are started using the UI, so only the UI could ask for the decryption code. It requires some UI developments.

**Comment by c-geek** [comment]
Done. For encryption, see #943.
