### ISSUE TITLE
Installation optimisation

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#884]
duniter webtstart avec une icône qui lance le navigateur sur localhost:9220 devrait pas peser plus que 82 MB...et fait tout ce que fait duniter-desktop qui pèse 128 MB soit 56% de plus !

duniter-desktop me semble donc une release inutile et lourde, la version de base avec l'option webstart contient tout le nécessaire, on pourrait donc : 

- ne plus avoir de version "desktop" mais une seule version à installer
- livrer simplement une icône de lancement qui contienne la commande : 

`duniter webstart && firefox localhost:9220`

ou équivalent...

**Comment by c-geek** [comment]
Linked to #933 #934 #935 #936

**Comment by c-geek** [comment]
Duniter is a bit lighter now, some other improvements to come for next version.

**Comment by c-geek** [comment]
Les versions pour bureau font désormais 75Mo, tandis que la version serveur fait 35Mo.

J'estime que le poids est acceptable, je ferme le ticket.
