### ISSUE TITLE
/wot/requirements : add pending cert count

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter#892]
Un truc qui fera gagner du temps à Cesium, c'est d'avoir le nombre de certification en attente, dans `/wot/requirements`.

Actuellement, je fais cela par `/wot/requirements` + `/wot/lookup`, en faisant plein de tri d'identité, croissement, etc... (un peu barbare)
Alors que mon besoin est uniquement d'avoir le nombre de ces certifications, pour alimenter ce compteur : 

![image](https://cloud.githubusercontent.com/assets/5269556/23938850/567e196c-095e-11e7-89ca-3e715405b817.png)

Je l'ai fait pour la page 'identité', mais pas pour "Mon Compte", qui charge déjà beaucoup de chose...
Du coup l'information n'est pas identique suivant les page. La raison est que beaucoup d'info de lookup me sont inutiles dans "Mon Compte"... 

bref, si c'est possible tant mieux.. sinon tant pis ;)

**Comment by blavenie** [comment]
D'ailleurs, dans `/wot/requirements` l'information sur les certifications recues et acceptables (actuellement dans l'attribut `certifications`) pourraient aussi etre un count, non ?
A priori c'est redondant avec `/wot/certifiers-of` ?

EDIT: a non il y en a moins dans `/wot/requirements` (seulement les validées ?). alors que `/wot/certifiers-of` les a toutes. Enfin je sais pas...

**Comment by c-geek** [comment]
Il n'y a que celles inscriptibles immédiatement, c'est différent.
