### ISSUE TITLE
Add /tx/sources_with_pending

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#896]
@Tortue95 commented on [Wed Mar 15 2017](https://github.com/duniter/duniter-bma/issues/1)

Hi,
it is possible to add a new page (ex:  /tx/sources_with_pending/<pubkey>
who return all sources with the Pending transactions.

This permit to create a simple client to send transaction.
Because today we need to parse the /tx/history to recreate this information.

Thanks

**Comment by c-geek** [comment]
I don't promise you it will be for next release, but I will try.

**Comment by blavenie** [comment]
> Because today we need to parse the /tx/history to recreate this information.

Why not use `/tx/sources` + `/tx/history/:pubkey/pending` [like in Cesium](https://github.com/duniter/cesium/blob/master/www/js/services/bma-services.js#L344) ?

**Comment by Tortue95** [comment]
thanks, yes  i used `/tx/history/:pubkey/pending`, 

But i need parse "`sending`" , "`receiving`" and "`pending`" to get all pending sources
Because sometimes one transaction is shown on only one category.

Today all is good for me, you can close it if you want.
