### ISSUE TITLE
Requests on /wot/lookup/

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#911]
With Silkaj, a request on /wot/lookup/existing_identity pass. la requette passe.
Therefore, a request on /wot/lookup/non_existing_id, there is following error:
- [Python 3.5 can not open a url- error (http 403)](https://stackoverflow.com/questions/38679113/python-3-5-can-not-open-a-url-error-http-403)
- [Python 3.4 urllib.request error (http 403)](https://stackoverflow.com/questions/28396036/python-3-4-urllib-request-error-http-403)

The solution is to modify the user-agent to make it works.
I could do it on Silkaj side, but it would be better, if possible, to fix it on Duniter BMA side.

**Comment by M5oul** [comment]
Finally, changing user-agent doesn't work.
I don't know why.

**Comment by c-geek** [comment]
When I make the following request in my web browser: https://g1.cgeek.fr/wot/lookup/gezgrhhr

I get a 404 HTTP error, not a 403, with a JSON answer.

If I do the same with `curl`, I get the JSON answer as well.

The problem seems specific to your agent, it would be better fixed in your own program.

**Comment by M5oul** [comment]
Ok.
I encounter 404 error, not 403 as mentioned on upper links.
Thanks, I bypassed the problem.
