### ISSUE TITLE
Update dependencies for main and modules repositories

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#914]

**Comment by M5oul** [comment]
Pull requests:
- [duniter](https://github.com/duniter/duniter/pull/915)
- [duniter-prover](https://github.com/duniter/duniter-prover/pull/2)
- [duniter-crawler](https://github.com/duniter/duniter-crawler/pull/1)
- [duniter-bma](https://github.com/duniter/duniter-bma/pull/3)
- [wotb](https://github.com/duniter/wotb/pull/8)
- [duniter-keypair](https://github.com/duniter/duniter-keypair/pull/1)
- [duniter-ui](https://github.com/duniter/duniter-ui/pull/24)

**Comment by M5oul** [comment]
All tests passed excepted for duniter-ui and wotb.

**Comment by c-geek** [comment]
Please do not merge any of this PRs, I need to carefully check each one of these.

There is no emergency to merge them.

**Comment by M5oul** [comment]
Yep, for sure. I won't merge them.
I don't know the implications and can't test them except for `duniter` repository.

**Comment by c-geek** [comment]
I've updated all the modules. However, `ws` dependency update makes duniter tests fail.

If you really want to update this module, please find what is going on using these commands:

    git clone https://github.com/duniter/duniter.git
    git clone https://github.com/duniter/duniter-bma.git
    cd duniter-bma
    sed -i "s/1.1.1/2.2.2/g" package.json
    yarn
    yarn link
    cd ../duniter
    sed -i "s/1.1.1/2.2.2/g" package.json
    yarn
    yarn link duniter-bma
    node node_modules/mocha/bin/mocha --recursive test/ --grep HTTP

Note: please make another issue for this problem.
