### ISSUE TITLE
Show an explicit error when port already in use

### ISSUE THREAD

**Issue by jytou** [duniter/duniter#919]
I tried the following:

    python -m SimpleHTTPServer 9220

Then:

    duniter webstart

The process starts and shows no error (even gives a daemon PID which of course disappears almost instantly since it cannot reserve the port).

The same thing happens when capturing the port for the agent (10901 for instance) before launching a "duniter start", on the console, everything looks fine:

    $ duniter start
    Starting duniter_default daemon...
    duniter_default daemon started. PID: 18850

But in reality the daemon is not running (subsequent start shows the same thing instead of "already running", stop says that it is not running, and a simple ps -aef|grep <pid> shows that it is not running).

Besides, nothing at all appears in the logs.

**Comment by c-geek** [comment]
Fixed by https://github.com/duniter/duniter-ui/commit/f03c59bed7c1a9349c8505bebe82ae8d0ee6df47
