### ISSUE TITLE
0.31.0 Tx operations: lot of empty space

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#923]
For example here, I have only 4 transactions with no particularities to display, yet I have a lot of unsued space:

![image](https://cloud.githubusercontent.com/assets/969136/24579063/38b395ae-16ee-11e7-8943-8b1a8293f12d.png)

I suppose it has something to do with multiple-receivers transactions of Remuniter, because for UD or other operations I do not have this problem:

![image](https://cloud.githubusercontent.com/assets/969136/24579078/73dc0436-16ee-11e7-8aab-81401829449d.png)

**Comment by M5oul** [comment]
Wrong repository?
I encounter same issue.

**Comment by Insoleet** [comment]
Yes I noticed it too. Also if you enlarge the Uid column, the display is much better... Weird.

**Comment by M5oul** [comment]
Ah, it's the pubkey which cause the issue.

**Comment by c-geek** [comment]
Issue moved to [duniter/sakia #652](https://github.com/duniter/sakia/issues/652) via [**ZenHub**](https://www.zenhub.com/)
