### ISSUE TITLE
Command web(re)start result to stopped daemon

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#937]
```bash
duniter webrestart
Stopping duniter_default daemon...
duniter_default daemon stopped.
Starting duniter_default daemon...
duniter_default daemon stopped.
```
```bash
duniter status
Duniter daemon status: stopped
```

It doesn't works with `webstart`.

**Comment by c-geek** [comment]
Requires UI to be installed in install.sh:
    
    $NODE $NPM install duniter-ui

**Comment by M5oul** [comment]
Thanks!
Works with:
```bash
yarn add duniter-ui
````

**Comment by c-geek** [comment]
Yes but only in `dev`, though.

**Comment by M5oul** [comment]
A warning should say that the daemon couldn't be launched because `duniter-ui` is missing.

**Comment by c-geek** [comment]
I'm working on it, the message will be `Unknown command 'webstart'`. That's logical because the UI installation will be bringing the command to duniter.
