### ISSUE TITLE
Add a `--loglevel` option

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#938]
Which could change the loglevel either in configuration or at runtime.

**Comment by M5oul** [comment]
I always get `trace` log level specifying or without specifying a level.

**Comment by c-geek** [comment]
You don't know how to use this parameter. Try with `config` first.

**Comment by M5oul** [comment]
Ok, it's `duniter config --loglevel info` to configure that on `conf.json` file.
I thought we could use it with `duniter logs --loglevel info`: I opened #945.
Concerning the log level, I still have display with `trace` level even on `conf.json` it's set to `info`.
It is a bug?

**Comment by c-geek** [comment]
You need to restart the node.

**Comment by M5oul** [comment]
Ok, works! Thanks.
