### ISSUE TITLE
Unexpected fork behaviour

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter#950]
My node, which run version 1.2.1, forked two times.

You could [logs on one fork here](https://moul.re/zerobin/?2d16c2342ca06ee6#tU4sqPDNtE+6HpoulGY+QSF4ACrqBDUzPhBZllb0XYY=).

I would put it as a release blocker.

**Comment by c-geek** [comment]
Mine is under 1.2.1 since the release, and don't have any "fork" word in its logs.

**Comment by c-geek** [comment]
Let's wait a bit more and observe.

**Comment by M5oul** [comment]
Yep, there is no `fork` word.
But, on logs PoW computation is very strange.
My node `desktop.moul.re:10901`, is currently on a fork. You could check.

**Comment by M5oul** [comment]
On logs, there is almost 10 blocks gap in one minute. And during this time laps it happen:

```bash
|    8094 | 19:56:38  |   18:53:47   | 000002AE |   mathieuBize    |
|    8093 | 19:52:55  |   18:49:31   | 000006B7 |     nicoleC      |
|    8092 | 19:50:35  |   18:45:09   | 00000D42 | GildasMalassinet |
```

**Comment by c-geek** [comment]
I don't understand what you want to say, what is the problem to you? What clues lead you to this supposition of a problem in the release?

We now have 5 updated nodes, yours, vincentux and I + g1.duniter.org. And I don't see any fork right now in Cesium.

**Comment by M5oul** [comment]
Ok, I didn't saw the release buid were here.
Yep, let's see if it happen again, I reset forked blocks from my node to see.

**Comment by c-geek** [comment]
Note: the Windows + ARM build are broken. I have to make them again.

**Comment by M5oul** [comment]
Ha!
My node is forking because of this:

```bash
warn: Pulling not finished after 10000 ms, continue PoW
```

**Comment by c-geek** [comment]
Hmmm that's possible. But its not a hurry, because we have this code since v1.0.0.

**Comment by M5oul** [comment]
I don't know why my node have blocks late. It's annoying.
I don't know why other node don't encounter this bug.

**Comment by c-geek** [comment]
A possible problem is that peers for the pulling are not selected randomly. So if you always have a timeout on one of them, you can get this bug.

**Comment by M5oul** [comment]
I reset data and sync, and the problem persist.
My node can not retrieve blocks from the network.

**Comment by M5oul** [comment]
Holy shit! I have same problem using the ARM build.
May it come from the fact my nodes are using IPv6?
It seems IPv6 or network related code changed since 1.1.0.
I am not sure it could come from IPv6 as `g1.cgeek.fr` is using IPv6.

**Comment by M5oul** [comment]
It seems fixed on my side.
That's a strange behaviour.
It seems the port of my nodes switch between them.
My node with port 10901 pass to port 38622 on the other the contrary.
That's very strange.

That could be the cause:
```bash
2017-04-07T11:50:34+02:00 - info: Duniter server listening on http://192.168.1.16:38622
2017-04-07T11:50:34+02:00 - info: Duniter server listening on http://[2a01:e34:ee36:b2d0:11:1ff:fec1:e6c4]:10901
```

I will close it if it's ok for a long time.

**Comment by M5oul** [comment]
I reconfigured ports and it doesn't work.
I give up for now.

**Comment by M5oul** [comment]
It seems there is an issue to share peer document.
May be due to this:
```bash
duniter peer duniter.org 10901

2017-04-10T10:44:48+02:00 - debug: Plugging file system...
2017-04-10T10:44:49+02:00 - debug: Loading conf...
2017-04-10T10:44:49+02:00 - debug: Configuration saved.
2017-04-10T10:44:49+02:00 - debug: Opening SQLite database "/root/.config/duniter/duniter_default/duniter.db"...
2017-04-10T10:44:49+02:00 - debug: Upgrade database...
2017-04-10T10:44:49+02:00 - info: Fetching peering record at duniter.org:10901...
2017-04-10T10:44:50+02:00 - info: Apply peering ...
2017-04-10T10:44:50+02:00 - info: Applied
2017-04-10T10:44:50+02:00 - info: Send self peering ...
2017-04-10T10:44:50+02:00 - error: opts is not defined
2017-04-10T10:44:50+02:00 - debug: Trying to close SQLite...
2017-04-10T10:44:50+02:00 - error:  Error: Exiting
    at Error (native)
    at /opt/duniter/sources/node_modules/duniter-crawler/index.js:123:17
    at next (native)
    at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
```

**Comment by c-geek** [comment]
I let you close this ticket if everything seems fine to you with duniter@1.2.2.
