### ISSUE TITLE
Memory leak is still present

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter#978]
We had memory issues like #910, #961, #971.

Even if the memory leak seems fixed, Duniter still has a high memory usage (more than 1GB in RAM).

However when we make a heapdump, we can see only 32MB or RAM usage. This could be explained by Node.js long term memory usage, where Node does not clean its unused objects with Garbage Collector very often, and expands its memory usage as long as GC is not required.

We could set an upper limit for long term memory to 300 MB for example, as it seems to be enough for Duniter to work correctly.

I've tested such value, and Duniter uses ~100MB memory permanently.

**Comment by blaurent49** [comment]
Hello c-geek,
My mirror node eventually went down. I suppose it ran out of memory.
Here is the [link](https://framadrop.org/r/BFZv5OHWLh#cyztaVZvC3rTaVUI3Tk9eIftwyw9VgbRoXg/aPvULwk=) to download the headdump.

**Comment by c-geek** [comment]
There is still a memory leak. I will have to make tests in development mode to find it. I really suspect native addons (C++) to be the hosts of the leak. I will try to loop a lot of times on a block adding, which will fail, to see if the memory increases rapidly due to `wotb` module.

**Comment by blaurent49** [comment]
Hello c-geek,
I had a quick look on the c++ web-of-trust related code (only this part). 
I compiled it with msvc10, which worked fine.
Using visual leak detector, I found 4 memory leaks, lines 310, 331, 352 and 368 of the webOfTrust.cpp file.
If these methods are called by Duniter, the problem is identified. Otherwise, we have to conduct deeper investigations.

**Comment by c-geek** [comment]
Thank you *very* much blaurent49, these seem to be very good candidates to leaking. :+1: 

I will investigate and test all this very soon. I note how these parts of the code could explain very well why wotex (https://wotex.cgeek.fr) node was using more memory than Duniter / Remuniter nodes.

**Comment by blaurent49** [comment]
I have got another question : the goal of the c++ code is to achieve very fast code. Is it sufficient for the moment ?
I am much more familiar with c++ than Node.js. I noticed different potential improvements to fasten the code. If the response time is sufficient, we can let the code as it is. Else, I can propose pull requests.

**Comment by c-geek** [comment]
It is enough right now, very enough. But we can already think forward and the next months / years.

If you have ideas, you should definitely try them. Do not worry, there are tests covering the behavior.

**Comment by c-geek** [comment]
You know, with 500 members with a mean of 10 links between them, we arleady have a 5.000 links WoT to go through. I really prefer to have the bests algorithms we can produce, and the earlier.

**Comment by blaurent49** [comment]
Ok, I shall have a try. I have to better understand the code before.
As far as I understand, the wot is essentially a graph representation. Did you considered using [the boost graph library](http://www.boost.org/doc/libs/1_64_0/libs/graph/doc/) ?

**Comment by c-geek** [comment]
Yes it is an oritented graph. The links are stored on each node, which gathers the *received* links.

I did not considered the boost graph library, because I wanted to do something simple relatively to my C/C++ skills. Also, the graph has to be quiclky storable on a disk file.

**Comment by blaurent49** [comment]
Ok. 
Don't worry : I do not plan to change everything :-).

**Comment by c-geek** [comment]
Some news: it appears that the leak was on line 368. Adding this line fixs the leak:

```c++
delete[] wotDistance;
```

About lines 310, 331 and 352, there is no leak because the memory release occurs in file `functions.cc`, which msvc10 was not aware of.

I will make more tests, but we are on the good way :+1:

**Comment by c-geek** [comment]
I've added a fix constituted of 2 commits: 

* duniter/wotb@6720a4c32ce9ecaddd0a372c6556c4db1e4385ef: a new test suite for detecting leaks
* duniter/wotb@457f0c60b2d179cd6dc94764ec16430ae7a90956: the above fix

I will test this for few days on wotex, and if the results is satisfying I will make a release.

**Comment by blaurent49** [comment]
Good job !
